SYNTAX.md, src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/ast/ModelASTStep.groovy, src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/validator/ModelValidator.groovy, src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/AbstractModelDefTest.java, src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/ValidatorTest.java, src/test/resources/errors/rejectParallelMixedInSteps.groovy, src/test/resources/json/errors/rejectParallelMixedInSteps.json
[JENKINS-37828](https://issues.jenkins-ci.org/browse/JENKINS-37828)
More notably, reject it when it's not the only step in a block. In the
JSON representation, we don't even use the term parallel - we just
have multiple branches. In the groovy parsing, we look for parallel as
the only step in a stage and treat it differently (resulting in
multiple branches). So any time we see parallel as a step by the time
we get to validation, well, it's wrong. So, yeah.
Also, tweaks to make sure we don't end up doing validation of steps we've already blacklisted, because that's silly.
cc @reviewbybees @i386 @michaelneale @oleg-nenashev
=> [FIXED JENKINS-37828] Properly reject parallel

src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/Utils.groovy, src/main/resources/org/jenkinsci/plugins/pipeline/modeldefinition/ModelInterpreter.groovy, src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/BasicModelDefTest.java, src/test/resources/allStagesExist.groovy
[JENKINS-38097](https://issues.jenkins-ci.org/browse/JENKINS-38097)
To ensure that we always have the same stage execution order
(including the synthetic postBuild/notification stages), we now switch
to still running stages after a failure, but not running anything *in*
them. I don't know if there's some way we can set those post-failure
stages as "skipped"?
cc @reviewbybees esp @michaelneale @i386 and @vivek - if you've got any ideas on how to mark a stage skipped, that'd be great. =)
=> [JENKINS-38097] Run empty stages for post-failure stages.

src/main/java/org/jenkinsci/plugins/pipeline/modeldefinition/model/MethodMissingWrapperWhitelist.java, src/main/resources/org/jenkinsci/plugins/pipeline/modeldefinition/ClosureModelTranslator.groovy, src/main/resources/org/jenkinsci/plugins/pipeline/modeldefinition/ModelInterpreter.groovy, src/main/resources/org/jenkinsci/plugins/pipeline/modeldefinition/PropertiesToMapTranslator.groovy, src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/AbstractModelDefTest.java, src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/EnvironmentTest.java, src/test/resources/nonLiteralEnvironment.groovy
[JENKINS-38426](https://issues.jenkins-ci.org/browse/JENKINS-38426)
Allowing fall-through delegation and whitelisting getProperty(s) on
ClosureModelTranslator and PropertiesToMapTranslator lets us do env
vars with values like:
- "${currentBuild.getNumber()}"
- currentBuild.getNumber()
Can't do "${PREVIOUSLY_DEFINED_ENV}_something" yet, though. Still
trying to figure that one out.
This replaces #20 
cc @reviewbybees esp @rsandell @i386 @michaelneale @HRMPW
=> [FIXED JENKINS-38426] Allow non-literal expressions in env vars.

pom.xml
Have seen problems with the default Maven central repo on Azure for
some reason, so hey.
cc @reviewbybees esp @stephenc @rsandell
=> Use repo.jenkins-ci.org in parent POM.

SYNTAX.md, pipeline-model-api/src/main/java/org/jenkinsci/plugins/pipeline/modeldefinition/ast/ModelASTStage.java, pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/model/Stage.groovy, pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/parser/JSONParser.groovy, pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/parser/ModelParser.groovy, pipeline-model-definition/src/main/resources/ast-schema.json, pipeline-model-definition/src/main/resources/org/jenkinsci/plugins/pipeline/modeldefinition/ModelInterpreter.groovy, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/AbstractModelDefTest.java, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/EnvironmentTest.java, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/ToolsTest.java, pipeline-model-definition/src/test/resources/environmentInStage.groovy, pipeline-model-definition/src/test/resources/json/environmentInStage.json, pipeline-model-definition/src/test/resources/json/toolsInStage.json, pipeline-model-definition/src/test/resources/toolsInStage.groovy
[JENKINS-39244](https://issues.jenkins-ci.org/browse/JENKINS-39244), [JENKINS-39245](https://issues.jenkins-ci.org/browse/JENKINS-39245)
Adds support for tools and environment sections inside individual stages.
cc @reviewbybees esp @stephenc @rsandell
=> [FIXED JENKINS-39244, FIXED JENKINS-39245] Add env and tools to stages

pipeline-model-api/src/main/java/org/jenkinsci/plugins/pipeline/modeldefinition/ast/ModelASTPipelineDef.java, pipeline-model-api/src/main/java/org/jenkinsci/plugins/pipeline/modeldefinition/ast/ModelASTStep.java, pipeline-model-api/src/main/java/org/jenkinsci/plugins/pipeline/modeldefinition/ast/ModelASTWrapper.java, pipeline-model-api/src/main/java/org/jenkinsci/plugins/pipeline/modeldefinition/ast/ModelASTWrappers.java, pipeline-model-api/src/main/java/org/jenkinsci/plugins/pipeline/modeldefinition/validator/ModelValidator.java, pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/model/Root.groovy, pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/model/Wrappers.groovy, pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/model/WrappersToMap.groovy, pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/parser/JSONParser.groovy, pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/parser/ModelParser.groovy, pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/validator/ModelValidatorImpl.groovy, pipeline-model-definition/src/main/resources/ast-schema.json, pipeline-model-definition/src/main/resources/org/jenkinsci/plugins/pipeline/modeldefinition/ClosureModelTranslator.groovy, pipeline-model-definition/src/main/resources/org/jenkinsci/plugins/pipeline/modeldefinition/ModelInterpreter.groovy, pipeline-model-definition/src/main/resources/org/jenkinsci/plugins/pipeline/modeldefinition/WrappersToMapTranslator.groovy, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/AbstractModelDefTest.java, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/ValidatorTest.java, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/WrappersTest.java, pipeline-model-definition/src/test/resources/errors/invalidWrapperType.groovy, pipeline-model-definition/src/test/resources/json/errors/invalidWrapperType.json, pipeline-model-definition/src/test/resources/json/multipleWrappers.json, pipeline-model-definition/src/test/resources/json/simpleWrapper.json, pipeline-model-definition/src/test/resources/multipleWrappers.groovy, pipeline-model-definition/src/test/resources/simpleWrapper.groovy
[JENKINS-37823](https://issues.jenkins-ci.org/browse/JENKINS-37823)
Trying to figure out what more tests are needed - note that this doesn't accept the `wrap` step, since it requires a `node` context and we explicitly reject any step that requires a `node`. 
cc @reviewbybees esp @stephenc @rsandell 
Also cc @kuhnroyal since I know you're interested in this functionality. =)
=> [FIXED JENKINS-37823] Added "wrappers" section.

pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/parser/ModelParser.groovy
We're not supporting backwards compatibility for syntax that we change
before 1.0, but we should give clear error messages explaining what
has changed. At this point, this is the only compatibility-breaking
syntactic change.
cc @reviewbybees esp @rsandell @HRMPW @michaelneale
=> Explain that steps section is needed in stages.

pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/Utils.groovy, pipeline-model-definition/src/main/java/org/jenkinsci/plugins/pipeline/modeldefinition/agent/impl/DockerPipelineFromDockerfile.java, pipeline-model-definition/src/main/resources/org/jenkinsci/plugins/pipeline/modeldefinition/agent/impl/DockerPipelineFromDockerfileScript.groovy, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/AbstractModelDefTest.java, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/AgentTest.java, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/ValidatorTest.java, pipeline-model-definition/src/test/resources/fromAlternateDockerfile.groovy, pipeline-model-definition/src/test/resources/fromDockerfile.groovy
[JENKINS-39216](https://issues.jenkins-ci.org/browse/JENKINS-39216)
Not happy with the naming - but I needed a map key/value pair for this, so went with `dockerfileImage` as the unique identifier for this backend. The actual image name will be that string plus the `Dockerfile`'s sha1 hash. I'm open to better naming.
cc @reviewbybees esp @michaelneale @HRMPW @stephenc @rsandell
=> [JENKINS-39216] Add "dockerfile" agent backend

pipeline-model-definition/src/main/resources/org/jenkinsci/plugins/pipeline/modeldefinition/ModelInterpreter.groovy
Moved blocks of logic out into their own methods for actual
stage/post-stage execution, notifications and postBuild.
Switched all ModelInterpreter methods previously returning Closures to
instead call() those Closures. This *drastically* simplified the main
method's readability.
Still need to Javadoc all the ModelInterpreter methods and move a bit
more into separate methods from the main method.
Note that we're still using call() on Closures and returning the
results because...well, otherwise things just don't work. More
experimentation is needed to remember exactly why we need to do this,
but I believe it's to do with getting execution timing right.
=> Refactoring ModelInterpreter for easier maintenance

pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/parser/ModelParser.groovy, pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/validator/ModelValidatorImpl.groovy, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/ValidatorTest.java, pipeline-model-definition/src/test/resources/errors/badPostContent.groovy
[JENKINS-39799](https://issues.jenkins-ci.org/browse/JENKINS-39799)
We actually would have errored out properly-ish if it wasn't for the
fact that we ended up with a ModelASTBuildCondition with null
condition and null branch, leading to the NPE during compilation. I
decided to improve the error messaging and make sure we don't attempt
to validate further when condition or branch are null.
=> [FIXED JENKINS-39799] Properly handle bad content in post blocks.

pom.xml
Picks up https://github.com/jenkinsci/gmaven/commit/cd59639ce48c9f62e08b6808b724e280fdb63e2d.
I had thought this would solve the NPE from `ClosureModelTranslator` during compile-on-save test runs, but it does not. From
```diff
diff --git a/pipeline-model-definition/src/main/resources/org/jenkinsci/plugins/pipeline/modeldefinition/ClosureModelTranslator.groovy b/pipeline-model-definition/src/main/resources/org/jenkinsci/plugins/pipeline/modeldefinition/ClosureModelTranslator.groovy
index 011bf17..abcd6d3 100644
--- a/pipeline-model-definition/src/main/resources/org/jenkinsci/plugins/pipeline/modeldefinition/ClosureModelTranslator.groovy
+++ b/pipeline-model-definition/src/main/resources/org/jenkinsci/plugins/pipeline/modeldefinition/ClosureModelTranslator.groovy
@@ -63,6 +63,7 @@ public …
```
=> Use default GMaven plugin version

pipeline-model-api/src/main/resources/index.jelly, pipeline-model-declarative-agent/src/main/resources/index.jelly, pipeline-model-definition/pom.xml, pipeline-model-definition/src/main/java/org/jenkinsci/plugins/pipeline/modeldefinition/steps/ScriptStep.java, pipeline-model-definition/src/main/resources/index.jelly, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/steps/ScriptStepTest.java, pipeline-stage-tags-metadata/src/main/resources/index.jelly
[JENKINS-39134](https://issues.jenkins-ci.org/browse/JENKINS-39134)
My initial thought was that a missing `optional = true` attribute on `@Inject` would solve the issue; but it did not, and that would not explain the `withMaven` problem anyway. At any rate, this fix works for this plugin, and I will track down the `pipeline-maven` bug separately.
@reviewbybees
=> [JENKINS-39134] Fix CreationException when resuming inside script {}

pipeline-model-definition/pom.xml, pipeline-model-definition/src/main/java/org/jenkinsci/plugins/pipeline/modeldefinition/DeclarativeLinterCommand.java, pipeline-model-definition/src/main/java/org/jenkinsci/plugins/pipeline/modeldefinition/endpoints/ModelConverterAction.java, pipeline-model-definition/src/main/resources/org/jenkinsci/plugins/pipeline/modeldefinition/Messages.properties, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/DeclarativeLinterCommandTest.java
[JENKINS-39923](https://issues.jenkins-ci.org/browse/JENKINS-39923)
Can be used like:
```
ssh -p [sshd port on master] localhost declarative-linter < Jenkinsfile
```
or
```
curl -X POST -H `curl 'JENKINS_URL/crumbIssuer/api/xml?xpath=concat(//crumbRequestField,":",//crumb)'` -F 'jenkinsfile="@Jenkinsfile"' JENKINS_URL/pipeline-model-converter/validate
```
(the `crumbIssuer` bit is needed if your Jenkins master has CRSF enabled, as it should)
Example output:
Invalid:
```
ssh -p 8675 localhost declarative-linter < src/test/resources/errors/emptyAgent.groovy
Errors encountered validating Jenkinsfile:
WorkflowScript: 25: Not a valid section definition: 'agent'. Some extra configuration is required. @ line 25, column 1.
pipeline {
^
WorkflowScript: 25: Missing required section 'agent' @ line …
```
=> [FIXED JENKINS-39923] Add a CLI endpoint for the linter

pipeline-model-definition/src/main/java/org/jenkinsci/plugins/pipeline/modeldefinition/steps/DockerLabelStep.java, pipeline-model-definition/src/main/java/org/jenkinsci/plugins/pipeline/modeldefinition/steps/EnvVarsForToolStep.java
This is so they don't show up in the Snippet Generator or the eventual
Pipeline Editor step choice UI, since they only exist for internal purposes.
@kzantow - this covers one of the things we talked about today.
=> Make internal-only steps advanced.

pipeline-model-definition/pom.xml, pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/model/Wrappers.groovy, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/AbstractModelDefTest.java
More narrowly scoped than the previous requiring it to be empty. That
ended up bugging out with TimeoutStep from workflow-basic-steps 2.3
(probably due to some other change elsewhere in the dependency tree,
since TimeoutStep itself didn't change between 2.2 and 2.3, though
TimeoutStepExecution did). So switching!
=> Switch to requiring no Launcher in getRequiredContext() for wrappers

pipeline-model-api/src/main/java/org/jenkinsci/plugins/pipeline/modeldefinition/ast/ModelASTBuildParameter.java, pipeline-model-api/src/main/java/org/jenkinsci/plugins/pipeline/modeldefinition/ast/ModelASTJobProperty.java, pipeline-model-api/src/main/java/org/jenkinsci/plugins/pipeline/modeldefinition/ast/ModelASTScriptBlock.java, pipeline-model-api/src/main/java/org/jenkinsci/plugins/pipeline/modeldefinition/ast/ModelASTTrigger.java, pipeline-model-api/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/validator/ModelValidatorTest.java, pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/validator/ModelValidatorImpl.groovy, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/AbstractModelDefTest.java, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/ValidatorTest.java, pipeline-model-definition/src/test/resources/errors/invalidParameterType.groovy, pipeline-model-definition/src/test/resources/errors/invalidPropertiesType.groovy, pipeline-model-definition/src/test/resources/errors/invalidTriggerType.groovy
[JENKINS-40418](https://issues.jenkins-ci.org/browse/JENKINS-40418)
Turns out we do need validate methods on child classes - the parent
validate method will end up calling
validator.validateElement(ParentClass) which is...not what we
want. So, fixing that in a bunch of places and adding tests.
Also, added an expectError convenience method.
=> [FIXED JENKINS-40418] Fix validation for a number of extended types

pipeline-model-definition/src/main/java/org/jenkinsci/plugins/pipeline/modeldefinition/endpoints/ModelConverterAction.java, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/endpoints/ModelConverterActionTest.java
The previous error message was...annoying. So now let's do a null/empty check before we try to do something with the erstwhile content.
=> Give a better error message if no content for endpoint param

pipeline-model-definition/pom.xml, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/BasicModelDefTest.java, pipeline-model-definition/src/test/resources/booleanParamBuildStep.groovy
[JENKINS-40188](https://issues.jenkins-ci.org/browse/JENKINS-40188)
Can't actually reproduce the issue with 'env.PARAM' or 'params.PARAM',
but can with '"${env.PARAM}"'. If there's a deeper problem here, it's
that we're not actually validating the parameters to the parameters of
steps themselves, but that's a different matter.
=> [JENKINS-40188] Test to verify that boolean params can be passed on.

pipeline-model-definition/pom.xml, pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/parser/Converter.groovy, pipeline-model-definition/src/main/java/org/jenkinsci/plugins/pipeline/modeldefinition/parser/GroovyShellDecoratorImpl.java, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/BasicModelDefTest.java, pipeline-model-definition/src/test/resources/libraryAnnotation.groovy
[JENKINS-40642](https://issues.jenkins-ci.org/browse/JENKINS-40642)
@NonCPS and @Library were the most glaring missing import, but I
replicated the standard CpsGroovyShell imports - @NonCPS's package,
hudson.model, jenkins.model, and anything provided by a GroovyShellDecorator.
cc @reviewbybees esp @rsandell @kohsuke and @imod
=> [FIXED JENKINS-40642] Add additional imports for parse/translate

pipeline-model-declarative-agent/src/main/java/org/jenkinsci/plugins/pipeline/modeldefinition/agent/DeclarativeAgentDescriptor.java, pipeline-model-definition/src/main/java/org/jenkinsci/plugins/pipeline/modeldefinition/agent/impl/Any.java, pipeline-model-definition/src/main/java/org/jenkinsci/plugins/pipeline/modeldefinition/agent/impl/Label.java
[JENKINS-40790](https://issues.jenkins-ci.org/browse/JENKINS-40790)
https://github.com/jenkinsci/pipeline-model-definition-plugin/commit/762ee84a08b7881906ce5b7a6e04d27229d499d7 is the only relevant commit - the rest is on top of https://github.com/jenkinsci/pipeline-model-definition-plugin/pull/78, since that PR/branch messes around a lot with `DeclarativeAgentDescriptor` and I decided to save the mess by just doing this on top.
cc @reviewbybees esp @rsandell and @kzantow
=> [JENKINS-40790] Add metadata for whether agents support tools

pipeline-model-api/src/main/java/org/jenkinsci/plugins/pipeline/modeldefinition/ast/ModelASTValue.java, pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/Utils.groovy, pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/parser/Converter.groovy, pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/parser/JSONParser.groovy, pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/validator/ErrorCollector.groovy, pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/validator/JSONErrorCollector.groovy, pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/validator/ModelValidatorImpl.groovy, pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/validator/SourceUnitErrorCollector.groovy, pipeline-model-definition/src/main/java/org/jenkinsci/plugins/pipeline/modeldefinition/DeclarativeLinterCommand.java, pipeline-model-definition/src/main/java/org/jenkinsci/plugins/pipeline/modeldefinition/endpoints/ModelConverterAction.java, pipeline-model-definition/src/main/resources/org/jenkinsci/plugins/pipeline/modeldefinition/Messages.properties, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/AbstractModelDefTest.java, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/endpoints/ErrorsEndpointOpsTest.java, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/endpoints/ModelConverterActionTest.java, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/endpoints/SuccessfulEndpointOpsTest.java, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/parser/ConvertRoundTripTest.java, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/parser/ExecuteConvertedTest.java, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/validator/ErrorsJSONParserTest.java, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/validator/JSONValidationTest.java, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/validator/SuccessfulJSONParserTest.java, pipeline-model-definition/src/test/resources/json/errors/parallelPipelineDuplicateNames.json
[JENKINS-40793](https://issues.jenkins-ci.org/browse/JENKINS-40793)
Specifically to the JSON output. This also moves us to not doing
conversion between JSONObject and JsonNode, which is nice. There's
probably some cleanup/optimization that could still be done in
JSONParser.
cc @reviewbybees esp @kzantow @rsandell
=> [FIXED JENKINS-40793] Add location information to validation errors

pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/model/AbstractBuildConditionResponder.groovy, pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/model/Root.groovy, pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/model/Stage.groovy, pipeline-model-definition/src/main/java/org/jenkinsci/plugins/pipeline/modeldefinition/model/BuildCondition.java, pipeline-model-definition/src/main/resources/org/jenkinsci/plugins/pipeline/modeldefinition/ModelInterpreter.groovy, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/BuildConditionResponderTest.java, pipeline-model-definition/src/test/resources/postChecksAllConditions.groovy
[JENKINS-40984](https://issues.jenkins-ci.org/browse/JENKINS-40984)
Even if there's an error in an earlier condition execution, continue
to the subsequent ones. Additionally, switch to doing a one-off check
at the beginning of the post section to see if *any* conditions are
satisfied at that time, and then when actually iterating through the
conditions, check for satisfaction at *that* time. That's so that, for
example, if the build is successful when it gets to evaluating post
conditions and then there's a failure in the execution of `always`,
the `success` block won't be executed, and the `failure` block will,
since the build status has changed.
cc @reviewbybees esp @rsandell @batmat
=> [FIXED JENKINS-40984] Always evaluate/run all post conditions

pipeline-model-api/src/main/java/org/jenkinsci/plugins/pipeline/modeldefinition/ast/ModelASTAgent.java, pipeline-model-api/src/main/java/org/jenkinsci/plugins/pipeline/modeldefinition/ast/ModelASTPipelineDef.java, pipeline-model-api/src/main/java/org/jenkinsci/plugins/pipeline/modeldefinition/ast/ModelASTStages.java, pipeline-model-api/src/main/java/org/jenkinsci/plugins/pipeline/modeldefinition/ast/ModelASTStep.java, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/endpoints/ModelConverterActionStepsTest.java
[JENKINS-41089](https://issues.jenkins-ci.org/browse/JENKINS-41089)
[JENKINS-41090](https://issues.jenkins-ci.org/browse/JENKINS-41090)
Get rid of superfluous newlines, make sure we have a newline after
'label "foo"', don't serialize unneeded parentheses for single unnamed
arguments for steps/functions.
cc @reviewbybees esp @rsandell @i386
=> [FIXED JENKINS-41090, JENKINS-41089] Groovy serialization cleanup

pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/SyntheticStageNames.groovy, pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/Utils.groovy, pipeline-model-definition/src/main/java/org/jenkinsci/plugins/pipeline/modeldefinition/SyntheticStageGraphListener.java, pipeline-model-definition/src/main/java/org/jenkinsci/plugins/pipeline/modeldefinition/actions/ExecutionModelAction.java, pipeline-model-definition/src/main/resources/org/jenkinsci/plugins/pipeline/modeldefinition/ModelInterpreter.groovy, pipeline-model-definition/src/main/resources/org/jenkinsci/plugins/pipeline/modeldefinition/agent/impl/DockerPipelineFromDockerfileScript.groovy, pipeline-model-definition/src/main/resources/org/jenkinsci/plugins/pipeline/modeldefinition/agent/impl/DockerPipelineScript.groovy, pipeline-model-definition/src/main/resources/org/jenkinsci/plugins/pipeline/modeldefinition/agent/impl/LabelScript.groovy, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/BasicModelDefTest.java, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/SyntheticStageGraphListenerTest.java
[JENKINS-41243](https://issues.jenkins-ci.org/browse/JENKINS-41243)
This approach yielded an average time from just before the stage call
to just before actually attaching the tag of 15.4ms over 5 runs, vs
40.8ms over 5 runs with the previous approach. I'm sure there are many
things wrong with this approach, though.
cc @reviewbybees esp @rsandell @svanoort @vivek @jglick
=> [JENKINS-41243] Slightly faster tagging of synthetic stages

pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/SyntheticStageNames.groovy, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/OptionsTest.java, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/TriggersTest.java
Once upon a time the syntax was called "postBuild' but was renamed to "post"
and this label never got updated.
=> Correct the synthetic "Post" stage label

pipeline-model-api/src/main/resources/ast-schema.json, pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/validator/ModelValidatorImpl.groovy, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/AbstractModelDefTest.java, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/BasicModelDefTest.java, pipeline-model-definition/src/test/resources/json/nestedTreeSteps.json, pipeline-model-definition/src/test/resources/nestedTreeSteps.groovy
[JENKINS-41490](https://issues.jenkins-ci.org/browse/JENKINS-41490), [JENKINS-41491](https://issues.jenkins-ci.org/browse/JENKINS-41491)
So this started with fixing JENKINS-41490, so that the editor can
actually do nested tree steps (d'oh), but in the process, I discovered
a strange decision from waaaaaay back in the day to force validation
in certain cases to treat the step parameter type as a String, even
when it wasn't one. That...was bad. So, fixing both those things.
Note that these are both blockers - JENKINS-41490 is hosing the editor and JENKINS-41491 is just plain stupid. So long as this doesn't cause any test regressions (which it hasn't in my local testing), this is going in 0.9.1.
cc @reviewbybees esp @rsandell @kzantow
=> [FIXED JENKINS-41490, JENKINS-41491] Tree steps and validation!

pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/Utils.groovy, pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/validator/ModelValidatorImpl.groovy, pipeline-model-definition/src/main/resources/org/jenkinsci/plugins/pipeline/modeldefinition/Messages.properties, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/BaseParserLoaderTest.java, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/validator/ErrorsJSONParserTest.java, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/validator/JSONValidationTest.java, pipeline-model-definition/src/test/resources/json/errors/invalidIdentifierInEnv.json
[JENKINS-41518](https://issues.jenkins-ci.org/browse/JENKINS-41518)
Specifically for validity as Java identifiers - otherwise everything
'splodes. This was never a problem from the Jenkinsfile side, since
there'd be compilation errors before getting to validation if you used
an invalid identifier, but it *is* a problem coming from JSON.
cc @reviewbybees esp @rsandell @kzantow
=> [FIXED JENKINS-41518] Validate env var names for validity

pipeline-model-api/pom.xml, pipeline-model-declarative-agent/pom.xml, pipeline-model-definition/pom.xml, pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/parser/Converter.groovy, pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/parser/JSONParser.groovy, pipeline-model-definition/src/main/java/org/jenkinsci/plugins/pipeline/modeldefinition/endpoints/ModelConverterAction.java, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/BaseParserLoaderTest.java, pipeline-model-json-shaded/pom.xml, pipeline-stage-tags-metadata/pom.xml, pom.xml
* [JENKINS-41911](https://issues.jenkins-ci.org/browse/JENKINS-41911)
* Description:
* This took some hoop-jumping, but now we should be guaranteed to use our own copy of Jackson at all times. Phew. Note that I added a test dependency on the `jackson2-api` plugin, basically to prove that this works, since the tests fail hard without the shade change but with that plugin.
* n/a - purely internal change, not at all user facing.
* @rsandell 
* @kzantow
=> [FIXED JENKINS-41911] Shade away Jackson

pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/AbstractModelDefTest.java, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/AgentTest.java, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/ValidatorTest.java, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/agent/impl/NestedConf.java, pipeline-model-definition/src/test/resources/multipleVariablesForAgent.groovy, pipeline-model-definition/src/test/resources/org/jenkinsci/plugins/pipeline/modeldefinition/agent/impl/LabelAndOtherFieldAgentScript.groovy
* n/a - this is just adding a test for something that already works.
* Description:
* Adding a test to verify that you can use nested describables within an agent's configuration, which will be relevant for, say, Kubernetes. This already works, but I wanted to make sure we had a test for it so that we don't inadvertently break this behavior in the future.
* n/a - purely internal test.
* @rsandell
=> Verifying that nested describables can be used with agent config

pipeline-model-definition/src/main/java/org/jenkinsci/plugins/pipeline/modeldefinition/config/GlobalConfig.java, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/DurabilityTest.java
* [JENKINS-42027](https://issues.jenkins-ci.org/browse/JENKINS-42027)
* Description:
* We weren't doing this before, and so the settings in GlobalConfig weren't being persisted. That was an oopsie, but this is an easy fix.
* n/a - bug fix, no docs to change
* @rsandell
=> [FIXED JENKINS-42027] Actually load GlobalConfig from disk

pipeline-model-definition/src/main/resources/org/jenkinsci/plugins/pipeline/modeldefinition/ModelInterpreter.groovy, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/AgentTest.java, pipeline-model-definition/src/test/resources/nonExistentDockerImage.groovy
* [JENKINS-41950](https://issues.jenkins-ci.org/browse/JENKINS-41950)
* Description:
* We hadn't been reporting errors in the pre-stage blocks as `firstError`, so they were getting swallowed, particularly if the `post` that gets run if there are errors pre-stage itself had errors (i.e., due to running `deleteDir()` outside a node context. So now let's catch said pre-stage errors, report them properly, etc.
* n/a - internal fix.
* @rsandell
=> [FIXED JENKINS-41950] Properly report errors outside stages

pipeline-model-declarative-agent/src/main/java/org/jenkinsci/plugins/pipeline/modeldefinition/agent/DeclarativeAgent.java, pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/model/Agent.groovy, pipeline-model-definition/src/main/resources/org/jenkinsci/plugins/pipeline/modeldefinition/agent/impl/AbstractDockerPipelineScript.groovy, pipeline-model-definition/src/main/resources/org/jenkinsci/plugins/pipeline/modeldefinition/agent/impl/AnyScript.groovy, pipeline-model-definition/src/main/resources/org/jenkinsci/plugins/pipeline/modeldefinition/agent/impl/LabelScript.groovy, pipeline-model-definition/src/test/resources/org/jenkinsci/plugins/pipeline/modeldefinition/agent/impl/LabelAndOtherFieldAgentScript.groovy
* Follow up to [JENKINS-41900](https://issues.jenkins-ci.org/browse/JENKINS-41900)
* Description:
* There's no actual good reason for carrying the whole context (i.e., Root or Stage object) around in the DeclarativeAgent when all we need to know is whether we're already in a stage. So...switch that to a boolean and have Agent.groovy check whether the context it's handed is a Root instance. If it is a Root instance, we're not in a stage. If it isn't a Root instance, we are in a stage. Tada.
* And yes, this is an API change, but https://github.com/jenkinsci/kubernetes-plugin/pull/127 is the only thing yet using that API and I'm changing it specifically *for* that PR. =)
* n/a, just an API change.
* …
=> Followup to JENKINS-41900 - just record if in stage

pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/parser/ModelParser.groovy, pipeline-model-definition/src/main/resources/org/jenkinsci/plugins/pipeline/modeldefinition/Messages.properties, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/EnvironmentTest.java, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/ValidatorTest.java, pipeline-model-definition/src/test/resources/errors/envIdentifierDigitsUnderscore.groovy, pipeline-model-definition/src/test/resources/errors/envIdentifierHyphens.groovy, pipeline-model-definition/src/test/resources/errors/envIdentifierStartingWithDigit.groovy, pipeline-model-definition/src/test/resources/errors/envIdentifierString.groovy, pipeline-model-definition/src/test/resources/errors/envIdentifiersCaughtInternally.groovy, pipeline-model-definition/src/test/resources/errors/invalidEnvironmentIdentifiers.groovy
[JENKINS-41645](https://issues.jenkins-ci.org/browse/JENKINS-41645)
We can't handle all invalid environment identifiers currently - things
like 123_ABC or something-with-hyphens or 'somethingInQuotes' all end
up failing out at initial Groovy compilation, before we get the AST to
work with. We do catch those when coming from JSON, which is
something. But until this, we didn't give useful errors for any
invalid environment identifier that actually gets through compilation
- i.e., 3D_GLASSES, 123ABC. Those aren't BinaryExpressions, so they
were skipped and we ended up with just the general error case
reporting. This commit changes that. =)
cc @reviewbybees esp @rsandell and @orrc
=> [JENKINS-41645] Better validation for non-binary expressions in env

pipeline-model-api/src/main/java/org/jenkinsci/plugins/pipeline/modeldefinition/SyntheticStageNames.java, pipeline-model-definition/src/main/resources/org/jenkinsci/plugins/pipeline/modeldefinition/agent/impl/LabelScript.groovy
* n/a
* Description:
* Minor tweak - want to have the `SyntheticStageNames` class somewhere it can be picked up without depending on literally everything else.
* n/a
* @rsandell
=> Relocate SyntheticStageNames to model-api

pipeline-model-definition/src/main/java/org/jenkinsci/plugins/pipeline/modeldefinition/when/impl/BranchConditional.java, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/BasicModelDefTest.java, pipeline-model-definition/src/test/resources/whenBranchNull.groovy
* [JENKINS-42226](https://issues.jenkins-ci.org/browse/JENKINS-42226)
* Description:
* We should be null-checking `compare` in all cases as well as `actualBranch`, and if either is null/empty, we should return false. This change does that.
* n/a
* @rsandell 
* @imod
=> [FIXED JENKINS-42226] Treat null/empty branch comparison as false

pipeline-model-definition/src/main/java/org/jenkinsci/plugins/pipeline/modeldefinition/steps/ValidateDeclarativePipelineStep.java, pipeline-model-definition/src/main/resources/org/jenkinsci/plugins/pipeline/modeldefinition/steps/ValidateDeclarativePipelineStep/config.jelly, pipeline-model-definition/src/main/resources/org/jenkinsci/plugins/pipeline/modeldefinition/steps/ValidateDeclarativePipelineStep/help-path.html, pipeline-model-definition/src/main/resources/org/jenkinsci/plugins/pipeline/modeldefinition/steps/ValidateDeclarativePipelineStep/help.html, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/AbstractModelDefTest.java, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/steps/ValidateDeclarativePipelineStepTest.java, pipeline-model-definition/src/test/resources/validateDeclarativePipelineStep.groovy
* [JENKINS-42168](https://issues.jenkins-ci.org/browse/JENKINS-42168)
* Description:
* Given a path to a file containing a Declarative Pipeline to validate, this will read that file from the workspace, validate its contents, echo out relevant errors to the build log, and return true if the contents validated, or false other wise.
* TBD?
* @rsandell 
* @jtnord 
* @batmat
=> [FIXED JENKINS-42168] Add validateDeclarativePipeline(path) step

pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/validator/ModelValidatorImpl.groovy, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/AgentTest.java, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/ValidatorTest.java, pipeline-model-definition/src/test/resources/dirSepInDockerfileName.groovy
* [JENKINS-42286](https://issues.jenkins-ci.org/browse/JENKINS-42286)
* Description:
* Turns out this was a regression we shouldn't have allowed - directory separators should be allowed in the `Dockerfile` filename.
* n/a
* @rsandell
=> [FIXED JENKINS-42286] Allow dir separator in Dockerfile name

pipeline-model-definition/src/main/java/org/jenkinsci/plugins/pipeline/modeldefinition/endpoints/ModelConverterAction.java, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/WhenStageTest.java, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/endpoints/ErrorsEndpointOpsTest.java, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/endpoints/ModelConverterActionStepsTest.java, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/endpoints/ModelConverterActionTest.java, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/endpoints/SuccessfulEndpointOpsTest.java
* [JENKINS-42470](https://issues.jenkins-ci.org/browse/JENKINS-42470)
* Description:
* Add a `CrumbExclusion` extension to get rid of the need for a crumb on `ModelConverterAction` calls, since there are no side effects to any of its endpoints.  Additionally, the permission should be changed to `Jenkins.READ` rather than `Permission.READ`.
* None directly, but [WEBSITE-324](https://issues.jenkins-ci.org/browse/WEBSITE-324) is relevant.
* @rsandell 
* @jglick
=> [FIXED JENKINS-42470] Use CrumbExclusion and Jenkins.READ perms

pipeline-model-api/src/main/java/org/jenkinsci/plugins/pipeline/modeldefinition/ast/ModelASTLibraries.java, pipeline-model-api/src/main/java/org/jenkinsci/plugins/pipeline/modeldefinition/ast/ModelASTPipelineDef.java, pipeline-model-api/src/main/java/org/jenkinsci/plugins/pipeline/modeldefinition/validator/ModelValidator.java, pipeline-model-api/src/main/resources/ast-schema.json, pipeline-model-definition/pom.xml, pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/model/Libraries.groovy, pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/model/Root.groovy, pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/parser/JSONParser.groovy, pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/parser/ModelParser.groovy, pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/validator/ModelValidatorImpl.groovy, pipeline-model-definition/src/main/resources/org/jenkinsci/plugins/pipeline/modeldefinition/ClosureModelTranslator.groovy, pipeline-model-definition/src/main/resources/org/jenkinsci/plugins/pipeline/modeldefinition/LibrariesTranslator.groovy, pipeline-model-definition/src/main/resources/org/jenkinsci/plugins/pipeline/modeldefinition/Messages.properties, pipeline-model-definition/src/main/resources/org/jenkinsci/plugins/pipeline/modeldefinition/ModelInterpreter.groovy, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/AbstractModelDefTest.java, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/BasicModelDefTest.java, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/ValidatorTest.java, pipeline-model-definition/src/test/resources/errors/emptyLibrariesDirective.groovy, pipeline-model-definition/src/test/resources/errors/invalidLibrariesDirectiveContent.groovy, pipeline-model-definition/src/test/resources/librariesDirective.groovy, pom.xml
* [JENKINS-38110](https://issues.jenkins-ci.org/browse/JENKINS-38110)
* Description:
* Initial work on adding a `libraries` section to Declarative. Current syntax looks like:
```groovy
libraries {
lib('foo@1.2.3')
lib('bar')
}
```
Yes, I'd prefer not to have that pointless `lib` there, but the alternative is something like `libraries 'foo@1.2.3', 'bar'` and as we may remember from `agent` back in the day, I do not care for that syntax at _all_. Plus, we may end up wanting to include the ability to specify a `LibraryRetriever` (see [LibraryRetriever.java in workflow-cps-global-lib](https://github.com/jenkinsci/workflow-cps-global-lib-plugin/blob/master/src/main/java/org/jenkinsci/plugins/workflow/libs/LibraryRetriever.java) for details), in which case going to …
=> [JENKINS-38110] Add a libraries section

pipeline-model-definition/pom.xml, pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/model/Agent.groovy, pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/parser/JSONParser.groovy, pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/parser/ModelParser.groovy, pipeline-model-definition/src/main/java/org/jenkinsci/plugins/pipeline/modeldefinition/agent/AbstractDockerAgent.java, pipeline-model-definition/src/main/java/org/jenkinsci/plugins/pipeline/modeldefinition/agent/impl/Label.java, pipeline-model-definition/src/main/java/org/jenkinsci/plugins/pipeline/modeldefinition/options/impl/WorkspaceDir.java, pipeline-model-definition/src/main/resources/org/jenkinsci/plugins/pipeline/modeldefinition/ModelInterpreter.groovy, pipeline-model-definition/src/main/resources/org/jenkinsci/plugins/pipeline/modeldefinition/agent/impl/AbstractDockerPipelineScript.groovy, pipeline-model-definition/src/main/resources/org/jenkinsci/plugins/pipeline/modeldefinition/agent/impl/LabelScript.groovy, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/AbstractModelDefTest.java, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/BasicModelDefTest.java, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/parser/ModelParserTest.java, pipeline-model-definition/src/test/resources/inAbsoluteCustomWorkspace.groovy, pipeline-model-definition/src/test/resources/inCustomWorkspace.groovy, pipeline-model-definition/src/test/resources/inCustomWorkspaceInStage.groovy, pipeline-model-definition/src/test/resources/inRelativeCustomWorkspace.groovy, pipeline-model-definition/src/test/resources/inWorkspace.groovy, pipeline-model-definition/src/test/resources/json/inCustomWorkspace.json, pipeline-model-definition/src/test/resources/json/inRelativeCustomWorkspace.json, pipeline-model-extensions/pom.xml, pipeline-model-extensions/src/main/java/org/jenkinsci/plugins/pipeline/modeldefinition/agent/DeclarativeAgent.java, pipeline-model-extensions/src/main/resources/org/jenkinsci/plugins/pipeline/modeldefinition/agent/CheckoutScript.groovy, pom.xml, rfc/JENKINS-41118-custom-workspaces.md
* [JENKINS-41118](https://issues.jenkins-ci.org/browse/JENKINS-41118)
* Description:
* Enables custom workspaces in Declarative as an `agent` option.
* RFC document:
* https://github.com/abayer/pipeline-model-definition-plugin/blob/jenkins-41118/rfc/JENKINS-41118-custom-workspaces.md
* Doc update will be needed for the new `customWorkspace` option for `label`, `docker` and `dockerfile`.
* @rsandell
=> [JENKINS-41118] Allow specifying top level ws(...) block

pipeline-model-api/src/main/java/org/jenkinsci/plugins/pipeline/modeldefinition/ast/ModelASTWhen.java, pipeline-model-api/src/main/resources/ast-schema.json, pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/Utils.groovy, pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/model/StageConditionals.groovy, pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/parser/JSONParser.groovy, pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/parser/ModelParser.groovy, pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/validator/ModelValidatorImpl.groovy, pipeline-model-definition/src/main/resources/org/jenkinsci/plugins/pipeline/modeldefinition/ModelInterpreter.groovy, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/AbstractModelDefTest.java, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/BasicModelDefTest.java, pipeline-model-definition/src/test/resources/json/basicWhen.json, pipeline-model-definition/src/test/resources/json/errors/emptyWhen.json, pipeline-model-definition/src/test/resources/json/errors/unknownWhenConditional.json, pipeline-model-definition/src/test/resources/json/errors/whenInvalidParameterType.json, pipeline-model-definition/src/test/resources/json/errors/whenMissingRequiredParameter.json, pipeline-model-definition/src/test/resources/json/errors/whenUnknownParameter.json, pipeline-model-definition/src/test/resources/json/skippedWhen.json, pipeline-model-definition/src/test/resources/json/whenAnd.json, pipeline-model-definition/src/test/resources/json/whenBranchFalse.json, pipeline-model-definition/src/test/resources/json/whenEnvFalse.json, pipeline-model-definition/src/test/resources/json/whenNot.json, pipeline-model-definition/src/test/resources/json/whenOr.json, pipeline-model-definition/src/test/resources/whenMultiple.groovy
* [JENKINS-42762](https://issues.jenkins-ci.org/browse/JENKINS-42762)
* Description:
* Reverts changes made in JENKINS-41185 fix. Does not affect the core of the changes in JENKINS-41185 - nested `when` conditions still work exactly the same, we're just back to allowing multiple top-level `when` conditions, where if any of them fail/return false, the `when` is not satisfied. This came to light when [a user reported the regression](https://github.com/jenkinsci/pipeline-model-definition-plugin/pull/125#issuecomment-286322236) so I consider it a priority.
* n/a
* @rsandell 
* @kzantow due to `ast-schema.json` reversion.
=> [FIXED JENKINS-42762] Allow multiple conditions in when directly

rfc/JENKINS-41334-parallel-stage-execution.md
* [JENKINS-41334](https://issues.jenkins-ci.org/browse/JENKINS-41334)
* Description:
* RFC for parallel stages in Declarative. https://github.com/jenkinsci/pipeline-model-definition-plugin/pull/98 is pertinent. 
* n/a - this is just an RFC.
* @rsandell 
* @HRMPW 
* @kzantow
* @michaelneale 
* @i386
* @bitwiseman
=> RFC: JENKINS-41334: Parallel stage execution

pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/parser/ModelParser.groovy, pipeline-model-definition/src/main/resources/org/jenkinsci/plugins/pipeline/modeldefinition/Messages.properties, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/EnvironmentTest.java, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/ValidatorTest.java, pipeline-model-definition/src/test/resources/errors/invalidMultiExpressionEnvironment.groovy, pipeline-model-definition/src/test/resources/multiExpressionEnvironment.groovy
* [JENKINS-42771](https://issues.jenkins-ci.org/browse/JENKINS-42771)
* Description:
* This worked previously because we didn't actually pay attention to what was really in the value for an environment variable in the AST model, only at runtime. And the runtime parsing worked differently, so it did fine with `FOO = "A" + "B" + "C"`. Well, now so does the AST model. Yay!
* n/a, I think? @bitwiseman, I don't think we should be explicitly documenting that this works, especially since `FOO = "A" + "B" + "C"` will actually roundtrip through the editor to be `FOO = "ABC"`, since we concatenate the strings at parse time...
* @rsandell
=> [FIXED JENKINS-42771] Allow + binary expressions in env values

pipeline-model-api/src/main/java/org/jenkinsci/plugins/pipeline/modeldefinition/ast/ModelASTArgumentList.java, pipeline-model-definition/pom.xml, pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/parser/ModelParser.groovy, pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/validator/ModelValidatorImpl.groovy, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/BasicModelDefTest.java, pipeline-model-definition/src/test/resources/htmlPublisher.groovy, pom.xml
* [JENKINS-41456](https://issues.jenkins-ci.org/browse/JENKINS-41456)
* Description:
* Specifically, when we see that there's a sole required parameter, the only provided argument by the user is a map, at least one of those map keys doesn't have a corresponding parameter in the describable, and the sole required parameter's type is a describable itself, validate the argument map against that parameter type describable instead of against the parent describable. So for publishHTML, that means realizing `target` is an `HtmlPublisherTarget` and validating the map against that.
* n/a
* @rsandell 
* @bitwiseman
=> [FIXED JENKINS-41456] Properly validate publishHTML

pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/Utils.groovy, pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/model/Environment.groovy, pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/model/Options.groovy, pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/model/Root.groovy, pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/model/Stage.groovy, pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/parser/ModelParser.groovy, pipeline-model-definition/src/main/java/org/jenkinsci/plugins/pipeline/modeldefinition/model/CredentialsBindingHandler.java, pipeline-model-definition/src/main/resources/org/jenkinsci/plugins/pipeline/modeldefinition/ModelInterpreter.groovy, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/AbstractModelDefTest.java, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/DeclarativeLinterCommandTest.java, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/EnvironmentTest.java, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/ValidatorTest.java, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/WhenStageTest.java, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/steps/CredentialWrapperStepTest.java, pipeline-model-definition/src/test/resources/credentialsEnvCrossReference.groovy, pipeline-model-definition/src/test/resources/envDotCrossRef.groovy, pipeline-model-definition/src/test/resources/errors/scriptSecurityRejectionInEnvironment.groovy, pipeline-model-definition/src/test/resources/multilineEnvironment.groovy, pipeline-model-definition/src/test/resources/paramsInCreds.groovy, pipeline-model-definition/src/test/resources/paramsInEnvironment.groovy, pipeline-model-definition/src/test/resources/paramsInWhenExpression.groovy, pom.xml
* [JENKINS-43137](https://issues.jenkins-ci.org/browse/JENKINS-43137)
* [JENKINS-43143](https://issues.jenkins-ci.org/browse/JENKINS-43143)
* [JENKINS-43177](https://issues.jenkins-ci.org/browse/JENKINS-43177)
* [JENKINS-43013](https://issues.jenkins-ci.org/browse/JENKINS-43013)
* [JENKINS-42858](https://issues.jenkins-ci.org/browse/JENKINS-42858)
* Description:
* Environment variables with triple-quoted strings and ones with double-quotes inside them did not evaluate correctly. This fixes that.
* Make sure we process `params` into the environment, for normal environment variables and credentials.
* Use our own variable resolution logic rather than that from `EnvVars` to handle more complex expressions.
* The new round-robin variable resolution also deals with ordering …
=> [ENVIRONMENT OMNIBUS] Clean up environment issues stemming from 1.1 changes

pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/model/Environment.groovy, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/EnvironmentTest.java, pipeline-model-definition/src/test/resources/booleanParamAndEnv.groovy, pipeline-model-definition/src/test/resources/nullParamAndEnv.groovy, pom.xml
* [JENKINS-43486](https://issues.jenkins-ci.org/browse/JENKINS-43486)
* Description:
* non-`String` parameters (most notably `booleanParam`) were causing `ClassCastException`s when we tried to add them to the map for `environment` resolution, so do an explicit `toString()` on them.
* n/a
* @rsandell
=> [FIXED JENKINS-43486] Handle non-String parameters in env resolution

pipeline-model-definition/pom.xml, pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/Utils.groovy, pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/model/conditions/NotBuilt.groovy, pipeline-model-definition/src/main/resources/org/jenkinsci/plugins/pipeline/modeldefinition/ModelInterpreter.groovy, pipeline-model-definition/src/main/resources/org/jenkinsci/plugins/pipeline/modeldefinition/agent/impl/DockerPipelineFromDockerfileScript.groovy, pipeline-model-definition/src/main/resources/org/jenkinsci/plugins/pipeline/modeldefinition/agent/impl/DockerPipelineScript.groovy, pipeline-model-definition/src/main/resources/org/jenkinsci/plugins/pipeline/modeldefinition/model/conditions/Messages.properties, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/BasicModelDefTest.java, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/BuildConditionResponderTest.java, pom.xml
* [JENKINS-43339](https://issues.jenkins-ci.org/browse/JENKINS-43339)
* Description:
* We should be setting the build result to `FlowInterruptedException.getResult()` when we catch a `FlowInterruptedException`, since there's actually a relevant result there. Also added a `notBuilt` post status while I was here.
* n/a
* @rsandell 
=> [FIXED JENKINS-43339] Properly set result from FlowInterruptedException

pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/Utils.groovy, pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/model/Environment.groovy, pipeline-model-definition/src/main/resources/org/jenkinsci/plugins/pipeline/modeldefinition/ModelInterpreter.groovy, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/AgentTest.java, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/EnvironmentTest.java, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/steps/CredentialWrapperStepTest.java, pipeline-model-definition/src/test/resources/agentFromEnv.groovy, pipeline-model-definition/src/test/resources/credentialsDollarQuotes.groovy, pipeline-model-definition/src/test/resources/envDollarQuotes.groovy, pipeline-model-definition/src/test/resources/fileCredentialsInEnv.groovy
* [JENKINS-43872](https://issues.jenkins-ci.org/browse/JENKINS-43872)
* [JENKINS-43910](https://issues.jenkins-ci.org/browse/JENKINS-43910)
* Description:
* Hey look, another dumb `environment`/`script.evaluate` bug! I still should probably rewrite all this yet again, but for now...this "escapes" dollar signs in literal values and credentials values before `evaluate`ing non-literal env vars that may contain references to these literal/credential vars, and then "unescapes" the dollar signs back into place after all the pesky `evaluate`ing is done.
* Yet more circuitous processing to make sure we have credentials (including file credentials) processed before we try to process the environment, and definitely making agent get processed before either credentials or …
=> [FIXED JENKINS-43872, JENKINS-43910] Yet more env tweaks

pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/Utils.groovy, pipeline-model-definition/src/main/resources/org/jenkinsci/plugins/pipeline/modeldefinition/ModelInterpreter.groovy, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/OptionsTest.java, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/ParametersTest.java, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/TriggersTest.java, pipeline-model-definition/src/test/resources/propsTriggersParamsRemoved.groovy
* [JENKINS-44149](https://issues.jenkins-ci.org/browse/JENKINS-44149)
* Description:
* Previously we weren't calling the properties step if there were no properties (i.e., no job properties from options, no triggers, no parameters), but that left lurking properties when you removed all properties, triggers and parameters from the Jenkinsfile. So now let's check the job config to see if there were *already* defined properties before deciding not to call the properties step. Also make sure that PipelineTriggersJobProperty and ParametersDefinitionProperty are not empty, rather than just present.
* n/a
* @rsandell 
=> [FIXED JENKINS-44149] Properly clean up old props/triggers/params

pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/parser/Converter.groovy
* [JENKINS-43816](https://issues.jenkins-ci.org/browse/JENKINS-43816)
* Description:
* There's a small race condition that can occur where the `WorkflowRun` doesn't yet have a `FlowExecution` but we've been called anyway. In that scenario, calling `run.getExecutionPromise(...)` does the trick.
* n/a
=> [FIXED JENKINS-43816] Make sure we have a non-null execution.

pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/Utils.groovy, pipeline-model-definition/src/main/java/org/jenkinsci/plugins/pipeline/modeldefinition/SyntheticStageGraphListener.java, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/DurabilityTest.java, pom.xml
* [JENKINS-43055](https://issues.jenkins-ci.org/browse/JENKINS-43055)
* Description:
* Use the new `GraphListener` `ExtensionPoint` to have a single `SyntheticStageGraphListener` for all runs rather than one per run, with some logic for only firing on Declarative runs. Downstream of the now-merged https://github.com/jenkinsci/workflow-api-plugin/pull/38 and https://github.com/jenkinsci/workflow-cps-plugin/pull/137
* n/a
=> [FIXED JENKINS-43055] Change SyntheticStageGraphListener to an Extension

pipeline-model-definition/src/main/java/org/jenkinsci/plugins/pipeline/modeldefinition/endpoints/ModelConverterAction.java, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/endpoints/ModelConverterActionTest.java, pipeline-model-definition/src/test/resources/json/errors/invalidScriptContents.json
* Related to [JENKINS-44039](https://issues.jenkins-ci.org/browse/JENKINS-44039) but not exactly the same.
* Description:
* There are possible edge cases where the editor may not have done a validation of the JSON before saving it - so just to be safe, let's do a validation of the converted Jenkinsfile before returning it from `toJenkinsfile`.
* n/a
=> Validate converted Jenkinsfile before returning it.

pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/Utils.groovy, pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/model/Options.groovy, pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/model/Parameters.groovy, pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/model/Triggers.groovy, pipeline-model-definition/src/main/java/org/jenkinsci/plugins/pipeline/modeldefinition/actions/DeclarativeJobPropertyTrackerAction.java, pipeline-model-definition/src/main/java/org/jenkinsci/plugins/pipeline/modeldefinition/actions/JobPropertyTrackerAction.java, pipeline-model-definition/src/main/resources/org/jenkinsci/plugins/pipeline/modeldefinition/ModelInterpreter.groovy, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/OptionsTest.java, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/ParametersTest.java, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/TriggersTest.java
* [JENKINS-44621](https://issues.jenkins-ci.org/browse/JENKINS-44621)
* Description:
* Rather than actually using the properties(...) step directly, we
instead will now do this behind the scenes by interacting with the job
directly. We'll also record what job properties, triggers, and
parameters were defined in the Jenkinsfile for a given run, so that we
can refer back in the next build to see what existing job properties,
triggers, or parameters were defined through the Jenkinsfile vs
defined outside of the Jenkinsfile. This way, we can preserve the
defined-outside-Jenkinsfile properties et al.
* Note that this won't *quite* work right if the first run of a job
after upgrading removes triggers/properties/etc, because there is no
record for builds beforehand, so all …
=> [FIXED JENKINS-44621] Only remove job properties from Jenkinsfiles

pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/Utils.groovy, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/OptionsTest.java
* [JENKINS-44809](https://issues.jenkins-ci.org/browse/JENKINS-44809)
* Description:
* Two aspects - stop re-adding existing job properties defined outside of the Jenkinsfile, since they can't have changed, and remove all existing instances of a job property class defined inside the Jenkinsfile before we add the new instance, to avoid duplication.
* n/a
=> [FIXED JENKINS-44809] Clean up existing job property handling.

pipeline-model-extensions/src/main/java/org/jenkinsci/plugins/pipeline/modeldefinition/withscript/WithScriptDescribable.java, pipeline-model-extensions/src/main/java/org/jenkinsci/plugins/pipeline/modeldefinition/withscript/WithScriptScript.java
* Related to and a workaround for [JENKINS-44898](https://issues.jenkins-ci.org/browse/JENKINS-44898)
* Description:
* Note that this may be too insane and/or goofy to actually do. =)
* Relevant problem discussed at https://github.com/jenkinsci/kubernetes-plugin/pull/127.
* `PluginFirstClassLoader` doesn't have a functional `findResource` method, which for some reason I have yet to determine breaks `GroovyClassLoader.loadClass` when trying to fetch a groovy file from a `PluginFirstClassLoader` via the `UberClassLoader`. This works around that problem by catching the resulting `ClassNotFoundException` and trying to instead use `getResource` to get the URL for the groovy file and then parse it directly.
* Also whitelists the fields on `WithScriptScript` so they can be …
=> Work around PluginFirstClassLoader+GroovyClassLoader problem

pipeline-model-definition/src/main/java/org/jenkinsci/plugins/pipeline/modeldefinition/DeclarativeLinterCommand.java, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/DeclarativeLinterCommandTest.java
* [JENKINS-43071](https://issues.jenkins-ci.org/browse/JENKINS-43071)
* Description:
* `Permission.READ` meant that you actually needed admin rights to run the command. Which is dumb and wrong. So instead, go with a standard `Jenkins.READ`.
* n/a
=> [FIXED JENKINS-43071] Use Jenkins.READ perms for linter

pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/parser/ModelParser.groovy, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/AbstractModelDefTest.java, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/BasicModelDefTest.java, pipeline-model-definition/src/test/resources/objectMethodPipelineCall.groovy
* [JENKINS-45081](https://issues.jenkins-ci.org/browse/JENKINS-45081)
* Description:
* We were erroring out if you had a Scripted Pipeline with, say, a global variable `foo` with a method on it named `pipeline` that was being called like, say, `foo.pipeline { echo 'Hi there' }`. That...was not right. This fixes that. =)
* n/a
=> [FIXED JENKINS-45081] Don't error out for foo.pipeline { ... }

pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/parser/ModelParser.groovy, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/ValidatorTest.java, pipeline-model-definition/src/test/resources/errors/toolWithoutVersion.groovy
* [JENKINS-45098](https://issues.jenkins-ci.org/browse/JENKINS-45098)
* Description:
* We were still trying to do stuff with a variable after we determined it was null. That was dumb. Fixed.
* n/a
=> [FIXED JENKINS-45098] Properly validate tool-without-version

pipeline-model-definition/pom.xml
* n/a
* Description:
* Note that we *are* scanning both the compiled and CPS code in pipeline-model-definition. We're only failing for priority 1 warnings - priority 2 is a lot of "don't just catch Exception" or "empty if/else block" that I...frankly don't care about. And most of the priority 3 are unused imports, which would be nice to clean up, sure but don't actually *matter* in the grand scheme of things.
* Also, opened [INFRA-1267](https://issues.jenkins-ci.org/browse/INFRA-1267) to get the Warnings plugin (and Violations plugin) installed on ci.jenkins.io so we can actually report on failures in a useful way.
* n/a
=> Add CodeNarc!

Jenkinsfile, pom.xml
* [JENKINS-45546](https://issues.jenkins-ci.org/browse/JENKINS-45546)
* Description:
* Note that we're not using the Jacoco plugin - it's not installed on ci.jenkins.io in the first place, and I think the real value is probably going to come from the XML file anyway, which can be slurped in by other tools.
* n/a
=> [FIXED JENKINS-45546] Add jacoco code coverage to Declarative builds

pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/EnvironmentTest.java, pipeline-model-definition/src/test/resources/envVarContainsTEST.groovy
* [JENKINS-42082](https://issues.jenkins-ci.org/browse/JENKINS-42082)
* Description:
* Just verifying that this isn't an actual bug, at least as of now.
* n/a
=> [JENKINS-42082] Verify that you can put TEST in an env var name

pipeline-model-definition/pom.xml, pipeline-model-definition/src/main/java/org/jenkinsci/plugins/pipeline/modeldefinition/SyntheticStageGraphListener.java, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/BasicModelDefTest.java, pipeline-model-definition/src/test/resources/scmEnvVars.groovy, pipeline-model-extensions/src/main/resources/org/jenkinsci/plugins/pipeline/modeldefinition/agent/CheckoutScript.groovy, pom.xml
* [JENKINS-45198](https://issues.jenkins-ci.org/browse/JENKINS-45198)
* Description:
* This will not result in any change when run on core versions <2.60 (or with workflow-scm-step <2.6, git <3.3.1, etc), but will Just Work if you've got the right core/etc versions installed.
* BasicModelDefTest#scmEnvVars will start failing when we bump core etc dependencies for this plugin directly.
* Honestly not sure if there should be doc changes - @bitwiseman, thoughts?
=> [FIXED JENKINS-45198] When possible, add scm vars to environment

pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/Utils.groovy, pipeline-model-definition/src/main/resources/org/jenkinsci/plugins/pipeline/modeldefinition/ModelInterpreter.groovy, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/BasicModelDefTest.java, pipeline-model-definition/src/test/resources/skippedStagesInParallel.groovy
* n/a
* Description:
* I discovered that this won't actually mess with Blue Ocean visualization, since Blue Ocean already discards stages inside parallel branches but keeps the steps inside said stages. So...let's simplify things.
* n/a
=> Switch to actually calling stage('foo') for parallel stages

pipeline-model-api/src/main/java/org/jenkinsci/plugins/pipeline/modeldefinition/ast/ModelASTMethodCall.java, pipeline-model-api/src/main/java/org/jenkinsci/plugins/pipeline/modeldefinition/ast/ModelASTStep.java, pipeline-model-api/src/main/resources/org/jenkinsci/plugins/pipeline/modeldefinition/ast/Messages.properties
* [JENKINS-46309](https://issues.jenkins-ci.org/browse/JENKINS-46309)
* Description:
* Needed for backwards compatibility due to the editor calling ModelASTStep.getBlockedSteps() and the like, regrettably.
* n/a
=> [FIXED JENKINS-46309] Restore old blocked steps methods

pipeline-model-definition/src/main/resources/org/jenkinsci/plugins/pipeline/modeldefinition/agent/impl/DockerPipelineScript.groovy
* [JENKINS-46277](https://issues.jenkins-ci.org/browse/JENKINS-46277)
* Description:
* When we're at the top level, we want do do a pull of the docker image, but we want to do it within a synthetic stage. That's all well and good, but until now, the way this was done meant we weren't doing an image pull if we were at the stage level. That was dumb. Fixed!
* n/a
=> [FIXED JENKINS-46277] Do a pull for stage-level docker agent too

pipeline-model-api/src/main/java/org/jenkinsci/plugins/pipeline/modeldefinition/ast/ModelASTValue.java, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/BaseParserLoaderTest.java, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/validator/JSONValidationTest.java, pipeline-model-definition/src/test/resources/json/singleQuoteInMultiline.json
* [JENKINS-44039](https://issues.jenkins-ci.org/browse/JENKINS-44039)
* Description:
* We were only escaping `'''` in a multiline `script` block coming from JSON, when we should have been escaping `'`. Oops.
* n/a
=> [JENKINS-44039] Fix multiline script blocks containing single quotes

pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/parser/JSONParser.groovy, pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/parser/ModelParser.groovy, pipeline-model-definition/src/main/resources/org/jenkinsci/plugins/pipeline/modeldefinition/Messages.properties, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/ValidatorTest.java, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/validator/JSONValidationTest.java, pipeline-model-definition/src/test/resources/errors/bareDollarCurly.groovy, pipeline-model-definition/src/test/resources/json/errors/bareDollarCurly.json
* [JENKINS-46544](https://issues.jenkins-ci.org/browse/JENKINS-46544)
* Description:
* This isn't something we should allow, so now we check for it and do something about it. The problem isn't specific to the ticket's case of `environment`, so we're going to error out on any non-literal `ModelASTValue` that has a `toGroovy()` value starting with `${`.
* n/a
* @kshultzCB
=> [FIXED JENKINS-46544] Error on usage of unquoted ${...}

pipeline-model-definition/src/test/resources/environmentWithWorkspace.groovy, pipeline-model-definition/src/test/resources/nonLiteralEnvironment.groovy, pom.xml
* n/a
* Description:
* Newer durable task step plugin doesn't seem to know what to do with an escaped $ in an env var, so...bugger the lazy evaluation tricks I was doing, just do the simple thing.
* n/a
* @kshultzCB
=> Fix PCT issues caused by newer durable task step

pipeline-model-definition/pom.xml
When somebody hears about "Declarative Pipeline" they will logically go look for it in the plugins site or Update Center :smile:
=> Make the plugin name match user expectations

pipeline-model-api/src/main/java/org/jenkinsci/plugins/pipeline/modeldefinition/ast/ModelASTStage.java, pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/model/Stage.groovy, pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/parser/JSONParser.groovy, pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/parser/ModelParser.groovy, pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/parser/RuntimeASTTransformer.groovy, pipeline-model-definition/src/main/resources/org/jenkinsci/plugins/pipeline/modeldefinition/ModelInterpreter.groovy, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/AbstractModelDefTest.java, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/BasicModelDefTest.java, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/parser/ExecuteConvertedTest.java, pipeline-model-definition/src/test/resources/json/parallelStagesFailFast.json, pipeline-model-definition/src/test/resources/parallelStagesFailFast.groovy
* [JENKINS-47109](https://issues.jenkins-ci.org/browse/JENKINS-47109)
* Description:
* Allows setting `failFast` on a stage. Piggybacks on existing parallel branches JSON syntax, so roundtripping is built in. Woo.
* Might want to also reject if you use failFast in a non-parallel-parent stage, but it's pretty much harmless, so...eh.
* https://github.com/jenkins-infra/jenkins.io/pull/1156
* @kshultzCB
=> [FIXED JENKINS-47109] stage-level failFast w/ parallel stages

pipeline-model-definition/src/main/java/org/jenkinsci/plugins/pipeline/modeldefinition/parser/GroovyShellDecoratorImpl.java, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/BasicModelDefTest.java, pipeline-model-definition/src/test/resources/classInJenkinsfile.groovy
* [JENKINS-47193](https://issues.jenkins-ci.org/browse/JENKINS-47193)
* Description:
* For transformation purposes, we only are looking at the top level of the Jenkinsfile for pipeline blocks. So ignore classes defined in the Jenkinsfile as well, or we get errors due to things already having been transformed.
* n/a
=> [FIXED JENKINS-47193] Ignore other classes in Jenkinsfiles

pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/model/MappedClosure.groovy
* [JENKINS-47197](https://issues.jenkins-ci.org/browse/JENKINS-47197)
* Description:
* Groovy does something weird with `@Delegate` on a `Map` with Java 8 but targeting Java 7, resulting in a whole lot of additional methods created using `java.util.function.Function` and friends. That's annoying. To say the least.  Took me a while to find where that reference was being inserted, but yeah, it was `MappedClosure` and its `@Delegate`, so I got rid of `@Delegate` and now things are fine. Phew.
* n/a
=> [FIXED JENKINS-47197] Make sure we don't end up with Java 8 bits

pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/Utils.groovy, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/OptionsTest.java
* [JENKINS-46403](https://issues.jenkins-ci.org/browse/JENKINS-46403)
* Description:
* a Declarative Pipeline job can live-lock on startup when the (deprecated) Job.logRotator field has a value
* see [my explanation](https://issues.jenkins-ci.org/browse/JENKINS-46403?focusedCommentId=316154#comment-316154) in the JENKINS issue
* N/A
* ?
=> JENKINS-46403 - fix infinite loop running jobs with a logRotator

pipeline-model-definition/src/main/java/org/jenkinsci/plugins/pipeline/modeldefinition/actions/ExecutionModelAction.java
* [JENKINS-47421](https://issues.jenkins-ci.org/browse/JENKINS-47421)
* Description:
* This is a very minor issue in practice - the ExecutionModelAction isn't really used by anything but our own check for multiple executed pipeline blocks, which itself can't ever be the case on builds that started before Declarative 1.2 in the first place. Buuuuut it does result in some weird unreadable data messages in Jenkins, so let's play things very safe.
* n/a
=> [FIXED JENKINS-47421] Make sure we init stagesList in readResolve

pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/model/Tools.groovy, pipeline-model-definition/src/main/resources/org/jenkinsci/plugins/pipeline/modeldefinition/ModelInterpreter.groovy
* [JENKINS-46597](https://issues.jenkins-ci.org/browse/JENKINS-46597)
* Description:
* This was the last lurking bit of TreeMap, which almost certainly was causing the NotSerializableException. So let's get rid of it and switch to the ugly but functional list-of-pairs.
* n/a
* @kshultzCB
=> [FIXED JENKINS-46597] Eradicate TreeMap from runtime

pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/parser/ModelParser.groovy, pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/validator/ModelValidatorImpl.groovy, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/ValidatorTest.java, pipeline-model-definition/src/test/resources/errors/whenContainingNonCondition.groovy
* [JENKINS-47559](https://issues.jenkins-ci.org/browse/JENKINS-47559)
* Description:
* This has actually always been a potential problem but nothing in validation until 1.2 actually checked condition names via `.equals`. That'll end up null if you've got a non-method for the condition, so...tada. This fixes that by skipping the rest of validation in that case (since there's nothing more to validate!) and uses a better error message.
* n/a
=> [FIXED JENKINS-47559] Don't do full validation for non-conditions

pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/parser/RuntimeASTTransformer.groovy, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/EnvironmentTest.java, pipeline-model-definition/src/test/resources/environmentOverwriteReference.groovy
* [JENKINS-47600](https://issues.jenkins-ci.org/browse/JENKINS-47600)
* Description:
* If we try `VALUE = "${env.VALUE}"` or similar (with `env.` prefix), we're actually getting the getter call rather than the property directly, which leads to recursive hell. So switch that scenario to use the `getScriptPropOrParam` value instead, as we do for `VALUE = "${VALUE}"`.
* n/a
=> [FIXED JENKINS-47600] Avoid recursive hell for env.VALUE

pipeline-model-api/src/main/java/org/jenkinsci/plugins/pipeline/modeldefinition/DescriptorLookupCache.java, pipeline-model-definition/pom.xml, pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/Utils.groovy, pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/validator/ModelValidatorImpl.groovy, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/ValidatorTest.java, pipeline-model-definition/src/test/resources/errors/specificDescribableMatch.groovy, pom.xml
* [JENKINS-47781](https://issues.jenkins-ci.org/browse/JENKINS-47781)
* Description:
* The original problem here is that if you just look up describables by the "upstream" symbol, you'll get one from Copy Artifact before you get `ReverseBuildTrigger`. Which...ok. Except that our syntax checking treats kicks in for the one from Copy Artifact! So let's narrow our model lookups when appropriate.
* I don't *love* this solution - it could be smarter and have a better understanding of context. But this works for now, so I'll go with it.
* n/a
=> [FIXED JENKINS-47781] Narrow model lookups when appropriate

pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/validator/ModelValidatorImpl.groovy, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/ValidatorTest.java, pipeline-model-definition/src/test/resources/errors/optionValidatorContributor.groovy, pipeline-model-definition/src/test/resources/errors/postValidatorContributor.groovy, pipeline-model-extensions/src/main/java/org/jenkinsci/plugins/pipeline/modeldefinition/validator/DeclarativeValidatorContributor.java
* [JENKINS-47814](https://issues.jenkins-ci.org/browse/JENKINS-47814)
* Description:
* We were running contributor checks for all post containers twice. Let's only do that once per type.
* n/a
=> [FIXED JENKINS-47814] Don't run post validator contirbutors twice

pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/parser/ASTParserUtils.groovy, pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/parser/RuntimeASTTransformer.groovy, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/TriggersTest.java, pipeline-model-definition/src/test/resources/actualTriggerCorrectScope.groovy
* [JENKINS-47780](https://issues.jenkins-ci.org/browse/JENKINS-47781)
* Description:
* Actually fixing JENKINS-47780, because I only tested the validation before. D'oh. Still should probably get this more elegant, with auto-determination of context and valid describable types, but this works for now.
* n/a
=> [FIXED JENKINS-47780] Fix instantiation time scoping of describables

pipeline-model-definition/src/main/resources/org/jenkinsci/plugins/pipeline/modeldefinition/ModelInterpreter.groovy, pipeline-model-definition/src/main/resources/org/jenkinsci/plugins/pipeline/modeldefinition/when/impl/AllOfConditionalScript.groovy, pipeline-model-definition/src/main/resources/org/jenkinsci/plugins/pipeline/modeldefinition/when/impl/AnyOfConditionalScript.groovy, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/BasicModelDefTest.java, pipeline-model-definition/src/test/resources/parallelStagesShouldntTriggerNSE.groovy, pipeline-model-extensions/src/main/resources/org/jenkinsci/plugins/pipeline/modeldefinition/agent/CheckoutScript.groovy, pom.xml
* [JENKINS-46597](https://issues.jenkins-ci.org/browse/JENKINS-46597)
* Description:
* Specifically: the checkout step returns a TreeMap, so let's make sure we never have a variable assigned directly to that return value. Probably want to change checkout to return a HashMap in the
future, but we'll cross that bridge later. We can't actually test this normally because our core and `workflow-scm-step` versions are too old to have that functionality, but I did verify it by hand
* Also updated workflow-cps dependency so that we can be sure BooleanClosureWrapper serialization issues won't crop up, letting us write more things as .every or .any.
* n/a
=> [FIXED JENKINS-46597] Further handling of serializability issues

pipeline-model-definition/src/main/resources/org/jenkinsci/plugins/pipeline/modeldefinition/ModelInterpreter.groovy, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/PostStageTest.java, pipeline-model-definition/src/test/resources/postStage/parallelParentPostFailure.groovy
Fixes [JENKINS-47298](https://issues.jenkins-ci.org/browse/JENKINS-47928)
Avoid running `post` steps for parallel stage parents that did not throw errors.
=> [JENKINS-47928] Skip parallel stage post steps for previous errors

pipeline-model-api/src/main/java/org/jenkinsci/plugins/pipeline/modeldefinition/ast/ModelASTScriptBlock.java, pipeline-model-api/src/main/java/org/jenkinsci/plugins/pipeline/modeldefinition/ast/ModelASTWhenExpression.java, pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/validator/ModelValidatorImpl.groovy, pipeline-model-definition/src/main/resources/org/jenkinsci/plugins/pipeline/modeldefinition/Messages.properties, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/endpoints/ModelConverterActionTest.java, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/validator/JSONValidationTest.java, pipeline-model-definition/src/test/resources/json/errors/quoteRoundTripping.json
* [JENKINS-46854](https://issues.jenkins-ci.org/browse/JENKINS-46854)
* Description:
* This doesn't catch all possible script/expression errors that'll show up in full Groovy parsing and validation, but it'll catch errors like mismatched quotes in JSON form and report back their location and that compilation failed. Getting a more granular error would be too much text, so I opted for just the "hey, this wasn't valid Groovy syntax" approach.
* n/a
=> [FIXED JENKINS-46854] Do parsing pass on script/expression blocks in JSON validation

pipeline-model-definition/pom.xml, pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/model/conditions/Aborted.groovy, pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/model/conditions/Changed.groovy, pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/model/conditions/Failure.groovy, pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/model/conditions/NotBuilt.groovy, pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/model/conditions/Success.groovy, pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/model/conditions/Unstable.groovy, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/BuildConditionResponderTest.java, pipeline-model-definition/src/test/resources/contextResultOverridesRunResult.groovy, pipeline-model-definition/src/test/resources/junitResult.xml, pipeline-model-extensions/src/main/java/org/jenkinsci/plugins/pipeline/modeldefinition/model/BuildCondition.java, pom.xml
* [JENKINS-37663](https://issues.jenkins-ci.org/browse/JENKINS-37663)
* Description:
* The new junit step doesn't set the Run to UNSTABLE directly, it sets the context (and therefore the execution) result to UNSTABLE. We should be checking the execution result as well as the Run result.
* n/a
=> [FIXED JENKINS-37663] Check execution result in post as well

pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/Utils.groovy, pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/parser/RuntimeASTTransformer.groovy, pipeline-model-definition/src/main/java/org/jenkinsci/plugins/pipeline/modeldefinition/actions/DeclarativeJobAction.java, pipeline-model-definition/src/main/resources/org/jenkinsci/plugins/pipeline/modeldefinition/ModelInterpreter.groovy, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/BasicModelDefTest.java
* [JENKINS-46252](https://issues.jenkins-ci.org/browse/JENKINS-46252)
* Description:
* If we are in a Declarative run, mark the parent job as a Declarative job via DeclarativeJobAction, if it's not already present. Note that we never remove this - if a job was ever once Declarative, we still count it as such. Imperfect, but close enough.
* n/a
=> [FIXED JENKINS-46252] Mark Declarative jobs with DeclarativeJobAction

pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/parser/ASTParserUtils.groovy, pipeline-model-definition/src/main/java/org/jenkinsci/plugins/pipeline/modeldefinition/when/impl/ExpressionConditional.java, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/DurabilityTest.java, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/WhenStageTest.java, pipeline-model-definition/src/test/resources/whenExprDurableTask.groovy
* [JENKINS-48209](https://issues.jenkins-ci.org/browse/JENKINS-48209)
* Description:
* This shouldn't really matter, in truth - I believe we actually regenerate the whole Root object from scratch on resume, though I could be misremembering. Regardless, even having the when expression closure be transient, the durability test (with when expressions added) still works right.
* As to why we need to do this in the first place? Because something weird could be out there trying to some non-standard serialization of Describables. Ok, spoiler, there definitely is such a thing, and it does a straight XStream serialization of every Describable. But we use Describables as more than just UI config stuff - we use them for syntax validation and such for our internal extension …
=> [FIXED JENKINS-48209] Prevent serialization of when expression closure

pipeline-model-definition/src/main/java/org/jenkinsci/plugins/pipeline/modeldefinition/agent/impl/DockerPipelineFromDockerfile.java, pipeline-model-definition/src/main/resources/org/jenkinsci/plugins/pipeline/modeldefinition/agent/impl/DockerPipelineFromDockerfileScript.groovy
* [JENKINS-48229](https://issues.jenkins-ci.org/browse/JENKINS-48229)
* Description:
* I'm not sure how to test this - the issue occurs when the master's got different directory separators than the agent, which isn't something I can easily do in a unit test.
* n/a
=> [FIXED JENKINS-48229] Use the agent's dir separator for Dockerfile path

pipeline-model-definition/src/main/resources/org/jenkinsci/plugins/pipeline/modeldefinition/ModelInterpreter.groovy, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/PostStageTest.java, pipeline-model-definition/src/test/resources/postStage/postAfterParallel.groovy
* [JENKINS-48266](https://issues.jenkins-ci.org/browse/JENKINS-48266)
* Description:
* The JENKINS-47928 fix (in #217) was actually not right - it disabled calling post entirely for parallel parent stages if they weren't the source of an error themselves. That means they weren't called at all if there was no failure!
* The proper fix is to track whether a parallel parent stage has been skipped, and if so, skip post execution as well. Which is what's done here. Tada.
* n/a
=> [FIXED JENKINS-48266] Skip post for skipped parallel stages

pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/model/Options.groovy, pipeline-model-definition/src/main/java/org/jenkinsci/plugins/pipeline/modeldefinition/ModelStepLoader.java
* [JENKINS-48304](https://issues.jenkins-ci.org/browse/JENKINS-48304)
* Description:
* This may not be perfect, but it should hopefully eliminate the potential race condition of not all types being in the caches due to plugin loading order.
* n/a
=> [JENKINS-48304] Invalidate option type caches after extensions augmented

pom.xml
=> Seeing some docker-related hangs with 0.5-per-core - let's drop to 0.25-per-core

pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/Utils.groovy, pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/parser/RuntimeASTTransformer.groovy, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/parser/StepRuntimeTransformerContributorTest.java, pipeline-model-definition/src/test/resources/transformPost.groovy, pipeline-model-extensions/src/main/java/org/jenkinsci/plugins/pipeline/modeldefinition/parser/StepRuntimeTransformerContributor.java
* n/a
* Description:
* This'll end up getting used in `jx-pipelines-plugin` to avoid the same kind of closure->model transformation we got rid of when we switched to `RuntimeASTTransformer` here.
* Also unrestricted `Utils#createStepsBlock(Closure)` because that'll probably end up used in implementations of this.
* n/a
* @rsandell
=> Add an extension point for runtime transformation of steps.

pipeline-model-definition/src/main/resources/org/jenkinsci/plugins/pipeline/modeldefinition/Messages.properties
* [JENKINS-48758](https://issues.jenkins-ci.org/browse/JENKINS-48758)
* Description:
* Let's make sure it's clear what a string means in this context by, well, not saying string.
* n/a
=> [FIXED JENKINS-48758] Better message about allowed env values

pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/model/conditions/Changed.groovy, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/BuildConditionResponderTest.java, pipeline-model-definition/src/test/resources/postOnChangeUnstable.groovy
* [JENKINS-48752](https://issues.jenkins-ci.org/browse/JENKINS-48752)
* Description:
* The previous was...complicated. In some contexts, we do need to check the execution result, not just the run result, but that led to me writing some crappy code that meant that changed always triggered for any status but SUCCESS. Sigh. So instead, specifically get the worst status from the run and the execution and use that for comparison. Suddenly everything's simpler. =)
* n/a
=> [FIXED JENKINS-48752] Drastically simplify and fix changed calculation

Jenkinsfile, pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/parser/ModelParser.groovy, pipeline-model-definition/src/main/resources/org/jenkinsci/plugins/pipeline/modeldefinition/Messages.properties, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/BasicModelDefTest.java, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/ValidatorTest.java, pipeline-model-definition/src/test/resources/bigDecimalConverts.groovy, pipeline-model-definition/src/test/resources/errors/bigIntegerFailure.groovy
* [JENKINS-49070](https://issues.jenkins-ci.org/browse/JENKINS-49070)
* Description:
* Groovy parses `0.1` into a `BigDecimal`. So let's convert that to a `Double` instead in `ModelASTValue#value`. And also, just barf out if for some reason someone tries to use a `BigInteger` constant. Because no.
* n/a
=> [JENKINS-49070] Avoid serializing BigDecimal and BigInteger in the model

pipeline-model-definition/src/main/java/org/jenkinsci/plugins/pipeline/modeldefinition/when/impl/EqualsConditional.java, pipeline-model-definition/src/main/resources/org/jenkinsci/plugins/pipeline/modeldefinition/when/impl/EqualsConditional/help-actual.html, pipeline-model-definition/src/main/resources/org/jenkinsci/plugins/pipeline/modeldefinition/when/impl/EqualsConditional/help-expected.html, pipeline-model-definition/src/main/resources/org/jenkinsci/plugins/pipeline/modeldefinition/when/impl/EqualsConditional/help.html, pipeline-model-definition/src/main/resources/org/jenkinsci/plugins/pipeline/modeldefinition/when/impl/EqualsConditionalScript.groovy, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/AbstractModelDefTest.java, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/WhenStageTest.java, pipeline-model-definition/src/test/resources/when/whenEquals.groovy
* [JENKINS-49226](https://issues.jenkins-ci.org/browse/JENKINS-49226)
* Description:
* This adds a new `equals(expected:..., actual:...)` `when` condition. It basically does what you'd expect: checks if the two values are equal. This is intended to replace some of the most common usages of `when` `expression`s. I'm still trying to think of other common `expression` use cases that should have their own specific conditions...
* https://github.com/jenkins-infra/jenkins.io/pull/1425
=> [FIXED JENKINS-49226] Add equals condition.

pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/model/conditions/Aborted.groovy, pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/model/conditions/Always.groovy, pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/model/conditions/Changed.groovy, pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/model/conditions/Failure.groovy, pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/model/conditions/Fixed.groovy, pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/model/conditions/NotBuilt.groovy, pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/model/conditions/Regression.groovy, pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/model/conditions/Success.groovy, pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/model/conditions/Unstable.groovy, pipeline-model-definition/src/main/resources/org/jenkinsci/plugins/pipeline/modeldefinition/model/conditions/Messages.properties, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/BuildConditionResponderTest.java, pipeline-model-definition/src/test/resources/postOnChangeChanged.groovy, pipeline-model-definition/src/test/resources/postOnChangeFailed.groovy, pipeline-model-extensions/src/main/java/org/jenkinsci/plugins/pipeline/modeldefinition/model/BuildCondition.java
* [JENKINS-41060](https://issues.jenkins-ci.org/browse/JENKINS-41060)
* Description:
* Rather than trying to make `changed` take an additional parameter and break a bunch of parsing, let's make it simpler: here's two new `post` conditions: `fixed` and `regression`. 
* `fixed` runs if the previous build exists and wasn't `SUCCESS`, and the current build is `SUCCESS`.
* `regression` runs if the previous build exists and the current build's status is worse than the previous build - i.e., `currentResult.isWorseThan(previousResult)`.
* https://github.com/jenkins-infra/jenkins.io/pull/1444
=> [FIXED JENKINS-41060] Add new fixed/regression post conditions

Jenkinsfile, pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/model/Agent.groovy, pipeline-model-definition/src/main/java/org/jenkinsci/plugins/pipeline/modeldefinition/agent/AbstractDockerAgent.java, pipeline-model-definition/src/main/java/org/jenkinsci/plugins/pipeline/modeldefinition/options/impl/ContainerPerStage.java, pipeline-model-definition/src/main/resources/org/jenkinsci/plugins/pipeline/modeldefinition/ModelInterpreter.groovy, pipeline-model-definition/src/main/resources/org/jenkinsci/plugins/pipeline/modeldefinition/agent/impl/AbstractDockerPipelineScript.groovy, pipeline-model-definition/src/main/resources/org/jenkinsci/plugins/pipeline/modeldefinition/options/impl/ContainerPerStage/config.jelly, pipeline-model-definition/src/main/resources/org/jenkinsci/plugins/pipeline/modeldefinition/options/impl/ContainerPerStage/help.html, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/AgentTest.java, pipeline-model-definition/src/test/resources/agentDockerContainerPerStage.groovy, pipeline-model-definition/src/test/resources/agentDockerWithoutContainerPerStage.groovy
* [JENKINS-49558](https://issues.jenkins-ci.org/browse/JENKINS-49558)
* Description:
* If given with a top-level Docker or Dockerfile agent, the top-level
will magically switch to just a label agent, while each stage without
an explicit agent specified will end up using the root agent
definition with reuseNode enabled. The result will be that each stage
gets a new container. Tada.
* This could theoretically cause problems in resuming builds after
upgrade, but not likely, since we actually instantiate the
DeclarativeAgent instance just in time, not at the beginning of the
build. So the new field AbstractDockerAgent#containerPerStageRoot
should get populated correctly.
* https://github.com/jenkins-infra/jenkins.io/pull/1443
* Users/aliases to …
=> [FIXED JENKINS-49558] Add containerPerStage option

pipeline-model-definition/src/main/resources/org/jenkinsci/plugins/pipeline/modeldefinition/agent/impl/DockerPipelineScript.groovy
* https://issues.jenkins-ci.org/browse/JENKINS-47106
* Description:
* Support `alwaysPull` in the top level agent section, was broken by https://github.com/jenkinsci/pipeline-model-definition-plugin/commit/a367db7c2a727e5ea87381777b72b4c84b52f1a2#diff-f6e51fe76a49913b4ff00606e7d4d28aL43
* This is a bug fix.
* @abayer
=> [FIXED JENKINS-47106] Support alwaysPull in the top level agent section

pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/model/conditions/Failure.groovy, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/BuildConditionResponderTest.java
* [JENKINS-50652](https://issues.jenkins-ci.org/browse/JENKINS-50652)
* Description:
* It appears that an aborted durable task like sh results in `CpsFlowExecution#result` being `ABORTED`, but `WorkflowRun#result` being `FAILURE`, until the whole build actually finishes and the run gets updated accordingly. So the `failure` `post` condition shouldn't fire if `CpsFlowExecution#result` is `ABORTED`.
* n/a
=> [FIXED JENKINS-50652] Don't fire post failure for aborted durable task

pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/model/conditions/Cleanup.groovy, pipeline-model-definition/src/main/resources/org/jenkinsci/plugins/pipeline/modeldefinition/model/conditions/Messages.properties, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/BuildConditionResponderTest.java
* [JENKINS-41239](https://issues.jenkins-ci.org/browse/JENKINS-41239)
* Description:
* The new `cleanup` condition will always run regardless of build status, like `always`, but runs *after* all other `post` conditions have been evaluated, rather than before.
* I wanted to call this `finally` but that actually breaks Groovy parsing because `finally` is a reserved word. Dang. So for now, I'm calling it `cleanup`, but am open to suggestions.
* TODO
=> [FIXED JENKINS-41239] Add new cleanup post condition

pipeline-model-definition/src/main/java/org/jenkinsci/plugins/pipeline/modeldefinition/generator/DirectiveGenerator.java, pipeline-model-definition/src/main/resources/org/jenkinsci/plugins/pipeline/modeldefinition/generator/DirectiveGenerator/index.jelly
* [JENKINS-50964](https://issues.jenkins-ci.org/browse/JENKINS-50964)
* Description:
* The links to external doumentation for Pipeline Syntax are 404, because part of the path `book` is missing in their URLs. 
* Old, 404 version: `https://jenkins.io/doc/pipeline/syntax/`
* New, working version: `https://jenkins.io/doc/book/pipeline/syntax/`
* None necessary. Just links to existing documentation
* @abayer
=> JENKINS-50964: Fix the link to syntax documentation (was a 404)

pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/model/conditions/Success.groovy, pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/model/conditions/Unstable.groovy, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/BuildConditionResponderTest.java, pipeline-model-definition/src/test/resources/postFailureAfterSuccess.groovy, pipeline-model-definition/src/test/resources/postFailureAfterUnstable.groovy
* [JENKINS-50645](https://issues.jenkins-ci.org/browse/JENKINS-50645)
* Description:
* This way failure will still evaluate even if the actual failure doesn't occur until in the success or unstable blocks.
* Docs will need to reflect the changed order.
=> [FIXED JENKINS-50645] Move failure to run after other status checks

pipeline-model-definition/src/main/resources/org/jenkinsci/plugins/pipeline/modeldefinition/when/impl/BranchConditionalScript.groovy, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/BasicModelDefTest.java, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/WhenStageTest.java, pipeline-model-definition/src/test/resources/whenBranchNotMultibranch.groovy, pom.xml
* [JENKINS-50815](https://issues.jenkins-ci.org/browse/JENKINS-50815)
* Description:
* If we're not on multibranch (meaning BRANCH_NAME is null), fallback to GIT_LOCAL_BRANCH for when branch condition. We can theoretically add other SCMs here too if needed. We're using GIT_LOCAL_BRANCH because it most closely matches BRANCH_NAME - i.e., GIT_BRANCH includes the remote, GIT_LOCAL_BRANCH does not.
* n/a
* ...
=> [FIXED JENKINS-50815] Fallback to GIT_LOCAL_BRANCH for when branch

pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/ToolsTest.java, pipeline-model-definition/src/test/resources/buildPluginParentPOM.groovy
* n/a
* Description:
* This is breaking `ToolsTest#buildPluginParentPom`, so let's change that to use Maven 3.5.0 and we're all good.
* n/a
* ...
=> Plugin parent POM build now requires Maven 3.3.1 or newer

pipeline-model-api/src/main/java/org/jenkinsci/plugins/pipeline/modeldefinition/ast/ModelASTAgent.java, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/parser/ModelParserTest.java, pipeline-model-definition/src/test/resources/agentLabelEmptyString.groovy
* [JENKINS-43016](https://issues.jenkins-ci.org/browse/JENKINS-43016)
* Description:
* This'll make the editor happier - the label agent type does require an argument, but an empty string *is* a valid (but weird) use case. The editor, however, has no way of distinguishing between "you didn't specify a label" and "you specified an empty string for the label". There still should be work in the editor to figure out how to actually handle this situation, but this fix at least will unbreak existing Jenkinsfiles with empty string label agents being opened in the editor, by converting the JSON in that case to be `agent any`, which is functionally equivalent if no additional options are specified.
* However, if additional options are specified (such as `customWorkspace`), we …
=> [JENKINS-43016] Convert empty string label agent to agent any in JSON

pipeline-model-definition/src/main/resources/org/jenkinsci/plugins/pipeline/modeldefinition/ModelInterpreter.groovy, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/AbstractModelDefTest.java, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/BuildConditionResponderTest.java, pipeline-model-definition/src/test/resources/failureInPostBlock.groovy
* [JENKINS-44993](https://issues.jenkins-ci.org/browse/JENKINS-44993)
* Description:
* We only throw one exception for a failure in a stage, whether that failure is in the `steps` block or in a `post` condition's execution. Any subsequent exceptions get swallowed and never logged. This will change that, so that we'll start logging any exceptions encountered in executing `post` blocks even if the stage has already hit an error before getting to the `post` blocks.
* n/a
=> [FIXED JENKINS-44993] Don't swallow errors in post

pipeline-model-definition/src/main/resources/org/jenkinsci/plugins/pipeline/modeldefinition/ModelInterpreter.groovy, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/BuildConditionResponderTest.java, pipeline-model-definition/src/test/resources/sequentialPostNode.groovy
* [JENKINS-52084](https://issues.jenkins-ci.org/browse/JENKINS-52084)
* Description:
* We were executing post for a sequential stage parent the same way we do for parallel, but given that a sequential stage parent can define environment, agent, tools, etc, we should be running its post within those contexts.
* n/a
* ...
=> [FIXED JENKINS-52084] Execute sequential stage post in correct context

pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/Utils.groovy, pipeline-model-definition/src/main/resources/org/jenkinsci/plugins/pipeline/modeldefinition/ModelInterpreter.groovy, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/actions/RestartDeclarativePipelineActionTest.java, pipeline-model-definition/src/test/resources/restart/skippedParallelStagesMarkedNotExecuted.groovy
* [JENKINS-52261](https://issues.jenkins-ci.org/browse/JENKINS-52261)
* Description:
* We were marking the *start* node for stages skipped for restart with `NotExecutedNodeAction`, but not the end nodes, and it turns out, `StatusAndTiming#computeChunkStatus2` looks at the end node. So...whoops.
* n/a
* ...
=> [FIXED JENKINS-52261] Mark end nodes for skipped-for-restart stages properly

pipeline-model-definition/src/main/resources/org/jenkinsci/plugins/pipeline/modeldefinition/when/impl/IsRestartedRunConditional/config.jelly, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/generator/DirectiveGeneratorTest.java
* [JENKINS-51932](https://issues.jenkins-ci.org/browse/JENKINS-51932)
* Description:
* `isRestartedRun` wasn't showing up in the Directive Generator because it didn't have a `config.jelly`. So, here's a `config.jelly`.
* n/a
* ...
=> [FIXED JENKINS-51932] Add config.jelly for isRestartedRun

pipeline-model-definition/src/main/resources/org/jenkinsci/plugins/pipeline/modeldefinition/generator/DirectiveGenerator/symbol-hetero-list.jelly, pipeline-model-definition/src/main/resources/org/jenkinsci/plugins/pipeline/modeldefinition/generator/ToolsDirective/config.jelly
* [JENKINS-51872](https://issues.jenkins-ci.org/browse/JENKINS-51872?filter=15813)
* Description:
* SECURITY-624 resulted in the `<f:option>` body going through `h.xmlUnescape`...which is fine, except that when it's being specified inside a `l:renderOnDemand` block, the `h` variable isn't captured! Which results in `h.xmlUnescape('literally anything')` being null. So let's capture `h` when we call `l:renderOnDemand`, just to be safe.
* Note that this only is relevant for core 2.89.4 and >2.107, once SECURITY-624 was fixed.
* n/a
* ...
=> [FIXED JENKINS-51872] Fix tool dropdown

pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/Utils.groovy, pipeline-model-definition/src/main/resources/org/jenkinsci/plugins/pipeline/modeldefinition/ModelInterpreter.groovy, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/BuildConditionResponderTest.java, pipeline-model-definition/src/test/resources/postSuccessNoSuchMethodError.groovy
* [JENKINS-51383](https://issues.jenkins-ci.org/browse/JENKINS-51383)
* Description:
* Previously, we only caught and handled `Exception`s in `ModelInterpreter`. Which was fine in 99% of cases, but not `NoSuchMethodError` - that's an `Error`, not an `Exception`, and so it slipped through the cracks, resulting in `post` still firing for `success` even though the build would end up failed. So let's fix that.
* n/a
* ...
=> [FIXED JENKINS-51383] Handle Throwables, not just Exceptions

pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/Utils.groovy, pipeline-model-definition/src/main/java/org/jenkinsci/plugins/pipeline/modeldefinition/actions/DeclarativeJobPropertyTrackerAction.java, pipeline-model-definition/src/main/java/org/jenkinsci/plugins/pipeline/modeldefinition/options/impl/QuietPeriod.java, pipeline-model-definition/src/main/resources/org/jenkinsci/plugins/pipeline/modeldefinition/ModelInterpreter.groovy, pipeline-model-definition/src/main/resources/org/jenkinsci/plugins/pipeline/modeldefinition/options/impl/QuietPeriod/config.jelly, pipeline-model-definition/src/main/resources/org/jenkinsci/plugins/pipeline/modeldefinition/options/impl/QuietPeriod/help.html, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/OptionsTest.java, pipeline-model-definition/src/test/resources/quietPeriod.groovy
* [JENKINS-51227](https://issues.jenkins-ci.org/browse/JENKINS-51227)
* Description:
* This will let you set the quiet period for the job from the options block. As with job properties, triggers, and parameters, the quiet period will only be set to the default of 0 if the previous build actually had the QuietPeriod DeclarativeOption specified and the current build does not, so that UI-configured quiet periods don't get nuked.
* Will be needed.
* ...
=> [FIXED JENKINS-51227] Add quietPeriod DeclarativeOption

pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/model/AbstractBuildConditionResponder.groovy, pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/model/Root.groovy, pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/model/conditions/Aborted.groovy, pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/model/conditions/Always.groovy, pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/model/conditions/Changed.groovy, pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/model/conditions/Cleanup.groovy, pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/model/conditions/Failure.groovy, pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/model/conditions/Fixed.groovy, pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/model/conditions/NotBuilt.groovy, pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/model/conditions/Regression.groovy, pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/model/conditions/Success.groovy, pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/model/conditions/Unstable.groovy, pipeline-model-definition/src/main/resources/org/jenkinsci/plugins/pipeline/modeldefinition/ModelInterpreter.groovy, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/PostStageTest.java, pipeline-model-definition/src/test/resources/postStage/localAll.groovy, pipeline-model-definition/src/test/resources/postStage/postFailureSuccessInParallel.groovy, pipeline-model-extensions/src/main/java/org/jenkinsci/plugins/pipeline/modeldefinition/model/BuildCondition.java
* [JENKINS-52114](https://issues.jenkins-ci.org/browse/JENKINS-52114)
* Description:
* This changes `success` and `failure` `post` conditions for stages to look at whether there's an explicit error passed to them, rather than just looking at build status. This doesn't apply for top-level `post`, and has some special logic to not fire `success` if the build status is anything but `FAILURE`, and to not fire `failure` if the error is a result of aborting the build.
* There is one potentially problematic behavior change as a result - if you set `currentBuild.result` to `FAILURE` explicitly within a stage, `success` will still fire, and `failure` will not fire. There's no way to tell that this particular stage explicitly set `currentBuild.result` vs another stage running in …
=> [FIXED JENKINS-52114] Make success/failure use parallel stage result

pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/BuildConditionResponderTest.java, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/PostStageTest.java
These suckers are flaky for reasons I just don't understand - the
build result check will come up as failure, even though the build is
definitely aborted. I'm suspecting a timing issue, so am trying a sleep.
=> Trying to de-flake two tests

pipeline-model-definition/src/main/resources/org/jenkinsci/plugins/pipeline/modeldefinition/model/conditions/Messages.properties
Seen in "Declarative Directive Generator": ![grafik](https://user-images.githubusercontent.com/145182/48604179-3d168200-e979-11e8-8582-85e7178660c7.png)
1. Remove old (?) description for "Fixed" that accidentally was appended to "Unstable"
2. Since the two descriptions for "Fixed" vary, which one is actually the correct one? I guess/hope for the latter/current, as "Fixed" is hopefully also run when the previous build was e.g. "Aborted"?
- Run if the current build is "Success" and the previous build is "Failure" or "Unstable"
- Run if the previous build was not successful and the current build's status is "Success"
=> Fix description of "Unstable"

pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/model/conditions/Unsuccessful.groovy, pipeline-model-definition/src/main/resources/org/jenkinsci/plugins/pipeline/modeldefinition/model/conditions/Messages.properties, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/PostStageTest.java, pipeline-model-definition/src/test/resources/postStage/unsuccessful.groovy
* https://issues.jenkins-ci.org/browse/JENKINS-49997
* Description:
* Pipeline Declarative post unsuccessful block 
* https://github.com/jenkins-infra/jenkins.io/pull/1909
* N/A
=> JENKINS-49997 - Added Unsuccessful build condition for _post_

pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/model/Agent.groovy, pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/parser/ASTParserUtils.groovy, pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/parser/RuntimeASTTransformer.groovy, pipeline-model-definition/src/main/resources/org/jenkinsci/plugins/pipeline/modeldefinition/ModelInterpreter.groovy, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/AgentTest.java, pipeline-model-definition/src/test/resources/paramInAgentLabel.groovy
* [JENKINS-54919](https://issues.jenkins-ci.org/browse/JENKINS-54919)
* Description:
* This lets us reference environment variables (well, sorta - you can reference an environment variable defined at the parent level in a stage agent, but not an environment variable defined at the same level) and more immediately, this will allow referencing parameters that have just been added to the Pipeline in this build (well, as long as they have default values set).
* Basically, this makes Agent work more like StageConditionals by wrapping the map that defines the agent in a closure, and evaluating that closure at the time we actually need to use it, rather than baking the values in when we instantiate the runtime model.
* n/a
* …
=> [FIXED JENKINS-54919] Process agent configuration on the fly

pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/parser/ModelParser.groovy, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/ValidatorTest.java, pipeline-model-definition/src/test/resources/errors/multipleStepsSectionsInStage.groovy
* [JENKINS-51792](https://issues.jenkins-ci.org/browse/JENKINS-51792)
* Description:
* Given a malformed Pipeline, where there was more than one `steps` section inside of a `stage`, we were reporting a `Duplicate parallel branch name: "default"`. This was a bit confusing if the user's Pipeline had no branch named `default` in it at all. This change checks to make sure that the stage is empty before adding a `default` branch.
* No documentation changes should be necessary. This is just cleanup of some unnecessary error messages, which a user would only see if they had a mistake in their Pipeline anyway.
* N/A
=> [JENKINS-51792] Change ModelParser to error only once when there are multiple steps blocks

pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/model/conditions/Aborted.groovy, pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/model/conditions/Changed.groovy, pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/model/conditions/Failure.groovy, pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/model/conditions/Fixed.groovy, pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/model/conditions/NotBuilt.groovy, pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/model/conditions/Regression.groovy, pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/model/conditions/Success.groovy, pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/model/conditions/Unstable.groovy, pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/model/conditions/Unsuccessful.groovy, pipeline-model-definition/src/main/resources/org/jenkinsci/plugins/pipeline/modeldefinition/ModelInterpreter.groovy, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/AbstractModelDefTest.java, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/BasicModelDefTest.java, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/PostStageTest.java, pipeline-model-definition/src/test/resources/json/parallelStagesFailFast.json, pipeline-model-definition/src/test/resources/json/parallelStagesFailFastWithOption.json, pipeline-model-definition/src/test/resources/parallelStagesFailFast.groovy, pipeline-model-definition/src/test/resources/parallelStagesFailFastWithOption.groovy, pipeline-model-extensions/src/main/java/org/jenkinsci/plugins/pipeline/modeldefinition/model/BuildCondition.java
* [JENKINS-55459](https://issues.jenkins-ci.org/browse/JENKINS-55459)
* [JENKINS-55476](https://issues.jenkins-ci.org/browse/JENKINS-55476)
* Description:
* This changes the behavior of Declarative Pipeline to mimic Scripted Pipeline when a parallel stage configured to fail fast, fails fast. Previously, the overall build result would be set to ABORTED, whereas in Scripted Pipeline (and Declarative after this change), the overall build result would be set to FAILURE.
* This PR also fixes a bug causing the `unsuccessful` condition to always be executed in post blocks (JENKINS-55476).
* Open questions:
* How does this affect Blue Ocean/Stage View visualizations?
* Does removing the setting of build results in `ModelInterpreter.groovy` break post conditions in some cases? …
=> [JENKINS-55459] Make parallel stages that fail fast result in build failure

pom.xml
2.8 versions contain a broken JSON library that fails warnings-ng tests:
https://travis-ci.org/jenkinsci/warnings-ng-plugin/jobs/498444524#L7229
=> Bumb version of jackson-api-plugin to 2.9.8.

EXTENDING.md
#45 moved `ast-schema.json` from `pipeline-model-definition` to `pipeline-model-api`; however, the documentation was never updated to refer to the new location. This change updates the documentation to refer to the new location. I also fixed a few other typos I noticed in the documentation while I was there.
=> Fix errors in documentation

pipeline-model-definition/src/main/java/org/jenkinsci/plugins/pipeline/modeldefinition/agent/DeclarativeDockerUtils.java, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/AgentTest.java, pipeline-model-definition/src/test/resources/agentDockerWithRegistryNoCreds.groovy
* [JENKINS-56405](https://issues.jenkins-ci.org/browse/JENKINS-56405)
* Description:
* `registryUrl` should be used even if no credentials are supplied.
* n/a
* ...
=> [FIXED JENKINS-56405] Use Docker registry when only URL is given

pipeline-model-definition/src/main/resources/org/jenkinsci/plugins/pipeline/modeldefinition/ModelInterpreter.groovy, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/BuildConditionResponderTest.java, pipeline-model-definition/src/test/resources/resultIsFailureInPostAfterPostFailure.groovy, pipeline-model-definition/src/test/resources/resultIsFailureInPostAfterResultModified.groovy, pipeline-model-definition/src/test/resources/resultIsFailureInPostAfterStageFailure.groovy, pipeline-model-definition/src/test/resources/resultIsSuccessInPost.groovy, pipeline-model-definition/src/test/resources/resultStaysFailureWhenManuallySetInPost.groovy, pipeline-model-extensions/src/main/java/org/jenkinsci/plugins/pipeline/modeldefinition/model/BuildCondition.java
* See [JENKINS-56402](https://issues.jenkins-ci.org/browse/JENKINS-56402)
* Description:
* Set the build result in post conditions to the logical build result that will be used to determine which post blocks run. The result is unset after the post block so that JENKINS-55459 doesn't regress. If this seems too risky or doesn't seem like it would fix all of the reported issues, then we can go with #320 which just reverts #313 and then re-applies the patch for JENKINS-55475.
* N/A
* N/A
=> [JENKINS-56402] Set build result to the logical result in post conditions

pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/model/conditions/Aborted.groovy, pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/model/conditions/Failure.groovy, pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/model/conditions/NotBuilt.groovy, pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/model/conditions/Success.groovy, pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/model/conditions/Unstable.groovy, pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/model/conditions/Unsuccessful.groovy, pipeline-model-definition/src/main/resources/org/jenkinsci/plugins/pipeline/modeldefinition/agent/impl/DockerPipelineFromDockerfileScript.groovy, pipeline-model-definition/src/main/resources/org/jenkinsci/plugins/pipeline/modeldefinition/agent/impl/DockerPipelineScript.groovy, pipeline-model-definition/src/main/resources/org/jenkinsci/plugins/pipeline/modeldefinition/agent/impl/LabelScript.groovy, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/BasicModelDefTest.java, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/BuildConditionResponderTest.java, pipeline-model-definition/src/test/resources/json/parallelStagesFailFast.json, pipeline-model-definition/src/test/resources/json/parallelStagesFailFastWithOption.json, pipeline-model-definition/src/test/resources/parallelStagesFailFast.groovy, pipeline-model-definition/src/test/resources/parallelStagesFailFastWithAgent.groovy, pipeline-model-definition/src/test/resources/postFailureAfterManualResultChange.groovy
* [JENKINS-56544]()
* Description:
* Failure inside of a stage with an agent previously modified the build result. Now, the build result is left unmodified. 
* The trigger for the failure post condition has been modified so that it is not executed along with the aborted post condition in some cases.
* All post condition triggers for a specific build result now have identical implementations apart from the result they check for.
* TODO: Add a JSON file for the newly added test?
* TODO: Add some tests with Docker agents and failFast?
* TODO: Does the limitation mentioned under [the failure post condition in the documentation](https://jenkins.io/doc/book/pipeline/syntax/#post-conditions) still apply?
> Note that if you manually set …
=> [JENKINS-56544] Don't set build result when a stage with an agent fails

pipeline-model-definition/src/main/resources/org/jenkinsci/plugins/pipeline/modeldefinition/ModelInterpreter.groovy, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/OptionsTest.java, pipeline-model-definition/src/test/resources/parentStageRetryExecutesAllChildStages.groovy, pipeline-model-definition/src/test/resources/topLevelRetryExecutesAllStages.groovy
* [JENKINS-46354](https://issues.jenkins-ci.org/browse/JENKINS-46354)
* Description:
* When we retry the whole pipeline, we need to be sure that `firstError` is null before we try running everything again - otherwise, all stages get skipped due to an earlier failure.
* n/a
* ...
=> [FIXED JENKINS-46354] Make sure firstError is null on retries

pipeline-model-definition/src/main/resources/org/jenkinsci/plugins/pipeline/modeldefinition/agent/impl/DockerPipelineFromDockerfileScript.groovy
* https://issues.jenkins-ci.org/browse/JENKINS-56294
* Description:
* the dockerFingerprintFrom step uses an optional parameter commandLine which it parses for the build args to be passed to docker and in turn requires these arguments in order to correctly determine the from image for dockerfiles where the FROM directive contains a build argument in its expansion. This manifests as an IOException thrown by the dockerFingerprintFrom step when used within a declarative pipeline with a dockerfile whose FROM directive contains a build argument. I believe passing this commandLine argument should resolve that issue and restore parity with the docker workflow plugin.
* This is a pure bug fix and should not require any new user documentation
* …
=> [JENKINS-56294] pass commandLine to dockerFingerprintFrom for dockerfile agent

pipeline-model-definition/src/main/resources/org/jenkinsci/plugins/pipeline/modeldefinition/agent/impl/DockerPipelineFromDockerfileScript.groovy, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/AbstractModelDefTest.java, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/AgentTest.java, pipeline-model-definition/src/test/resources/agent/additionalDockerBuildArgsParallel.groovy
JENKINS issue(s):
- [JENKINS-57162](https://issues.jenkins-ci.org/browse/JENKINS-57162)
Description:
This extends the hash used to determine the image tag to include the
build args of the image since those generally result in a distinct image.
I had to do a bit of a hack in the tests to be able to use a fixed project name since that is part of the hash as well.
=> [JENKINS-57162] Dockerfile agent hash based on build args

pipeline-model-definition/src/main/resources/org/jenkinsci/plugins/pipeline/modeldefinition/ModelInterpreter.groovy
* N/A
* Description:
* Looks like this was unintentionally committed as part of https://github.com/jenkinsci/pipeline-model-definition-plugin/pull/330, noticed it while running some stuff locally.
* N/A
=> Remove call to System.err.println in ModelInterprer.groovy

pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/AgentTest.java, pipeline-model-definition/src/test/resources/agent/agentFromEnv.groovy, pipeline-model-definition/src/test/resources/agent/agentFromParentEnv.groovy
* JENKINS-43911 (ish) test only
* Description:
* JENKINS-43911 is still failing because the environment isn't preset when the agent label is evaluated. However, if the stage is inside another stage the label should be able to pick up the environment from the parent. This is not especially interesting but is worth having a test to cover it.
* n/a
* @abayer
=> Add test for label resolution from parent  env

pipeline-model-definition/pom.xml, pom.xml
* n/a
* Description:
* Looking that the build logs I noticed that gmaven was still running in some cases.  Also, noticed that gmavenplus runs on all the child projects, but is only needed by pipeline-model-definition.  Fixed both issues. 
* @abayer
=> Gmavenplus Part 2

pom.xml
Unlike gmaven, gmavenplus does not use providers.
=> gmavenplus uses the groovy version in the project

pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/Utils.groovy
* See [JENKINS-54322](https://issues.jenkins-ci.org/browse/JENKINS-54322)
* Description:
* Since this class can be used within the scripted pipeline, I'd like to expose the option to mark a staged as skipped programmatically.
* Not sure whether it might be interesting to expose the other `mark*` methods
* @abayer as you worked on https://github.com/jenkinsci/pipeline-model-definition-plugin/pull/210
=> [JENKINS-54322] enable markStageSkippedForConditional within the scripted

pipeline-model-definition/src/main/resources/org/jenkinsci/plugins/pipeline/modeldefinition/agent/impl/DockerPipelineFromDockerfileScript.groovy
See here for reference: https://github.com/jenkinsci/docker-workflow-plugin/pull/180
`dockerFingerprintFrom` has problems with multi-stage docker builds. The maintainers of the `docker-workflow-plugin` have decided to deprecate these steps, because the actual fingerprints are not anywhere in use.
=> Remove deprecated dockerFingerprintFrom

pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/Utils.groovy, pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/parser/ModelParser.groovy, pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/validator/ModelValidatorImpl.groovy, pipeline-model-definition/src/main/java/org/jenkinsci/plugins/pipeline/modeldefinition/actions/RestartDeclarativePipelineAction.java, pipeline-model-definition/src/main/java/org/jenkinsci/plugins/pipeline/modeldefinition/cli/DeclarativeLinterCommand.java, pipeline-model-definition/src/main/java/org/jenkinsci/plugins/pipeline/modeldefinition/endpoints/ModelConverterAction.java, pipeline-model-definition/src/main/java/org/jenkinsci/plugins/pipeline/modeldefinition/generator/DirectiveGenerator.java, pipeline-model-definition/src/main/java/org/jenkinsci/plugins/pipeline/modeldefinition/generator/StageDirective.java, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/actions/RestartDeclarativePipelineActionTest.java, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/cli/DeclarativeLinterCommandTest.java
While perusing the source tree, I noticed a number of deprecated methods:
- The documentation for [`ACL.impersonate(org.acegisecurity.Authentication, java.lang.Runnable)`](https://javadoc.jenkins-ci.org/hudson/security/ACL.html#impersonate-org.acegisecurity.Authentication-java.lang.Runnable-) states: "use try with resources and [`as(Authentication)`](https://javadoc.jenkins-ci.org/hudson/security/ACL.html#as-org.acegisecurity.Authentication-)".
- The documentation for [`User.get(java.lang.String)`](https://javadoc.jenkins-ci.org/hudson/model/User.html#get-java.lang.String-) states: "This method is deprecated, because it causes unexpected `User` creation by API usage code and causes performance degradation of used to retrieve users by ID. Use [`getById(java.lang.String, …
=> Remove usages of deprecated APIs

pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/parser/GroovyShellDecoratorImplTest.java
While looking at the test suite for this plugin, I noticed the `CpsFlowDefinition`s in the tests don't consistently use the script security sandbox. Using the script security sandbox results in a more realistic environment given that the script security sandbox should always be enabled in production.
In this change, I replaced any usages of the deprecated single-argument constructor for `CpsFlowDefinition` with usages of the non-deprecated two-argument constructor, passing in `true` as the second argument in order to always enable the script security sandbox.
=> Consistently use sandbox for CpsFlowDefinitions

pipeline-model-api/src/main/java/org/jenkinsci/plugins/pipeline/modeldefinition/ast/ModelASTWhen.java, pipeline-model-api/src/main/resources/ast-schema.json, pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/model/StageConditionals.groovy, pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/parser/JSONParser.groovy, pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/parser/ModelParser.groovy, pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/parser/RuntimeASTTransformer.groovy, pipeline-model-definition/src/main/java/org/jenkinsci/plugins/pipeline/modeldefinition/generator/WhenDirective.java, pipeline-model-definition/src/main/resources/org/jenkinsci/plugins/pipeline/modeldefinition/ModelInterpreter.groovy, pipeline-model-definition/src/main/resources/org/jenkinsci/plugins/pipeline/modeldefinition/generator/WhenDirective/config.jelly, pipeline-model-definition/src/main/resources/org/jenkinsci/plugins/pipeline/modeldefinition/generator/WhenDirective/help-beforeInput.html, pipeline-model-definition/src/main/resources/org/jenkinsci/plugins/pipeline/modeldefinition/generator/WhenDirective/help-beforeOptions.html, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/WhenStageTest.java, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/generator/DirectiveGeneratorTest.java, pipeline-model-definition/src/test/resources/when/whenBeforeOptionsFalse.groovy, pipeline-model-definition/src/test/resources/when/whenBeforeOptionsTrue.groovy
* https://issues.jenkins-ci.org/browse/JENKINS-51865
* Description:
* Introduces `beforeOptions` in `when` to be able to skip any (costly and pointless) `options` like `lock` (https://github.com/jenkinsci/lockable-resources-plugin).
* https://github.com/jenkins-infra/jenkins.io/pull/2569
* @abayer
* @bitwiseman
Some remarks:
- A single `before` attribute with possible values `'options'` XOR `'input'` XOR `'agent'` would be more concise but `beforeAgent` and `beforeInput` are already out there "in the wild".
- Strangely, `beforeInput` was missing from the generator (I fixed that).
- Also strangely, `beforeInput` and `beforeAgent` are _not_ evaluated when using `parallel` (but the new `beforeOptions` _is_ evaluated …
=> [JENKINS-51865] Introduce beforeOptions in 'when'

pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/parser/RuntimeASTTransformer.groovy, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/BasicModelDefTest.java, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/MatrixTest.java
* Description:
To get a 1.3.x release out without turning on matrix, I've set it to fail at runtime.
This is simpler than trying to tease apart what's been added in the last few months.
@dwnusbaum @olamy @kshultzCB @joseblas
=> Disable matrix execution

pipeline-model-api/pom.xml, pipeline-model-definition/pom.xml, pipeline-model-extensions/pom.xml, pipeline-stage-tags-metadata/pom.xml, pom.xml
* No Jira issue
* Description:
* Links to GitHub from the plugins.jenkins.io site are broken
* Documentation updated
=> Update plugins.jenkins.io GitHub links

pipeline-model-definition/src/main/java/org/jenkinsci/plugins/pipeline/modeldefinition/when/impl/ChangeSetConditional.java, pipeline-model-definition/src/main/java/org/jenkinsci/plugins/pipeline/modeldefinition/when/utils/Comparator.java, pipeline-model-definition/src/main/resources/org/jenkinsci/plugins/pipeline/modeldefinition/when/impl/ChangeSetConditional/config.jelly, pipeline-model-definition/src/main/resources/org/jenkinsci/plugins/pipeline/modeldefinition/when/impl/ChangeSetConditional/help-caseSensitive.html, pipeline-model-definition/src/main/resources/org/jenkinsci/plugins/pipeline/modeldefinition/when/impl/ChangeSetConditional/help-comparator.html, pipeline-model-definition/src/main/resources/org/jenkinsci/plugins/pipeline/modeldefinition/when/impl/ChangeSetConditional/help-pattern.html, pipeline-model-definition/src/main/resources/org/jenkinsci/plugins/pipeline/modeldefinition/when/impl/ChangeSetConditional/help.html, pipeline-model-definition/src/main/resources/org/jenkinsci/plugins/pipeline/modeldefinition/when/impl/ChangeSetConditionalScript.groovy, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/WhenStageMultibranchTest.java, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/WhenStageTest.java, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/when/utils/ComparatorTest.java, pipeline-model-definition/src/test/resources/json/when/conditions/changelog/changeset.json, pipeline-model-definition/src/test/resources/when/conditions/changelog/changeset.groovy
* [JENKINS-60217](https://issues.jenkins-ci.org/browse/JENKINS-60217)
* Description:
* Uses the `comparator` argument as already done with `tag` and `branch`.
* `help-*.html`.
* https://github.com/jenkins-infra/jenkins.io/pull/2664
- `caseSensitive` might not be relevant anymore as the `(?i)` with the `REGEXP` comparator should be enough. Do you think it might be worth to deprecate it? Or just remove it?
=> Support comparator pattern for the changeset directive

pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/Utils.groovy, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/OptionsTest.java, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/ParametersTest.java, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/TriggersTest.java, pipeline-model-definition/src/test/resources/simplePipelineWithTestTrigger.groovy
* https://issues.jenkins-ci.org/browse/JENKINS-49500
* https://issues.jenkins-ci.org/browse/JENKINS-44809
* Description:
I've found a problem, that concurrent execution of the same pipeline produces a bunch of problems:
- Jenkins saves job configuration each run, even if the configuration isn't changed. Save to the same file is blocking operation, so all parallel runs stuck for wait IO. In case of installed Job Config History Plugin IO calls multiplied 2 times due to reordering of some JobProperties during marshaling. Also, rewriting all job properties stops not changed triggers (JENKINS-49500)
- Updating of WorkflowJob object in method `Utils.updateJobProperties()` isn't thread-safe, so it produces undefined behavior. It can't be a root cause of JENKINS-44809. 
- One …
=> Update only changed Job Properties

pipeline-model-definition/pom.xml, pom.xml
* N/A
* Description:
* Previously, workflow-scm-step releases included a `-tests` jar with some utilities. Long ago, in https://github.com/jenkinsci/workflow-scm-step-plugin/pull/15 those utilities were moved to other plugins, and in https://github.com/jenkinsci/workflow-scm-step-plugin/pull/17, workflow-scm-step was changed to no longer publish a tests jar. pipeline-model-definition still depends on an older version of workflow-scm-step where the `-tests` jar was present, which causes a compilation failure in the PCT when run against newer versions of workflow-scm-step. Since the utilities were moved to other plugins that are already in use here, I think it should be safe to just remove the dependency, but if the CI build fails I might need to tweak some test imports. …
=> Remove dependency on obsolete tests jar for workflow-scm-step

pipeline-model-api/pom.xml, pipeline-model-definition/pom.xml, pipeline-model-extensions/pom.xml, pipeline-stage-tags-metadata/pom.xml
* N/A
* Description:
* https://github.com/jenkinsci/pipeline-model-definition-plugin/pull/358 only changed the URL for the parent, not each plugin, so pages like https://plugins.jenkins.io/pipeline-model-definition and https://plugins.jenkins.io/pipeline-model-extensions are still sourcing their content from the wiki instead of GitHub (note the lack of badges on those pages, even though the badges are present here on GitHub). 
* N/A
* N/A
=> Change urls for each plugin to point to GitHub

pipeline-model-api/src/main/java/org/jenkinsci/plugins/pipeline/modeldefinition/ast/ModelASTPipelineDef.java, pipeline-model-api/src/main/java/org/jenkinsci/plugins/pipeline/modeldefinition/validator/AbstractModelValidator.java, pipeline-model-api/src/main/java/org/jenkinsci/plugins/pipeline/modeldefinition/validator/ModelValidator.java, pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/parser/RuntimeASTTransformer.groovy, pipeline-model-definition/src/main/java/org/jenkinsci/plugins/pipeline/modeldefinition/actions/ExecutionModelAction.java, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/BasicModelDefTest.java, pipeline-model-definition/src/test/resources/executionModelAction.groovy
* [JENKINS-60531](https://issues.jenkins-ci.org/browse/JENKINS-60531)
* Description:
* Developer-only change. Right now, there are two issues that make it difficult to use the Declarative AST from another plugin to statically analyze a Declarative Pipeline:
* `ExecutionModelAction` does not contain the full Pipeline, only the stages, so there is no way to analyze the top-level agent, options, environment, etc. My proposed fix for this issue is to make `ExecutionModelAction` store the full Pipeline going forward, along with implementing a bit of compatibility code for old builds where only the stages were stored.
* I think the best way to walk/analyze the AST of a Declarative Pipeline is to use `ModelValidator` from `pipeline-model-api`, however, that interface recently …
=> Store full pipeline definition in ExecutionModelAction and add abstract ModelValidator class

pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/ProvisioningTimeoutModelDefTest.java, pipeline-model-definition/src/test/resources/options/stageLevelAgentFailsWithTimeout.groovy, pipeline-model-definition/src/test/resources/options/topLevelAgentSuccessWithTimeout.groovy
This PR is for amending [#376](https://github.com/jenkinsci/pipeline-model-definition-plugin/pull/376)
regarding https://issues.jenkins-ci.org/browse/JENKINS-60994
Documentation changes:
jenkins-infra/jenkins.io#2853
=> JENKINS-60994 Fixing timeout tests

README.md
The minimum Jenkins version was out of date, and the right version is automatically added to the plugin site, here is a screenshot:
Similarly, the security warnings are automatically added to the sidebar on the right-hand side of the page:
=> Remove content that is dynamically generated on plugins.jenkins.io

pipeline-model-definition/src/main/resources/org/jenkinsci/plugins/pipeline/modeldefinition/ModelInterpreter.groovy
[JENKINS-61007](https://issues.jenkins-ci.org/browse/JENKINS-61007)
Apparently the annotation introduced in #356 cannot be resolved in this context. Groovy may have different rules for lax resolution of annotations than Java. I do not know how to reproduce inside a functional test due to the different class loading environment. Anyway, I can confirm that this patch fixes the problem for me locally.
=> [JENKINS-61007] Do not use @SuppressFBWarnings in src/main/resources/**/*.groovy

pipeline-model-definition/pom.xml
As mentioned in https://github.com/jenkinsci/kubernetes-plugin/pull/735, follows up #373 to make this dependency optional so `docker-workflow` could actually be disabled. (Tested that scenario via `hpi:run`.)
=> [JENKINS-58732] Make docker-workflow dep optional

pipeline-model-declarative-agent/README.md, pipeline-model-definition/pom.xml
... and provide simple readme that can be displayed on plugins.jenkins.io for the deprecated plugin (AFAIK it doesn't have its own repo).
Note that <0.5% of declarative-agent users are not using the tombstone release and out of those  most are on old cores: https://stats.jenkins.io/pluginversions/pipeline-model-declarative-agent.html
=> Remove dependency on pipeline-model-declarative-agent

pipeline-model-definition/src/main/resources/org/jenkinsci/plugins/pipeline/modeldefinition/Messages.properties
Just saw this message in an error and I couldn't figure it out, and searched for the error message and arrived at this code, I think clarifying this error message to include human language describing the change needed would be a better developer experience. 
>${param.slack_channel} cannot be used as a value directly. Did you mean "${param.slack_channel}"
=> Clarify "cannot be used as a value directly" to mean "add quotes"

pom.xml
Introduces Jenkins BOM in order to simplify management of dependencies.
Also
* Replaced multiple occurrences of version by maven properties
* Cleaned up Hamcrest references (only `org.hamcrest:hamcrest` should be referenced directly, others are deprecated)
=> Use Jenkins BOM to manage dependencies

pipeline-model-definition/src/main/resources/org/jenkinsci/plugins/pipeline/modeldefinition/ModelInterpreter.groovy
* [JENKINS-62988](https://issues.jenkins-ci.org/browse/JENKINS-62988)
* Description:
* The classes `ModelInterpreter.groovy` has available to it at runtime depend on the versions of Jenkins and `workflow-cps` (among other plugins) being used, so we should minimize usage of any transitive dependencies that may be removed or modified, particularly annotations.
* TODO:
* N/A
* N/A
=> [JENKINS-62988] Do not use 3rd-party dependencies in ModelInterpreter.groovy

pipeline-model-api/pom.xml
* See [JENKINS-63123](https://issues.jenkins-ci.org/browse/JENKINS-63123)
* Description:
* Apparently, in some cases downstream plugins were getting upper bounds issues because `pipeline-model-api`  depends on `json-schema-validator` 2.0.4 which depends on `json-schema-core` 1.0.4 which depends on `guava` 13.0.1, which is newer than the version of Guava bundled in Jenkins core (11.0.1). From what I can tell 11.0.1 is what `pipeline-model-api` itself it using, and it is not bundling a newer version or anything, so I think this only affects downstream plugins, and even then maybe only under specific circumstances.
* N/A
* @oleg-nenashev If you have an easy way to check whether this fixes the issue you were seeing, could …
=> [JENKINS-63123] Exclude transitive guava dependency from json-schema-validator

Jenkinsfile, pipeline-model-definition/pom.xml, pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/Utils.groovy, pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/validator/ModelValidatorImpl.groovy, pipeline-model-definition/src/main/java/org/jenkinsci/plugins/pipeline/modeldefinition/generator/ParametersDirective.java, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/ParametersTest.java, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/steps/CredentialWrapperStepTest.java, pipeline-model-definition/src/test/resources/passwordParameters.groovy
See [JENKINS-63499](https://issues.jenkins-ci.org/browse/JENKINS-63499).
https://github.com/jenkinsci/jenkins/pull/4630 modified the `@DataBoundConstructor` for `PasswordParameterDefinition` in a way that broke backwards compatibility for structs-based data binding. `PasswordParameterDefinition` is used by Declarative for the parameters directive, so this PR adds a special case so that old Pipelines that configure `password` parameters as described in [the documentation](https://www.jenkins.io/doc/book/pipeline/syntax/#parameters) continue to work.
The directive generator is also affected by the original core change, here is the output when you try to generate a `parameters` directive with a password parameter:
```
parameters {
password defaultValueAsSecret: <object of type …
```
=> [JENKINS-63499] Make password parameters work with the parameters directive in Jenkins 2.236+

pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/parser/ModelParser.groovy
**JENKINS issue(s):  n/a**
Hey @bitwiseman, opening a Draft PR to start the conversation around supporting Declarative Syntax from a pipeline template in the Jenkins Templating Engine.  
This PR allows users of the [Jenkins Templating Engine](https://github.com/jenkinsci/templating-engine-plugin) to write pipeline templates using the Declarative Syntax. 
<details><summary><strong>Scoping this change to just JTE</strong></summary>
<p>
I was expecting to have to make a change to Declarative's `GroovyShellDecoratorImpl` to include a logical check for whether or not the `FlowDefinition` that led to the `CpsFlowExecution ` came from the Jenkins Templating Engine (by being a subclass of `TemplateFlowDefinition`).
This ended up not being necessary, since ultimately a pipeline template _is just a …
=> Support Declarative Pipeline Syntax Within Jenkins Templating Engine 

pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/parser/ModelParser.groovy, pipeline-model-definition/src/main/java/org/jenkinsci/plugins/pipeline/modeldefinition/parser/AlwaysTrueValidator.java, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/parser/ModelParserExternalTest.java
* n/a
* Description:
* I'm working on tooling for converting Jenkinsfiles to JSON outside of a Jenkins instance, and there are a number of things that break as things stand now. This fixes those, by allowing for providing a `ModelValidator` implementation and a `DescriptorLookupCache` instance to `ModelParser`, and uses a fallback for the zero-arg agent model map if run outside of Jenkins.
* n/a - this isn't user-facing.
* @bitwiseman
=> Allow ModelParser to be run outside of a Jenkins instance

pipeline-model-api/src/main/java/org/jenkinsci/plugins/pipeline/modeldefinition/ast/InvisibleGlobalWhenCondition.java, pipeline-model-api/src/main/java/org/jenkinsci/plugins/pipeline/modeldefinition/ast/InvisibleWhen.java, pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/Utils.groovy, pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/parser/ASTParserUtils.groovy, pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/parser/Converter.groovy, pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/parser/ModelParser.groovy, pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/parser/RuntimeASTTransformer.groovy, pipeline-model-definition/src/main/java/org/jenkinsci/plugins/pipeline/modeldefinition/generator/ParametersDirective.java, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/parser/ASTParserUtilsTest.java, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/parser/RuntimeASTTransformerTest.java, pipeline-model-definition/src/test/resources/org/jenkinsci/plugins/pipeline/modeldefinition/parser/GlobalStageNameTestConditionalScript.groovy, pipeline-model-definition/src/test/resources/org/jenkinsci/plugins/pipeline/modeldefinition/parser/GlobalStepCountTestConditionalScript.groovy, pipeline-model-definition/src/test/resources/org/jenkinsci/plugins/pipeline/modeldefinition/parser/GlobalTestConditionalScript.groovy, pipeline-model-definition/src/test/resources/prettyPrintTransformedOutput.txt, pipeline-model-definition/src/test/resources/twoStages.groovy, pipeline-model-extensions/src/main/java/org/jenkinsci/plugins/pipeline/modeldefinition/CommonUtils.java, pipeline-model-extensions/src/main/java/org/jenkinsci/plugins/pipeline/modeldefinition/when/DeclarativeStageConditionalDescriptor.java, pipeline-model-extensions/src/main/java/org/jenkinsci/plugins/pipeline/modeldefinition/when/GlobalStageConditional.java, pipeline-model-extensions/src/main/java/org/jenkinsci/plugins/pipeline/modeldefinition/when/GlobalStageConditionalDescriptor.java, pipeline-model-extensions/src/main/java/org/jenkinsci/plugins/pipeline/modeldefinition/when/GlobalStageConditionalScript.java
* [JENKINS-64508](https://issues.jenkins.io/browse/JENKINS-64508)
* Description:
* Adds a new extension point and parse/transformation logic for globally defined when conditions that will be evaluated for every stage run on the controller when configured.
* Also get the debug pretty printing for post-AST transformation to actually do something kinda useful again.
* n/a - no user-facing changes
* ...
=> [JENKINS-64508] Add extension point for globally defined when conditions

pipeline-model-definition/pom.xml, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/AbstractModelDefTest.java
Just the first commit from #391; whatever the purpose of the subsequent commits, they may have been made obsolete by changes in `master` since then.
Follows up #373 & #383.
Admins using `agent docker` / `agent dockerfile` should have updated to at least https://github.com/jenkinsci/docker-workflow-plugin/releases/tag/docker-workflow-1.22 first.
=> [JENKINS-58732] Remove docker-workflow dependency (refiled)

pipeline-model-api/pom.xml, pipeline-model-api/src/main/java/org/jenkinsci/plugins/pipeline/modeldefinition/DescriptorLookupCache.java, pipeline-model-api/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/DescriptorLookupCacheTest.java, pipeline-model-definition/src/test/resources/json/steps/metaStepSyntax.json, pipeline-model-definition/src/test/resources/steps/metaStepSyntax.groovy
* n/a
* Description:
* We always prefer `StepDescriptor`s to other `Descriptor`s, but can still hit symbol collisions and end up with the wrong `Descriptor` for a metastep symbol. It's not consistent across all cases - I think it has something to do with which `Symbol`-annotated class gets checked first in the symbol lookup, but I really can't be sure. So when we're looking up functions, we should prefer first `StepDescriptor`s, then `Descriptor`s for a metastep, and finally any ol' arbitrary `Descriptor`.
* Note that I had trouble getting a full end-to-end test to fail correctly - something about the `Symbol`-annotated class check ordering or, worse, some caching of lookups that actually do what they're supposed to do before we even get there. I really can't tell. So …
=> In validation and elsewhere, prefer metasteps to other non-step descriptors

pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/parser/RuntimeASTTransformer.groovy, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/AbstractModelDefTest.java, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/BasicModelDefTest.java
* [JENKINS-34987](https://issues.jenkins-ci.org/browse/JENKINS-37984)
Automatically splitting the pipeline script into multiple smaller parts makes it less likely
for the resulting compiled class throw "Method code too large!" or "Class too large"
exceptions during the class file generation phase of compilation.
Script splitting has two different strategies: method-grouped and closure-only. Closure-only is less effective but method-grouped splitting is not compatible with some groovy structures.  In particular locally declared variables, such as such as `def a = 1`, are incompatible with the more effective method-grouped script splitting.
Before this change, any statements outside the pipeline directive would cause the plugin to switch to using the less effective closure-only script …
=> [JENKINS-34987] - Allow better script splitting in more scenarios

pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/parser/RuntimeASTTransformer.groovy
* See https://github.com/jenkinsci/pipeline-model-definition-plugin/pull/405#issuecomment-771677208.
* Description:
* #405 introduced an unchecked cast to `ExpressionStatement` when `SCRIPT_SPLITTING_TRANSFORMATION` was active which caused failures in Pipelines that had other types of top-level statements. This PR moves that cast behind an `instanceof` check.
* Side note: Do we not have SpotBugs here? Or does it not work with the code in `src/main/groovy` or something? I think that normally it would catch this kind of issue.
* N/A
* @eplodn
=> Check statement type before casting to ExpressionStatement

pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/parser/RuntimeASTTransformer.groovy, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/BasicModelDefTest.java, pipeline-model-definition/src/test/resources/basic/stages100WithOutsideVarAndFunc.groovy
JENKINS-34987 , #405, #412
Per suggestion from @dwnusbaum, I've improved the output for variable declarations to only include the name.  The space was a bit more complex that just a stream statement since `getVariableExpression()` will throw for some types of declarations.
* ...
=> [JENKINS-34987] Improved output for local variable declarations with script splitting

pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/parser/RuntimeASTTransformer.groovy
* n/a
* Description:
* Pull request #405 introduced a new environment variable `SCRIPT_SPLITTING_ALLOW_LOCAL_VARIABLES`. However, there is a typo in the variable, resulting in not being able to set this variable. This leaves the variable to the default.
* No documentation changes needed, it's just a typo.
* @bitwiseman
=> Remove space from environment variable

pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/parser/RuntimeASTTransformer.groovy, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/AbstractModelDefTest.java, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/BasicModelDefTest.java, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/EnvironmentTest.java, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/LibrariesTest.java, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/MatrixTest.java, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/OptionsTest.java, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/ParametersTest.java, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/PostStageTest.java, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/StageInputTest.java, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/ToolsTest.java, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/TriggersTest.java, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/WhenStageTest.java, pipeline-model-definition/src/test/resources/matrix/matrixStageDirectivesOutsideVarAndFunc.groovy, pom.xml
* [JENKINS-64846](https://issues.jenkins.io/browse/JENKINS-64846)
* Description:
* We have script splitting turned on by default in most tests.  The assumption as was that script splitting being turned on would break things, not make them work unexpectedly. Turns out that is not always the case.  With the change to script splitting from 1.8.0, if script splitting is turned off local declared variables do not get retained appropriately in matrix.
* @abayer
=> [JENKINS-64846] Fix use of local declared variables inside matrix

pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/generator/DirectiveGeneratorTest.java
* N/A
* Description:
* Fixed PCT failures see jenkinsci/bom#511
* No docs needed
* @bitwiseman
=> Fix PCT failures past 2.281

pipeline-model-definition/src/main/resources/lib/pipelinemodeldefinition/blockWrapper.jelly, pipeline-model-definition/src/main/resources/org/jenkinsci/plugins/pipeline/modeldefinition/generator/EnvironmentDirective/config.jelly, pipeline-model-definition/src/main/resources/org/jenkinsci/plugins/pipeline/modeldefinition/generator/LibrariesDirective/config.jelly, pipeline-model-definition/src/main/resources/org/jenkinsci/plugins/pipeline/modeldefinition/generator/ToolsDirective/config.jelly
The declarative directive generators had some issues with it after the
migration from tables to divs, particularly in the tools section. Make
the necessary changes for compatibility with 2.264 and higher.
* n/a
* not needed as bugfix only
* @bitwiseman
=> Fix tables-to-divs issues in directive generator

pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/parser/RuntimeASTTransformer.groovy
SCRIPT_SPLITTING_TRANSFORMATION should be JENKINS-37984, NOT JENKINS-34987.
* https://issues.jenkins.io/browse/JENKINS-37984
* https://issues.jenkins.io/browse/JENKINS-34987
* Description:
* There was a typo in the issue id.
* The Jenkins error message references the wrong issue id, which makes the error message misleading.
* @jglick
=> Fix typo in issue id

pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/AgentTest.java
See https://github.com/jenkinsci/jenkins/pull/5450#issuecomment-888512618 and following discussion. Whether the new core behavior is a genuine regression is hard to pin down because I am not exactly sure how this test worked before—`Slave.setNumExecutors` updates a field but has no other effect itself.
=> Call `Jenkins.setNodes` to adapt to core change in 2.302

pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/model/Agent.groovy, pipeline-model-definition/src/main/resources/org/jenkinsci/plugins/pipeline/modeldefinition/ModelInterpreter.groovy
Formerly this would just throw a NPE, observed in https://github.com/jenkinsci/bom/pull/587.
This patch does _not_ solve the actual bug, which is that https://github.com/jenkinsci/pipeline-model-definition-plugin/blob/f06ef76fb39148bf1ee166f39e2ae191fee81955/pipeline-model-definition/src/main/java/org/jenkinsci/plugins/pipeline/modeldefinition/agent/impl/None.java#L43 is not found, due to https://github.com/jenkinsci/lib-annotation-indexer/pull/10 via https://github.com/jenkinsci/plugin-pom/pull/424.
#442 did not reproduce the issue because then we are compiling `pipeline-model-definition` with the same version of core as we are running tests with. You need to run in PCT to see the problem.
=> [JENKINS-66247] Properly report an unrecognized `agent` type

pipeline-model-definition/src/test/resources/errors/globalLibraryNonStepBody.groovy, pipeline-model-definition/src/test/resources/errors/globalLibraryObjectMethodCall.groovy, pipeline-model-definition/src/test/resources/json/libraries/globalLibrarySuccess.json, pipeline-model-definition/src/test/resources/libraries/globalLibrarySuccess.groovy, pipeline-model-definition/src/test/resources/libraries/globalLibrarySuccessInScript.groovy
More breakage from jenkinsci/jenkins#5425, discovered when running PCT against a recent core incremental. This gets these tests to pass against both old and new cores.
=> Adapting `LibrariesTest`, `MultipleUnnamedParametersTest`, and `ScriptStepTest` to jenkinsci/jenkins#5425

pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/AbstractModelDefTest.java
Subclasses of `AbstractModelDefTest` frequently have blocks like https://github.com/jenkinsci/pipeline-model-definition-plugin/blob/3f496434de4cf2fb618bf85d4fa306978a485630/pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/ValidatorTest.java#L64-L70 which invariably use `createOnlineSlave`. Yet according to test failures described in https://github.com/jenkinsci/bom/issues/613#issuecomment-969300344, occasionally these agents go offline for reasons not currently understood but probably environmental. Since this is very likely not a bug in tested plugin code, it ought not cause a test failure.
=> Assume that configured agents are online

pipeline-model-api/pom.xml, pipeline-model-definition/pom.xml, pipeline-model-extensions/pom.xml, pipeline-stage-tags-metadata/pom.xml
https://github.com/jenkinsci/pipeline-model-definition-plugin/pull/463 deployed a bad incremental POM. `gitHubRepo` is correctly used in the parent POM, but then `<scm>` is being overridden in plugins inside it. This seems to be a common mistake.
=> Delete `<scm>` sections from submodules

pom.xml
Amends #464 to work around a silly default in Maven which dates to CVS/Subversion days.
```diff
--- before.xml	2021-11-17 13:51:54.820443485 -0500
+++ after.xml	2021-11-17 13:54:08.380403669 -0500
@@ -46,10 +46,10 @@
<name>Andrew Bayer</name>
</developer>
</developers>
-  <scm>
-    <connection>scm:git:git://github.com/jenkinsci/pipeline-model-definition-plugin.git/pipeline-stage-tags-metadata</connection>
-    <developerConnection>scm:git:git@github.com:jenkinsci/pipeline-model-definition-plugin.git/pipeline-stage-tags-metadata</developerConnection>
-    <url>https://github.com/jenkinsci/pipeline-model-definition-plugin/pipeline-stage-tags-metadata</url>
+  <scm child.scm.connection.inherit.append.path="false" child.scm.developerConnection.inherit.append.path="false" …
```
=> Set `child.scm.*.inherit.append.path=false`

pom.xml
This is a total hack, but if it stabilizes CI runs such that we can process the PR queue and then go back later to fix these tests, I suppose that is better than nothing.
=> Skip resource-intensive tests on CI

pipeline-model-definition/pom.xml, pom.xml
Updates the plugin parent POM from a weekly to an LTS, along with updating the plugin BOM accordingly. This is necessary in order to be able to test this plugin on Java 17, as I am trying to do in jenkinsci/bom#935. The CodeNarc Maven plugin doesn't seem to work at all on Java 17, but it appears to be adding little value so I just removed it. With these changes I can run `mvn clean verify -Dtest=org.jenkinsci.plugins.pipeline.modeldefinition.DeclarativePipelineTest -DfailIfNoTests=false -Djenkins-test-harness.version=1721.v385389722736 '-DargLine=--add-opens java.base/java.lang=ALL-UNNAMED --add-opens java.base/java.io=ALL-UNNAMED --add-opens java.base/java.util=ALL-UNNAMED --add-opens java.base/java.util.concurrent=ALL-UNNAMED'` successfully on Java 17. CC @car-roll
=> Update plugin parent POM and plugin BOM

pipeline-model-definition/pom.xml, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/LibrariesTest.java, pom.xml
This PR refiles the BOM portion of #498 as it was reverted in #501 due to windows CI failures.
Failures generated are `filename too long`. See: https://github.com/jenkinsci/pipeline-model-definition-plugin/runs/5580211853
See also: https://github.com/jenkinsci/pipeline-model-definition-plugin/pull/499
cc @basil
=> Update plugin BOM and jenkins version

pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/LibrariesTest.java
https://github.com/jenkins-infra/pipeline-library/pull/334 should remove the need to call `core.longpaths` for windows git.
=> core.longpaths config no longer needed for windows git

pipeline-model-definition/pom.xml, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/AbstractModelDefTest.java, pom.xml
This test dependency has caused us a lot of pain with `RequireUpperBoundDeps`. Simpler just to remove it and rely on the Jenkins Test Harness instead. CC @car-roll
=> Remove JCabi Matchers

pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/AgentTest.java, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/BasicModelDefTest.java, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/DurabilityTest.java, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/EnvironmentTest.java, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/LibrariesTest.java, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/MatrixTest.java, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/ParallelTest.java, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/PostStageTest.java, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/ScriptStepTest.java, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/SerializationTest.java, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/StepsTest.java, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/ToolsTest.java, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/ValidatorTest.java, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/WhenStageMultibranchTest.java, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/WhenStageTest.java
in older versions of Jenkins the tests would be less flaky as adding any
Node would cause all labels to be re-evaluated, so when creating a few
agents and adding labels in a loop the last one created would at least
deterministically ensure that all previous agents labels where correct.
However since 2.332 (jenkinsci/jenkins#5882)
only labels part of a node added or removed would be updated, and when
creating the agents they where created without labels, which where added
later.
This has the potential to cause tests to be flaky depending on when the periodic
trimLabels was called (or at least on other timing related things)
Additionally creating agents and waiting for them to come oneline is
slow. A job can be scheduled and the pipeline will run and then wait for the node to be
available, …
=> calling setLabels on an agent will not persist the node.

pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/AbstractModelDefTest.java
#462 (arguably) made sense at the time. Yet after #527, the effect was that a lot of tests (e.g., `LibrariesTest`) started being skipped all the time.
=> Remove assumption that configured agents are online

pipeline-model-definition/src/main/resources/org/jenkinsci/plugins/pipeline/modeldefinition/agent/impl/AnyScript.groovy
Simplifying a rather roundabout system to just be like https://github.com/jenkinsci/pipeline-model-definition-plugin/blob/12b420f036e5e4d114791602b896c5790567f7a6/pipeline-model-definition/src/main/resources/org/jenkinsci/plugins/pipeline/modeldefinition/agent/impl/LabelScript.groovy#L41-L45 except without the `label` and `customWorkspace` fields. The weird logic seems to have been introduced in #94, at which time perhaps it made sense but it seems `CheckoutScript` when introduced in #123 was not also used here.
=> Simplify `AnyScript`

pipeline-model-definition/src/main/java/org/jenkinsci/plugins/pipeline/modeldefinition/ModelStepLoader.java, pipeline-model-definition/src/main/java/org/jenkinsci/plugins/pipeline/modeldefinition/when/impl/ChangeLogConditional.java, pipeline-model-definition/src/test/resources/org/jenkinsci/plugins/pipeline/modeldefinition/generator/DirectiveGeneratorTest$ComplexDeclarativeAgentScript.groovy, pipeline-model-extensions/src/main/java/org/jenkinsci/plugins/pipeline/modeldefinition/agent/DeclarativeAgent.java, pipeline-model-extensions/src/main/java/org/jenkinsci/plugins/pipeline/modeldefinition/withscript/WithScriptDescribable.java, pipeline-model-extensions/src/main/java/org/jenkinsci/plugins/pipeline/modeldefinition/withscript/WithScriptDescriptor.java, pom.xml
See https://github.com/jenkinsci/workflow-cps-plugin/pull/538. The fix for SECURITY-359 added a new API that should be used by plugins that define Groovy DSLs. Declarative defines two main kinds of Groovy DSLs:
* `ModelInterpreter.groovy` via `ModelStepLoader`: The main declarative syntax
* Various Groovy files via subclasses of `WithScriptDescribable`: Extensions related to `agent` (`DeclarativeAgent`, used by other plugins, specifically `docker-workflow`, `kubernetes`, and `amazon-ecs`) and `when` (`DeclarativeStageConditional`).`
This PR implements `GroovySourceFileAllowlist` for various individual files, but also for `WithScriptDescribable` in a generic way that automatically allows the scripts used by subclasses. This allows us to remove entries from `default-allowlist` upstream in …
=> Use GroovySourceFileAllowlist to adapt to SECURITY-359 changes

pipeline-model-definition/pom.xml, pom.xml
Takes care of #539, #538, #537, and #536 by updating the BOM and then removing version specifiers and `dependencyManagement` entries that are no longer needed.
=> Update BOM and remove unnecessary version specifiers

pom.xml
Sorry for another build PR so soon after the last one. This is needed for the forthcoming PCT multi-module mode to pull in the fix for [JENKINS-62658](https://issues.jenkins.io/browse/JENKINS-62658) via https://github.com/jenkinsci/maven-hpi-plugin/pull/453. I tested this successfully with the latest update to the multimodule project branch of PCT, which is now doing `mvn process test-classes` rather than `mvn install`, therefore requiring the fix for [JENKINS-62658](https://issues.jenkins.io/browse/JENKINS-62658). With these changes you can now successfully run `mvn process-test-classes` in the root directory of the repository, which was not possible with the old version of Maven HPI plugin.
CC @car-roll @jglick @olamy
=> Upgrade plugin parent POM from 4.56 to 4.57

pom.xml
No new version of json-schema-validator is available and seems abandoned.
The XXE is not reachable from this plugin and a new schema validator library is needed,
but in the meantime manage the rhino dependency to satisfy security scanners.
=> Make security scanners happy about XRAY-178804 Rhino XXE

pipeline-model-definition/src/main/java/org/jenkinsci/plugins/pipeline/modeldefinition/properties/PreserveStashesJobProperty.java
https://github.com/jenkinsci/bom/pull/2105 turned up a test regression seen in https://github.com/jenkinsci/workflow-job-plugin/pull/357#issuecomment-1561105285 which was easily reproduced. Confusingly, stashes were being deleted from the most recent build (11) of the project, which had just been run, despite it being marked to preserve stashes from the last two builds. Even more confusingly, the `shouldClearAll` implementation correctly returned builds 11 and 10 from `j.getBuilds().completedOnly().limit(bc)`, yet claimed that 11 should be cleared nonetheless. It turned out that the comparison via `Object.equals` was failing for two copies (`WorkflowRun`s) of build 11, due to use of `RunLoadCounter` in the test: a subtle change in timing caused the stash clearing check for 11 to run after …
=> Refine build comparison in `PreserveStashesJobProperty`

pipeline-model-api/pom.xml, pipeline-model-definition/pom.xml, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/BasicModelDefTest.java, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/BuildConditionResponderTest.java, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/MatrixTest.java, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/ParallelTest.java, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/StageInputTest.java, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/WhenStageTest.java, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/actions/RestartDeclarativePipelineActionTest.java, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/endpoints/ErrorsEndpointOpsTest.java, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/endpoints/ModelConverterActionStepsTest.java, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/endpoints/ModelConverterActionTest.java, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/endpoints/SuccessfulEndpointOpsTest.java, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/generator/DirectiveGeneratorTest.java, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/properties/PreserveStashesJobPropertyLoadTest.java, pipeline-model-extensions/pom.xml, pom.xml
* Contents of pull request
* #622 
* #621 
* Require Jenkins 2.387.3 or newer
* Require workflow-cps 3691.v28b_14c465a_b_b_ for HTMLUnit 3
* Test with git plugin 5.1.0 for HTMLUnit 3
* Add git and httpcomponent test dependencies
* Supersedes pull requests
* #616 
* https://github.com/jenkinsci/jenkins-test-harness/releases/tag/2010.v1888f1a_cd45a_
* https://github.com/jenkinsci/bom/pull/2158
* https://github.com/jenkinsci/branch-api-plugin/pull/379
* https://github.com/jenkinsci/workflow-cps-plugin/pull/723
* https://github.com/jenkinsci/workflow-multibranch-plugin/pull/258
* https://github.com/jenkinsci/workflow-scm-step-plugin/pull/126
* Description:
* Upgrade to HTMLUnit 3 by making necessary upgrades of other components
* No documentation …
=> Require Jenkins 2.387.3 or newer

pipeline-model-definition/src/main/resources/org/jenkinsci/plugins/pipeline/modeldefinition/generator/DirectiveGenerator/index.jelly
See [JENKINS-70906](https://issues.jenkins.io/browse/JENKINS-70906). Jenkins core currently uses [Prototype 1.7](https://github.com/prototypejs/prototype/releases/tag/1.7), released on November 15, 2010. The latest version is [Prototype 1.7.3](https://github.com/prototypejs/prototype/releases/tag/1.7.3), released on September 22, 2015. When an attempt was made to upgrade to 1.7.3 in 2018 in [JENKINS-49319](https://issues.jenkins.io/browse/JENKINS-49319), the change had to be reverted. Since this library has been unmaintained for the past 8 years, this PR removes any usages of it in favor of native JavaScript APIs. To test this, I installed this plugin on a custom build of Jenkins that had Prototype ripped out (a local project branch), and generated several Declarative snippets on the …
=> Replace Prototype.js with native JavaScript

pipeline-model-api/pom.xml, pipeline-model-definition/pom.xml, pipeline-model-extensions/pom.xml, pom.xml
Update the parent pom from 4.66 to 4.73.
Update the plugin bill of materials from 2143 to 2401.
Remove the unnecessary version declarations for workflow-cps and git plugins.
Supersedes the following pull requests:
* #636
* #664
* #665
* #666
* #667
* #669 
* #670
* n/a
* Description:
* Update the parent pom from 4.66 to 4.73. Update the plugin bill of materials from 2143 to 2401. Remove the unnecessary version declarations for workflow-cps and git plugins.
* n/a
* n/a
=> Remove unnecessary version declarations by updating bom and pom

pipeline-model-definition/src/main/resources/org/jenkinsci/plugins/pipeline/modeldefinition/generator/DirectiveGenerator/index.jelly, pipeline-model-definition/src/main/resources/org/jenkinsci/plugins/pipeline/modeldefinition/generator/DirectiveGenerator/indexScript.js
* https://issues.jenkins.io/browse/JENKINS-72136
* Description:
* Inline handlers were showing in console. Used the recommendations given in the issue.
* There is no feature change but just a minor change for security reasons.
* n/a
Testing:
Screenshots:
Before:
After:
mvn tests run and changes appear in mvn:hpi run
=> [JENKINS-72136] Remove inline onclick handlers for generate directive button

pipeline-model-definition/src/main/resources/org/jenkinsci/plugins/pipeline/modeldefinition/generator/ToolsDirective/config.jelly, pom.xml
See https://github.com/jenkinsci/jenkins/pull/8418#discussion_r1337479191
hetero-list adjunct was removed in https://github.com/jenkinsci/jenkins/pull/8418
If this adjunct gets called, a large stack trace error should appear in the logs.
Done locally, but I was not able to identify the gui interface for the ToolsDirective that would exercise the adjunct.
=> remove lib.form.hetero-list.hetero-list

pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/AbstractModelDefTest.java, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/endpoints/ErrorsEndpointOpsTest.java, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/validator/ErrorsJSONParserTest.java
While trying to add the Kubernetes plugins to `jenkinsci/bom` in https://github.com/jenkinsci/bom/pull/2417 I got some test failures of the form:
> "error": "Invalid agent type \"foo\" specified. Must be one of [any, kubernetes, label, none, otherField]"
}]) didn't contain expected error 'Invalid agent type "foo" specified. Must be one of [any, label, none, otherField]'
The existing test logic had tried to deal with this case by defining a `legalAgentTypes` field, but it was flawed in a few ways:
- It was not used consistently in `AbstractModelDefTest#configsWithErrors`: `unknownBareAgentType` used it but not `unknownAgentType`
- Any usage of `legalAgentTypes` from `AbstractModelDefTest#configsWithErrors` was flawed and yielding the empty string (thus making the test pass erroneously) …
=> Allow valid agent types in PCT context

pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/parser/RuntimeASTTransformer.groovy
This plugin currently depends on ASM, provided by Jenkins core. We'd eventually like to drop ASM from Jenkins core and move it into a library plugin, so this PR prepares this plugin by dropping this plugin's dependency on ASM. The dependency was only used in one place for a constant, and since this constant is unlikely to ever change we can simply inline it.
`mvn clean verify -Dtest=InjectedTest,org.jenkinsci.plugins.pipeline.modeldefinition.parser.RuntimeASTTransformerTest`
=> Drop dependency on ASM

pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/Utils.groovy, pipeline-model-definition/src/main/resources/org/jenkinsci/plugins/pipeline/modeldefinition/ModelInterpreter.groovy, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/MatrixTest.java, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/ParallelTest.java, pipeline-model-definition/src/test/resources/matrix/matrixStagesHaveStatusWhenMultipleSkipped.groovy
* [JENKINS-72841](https://issues.jenkins.io/browse/JENKINS-72841)
* Fixes https://github.com/jenkinsci/pipeline-graph-view-plugin/issues/220
* Fixes https://github.com/jenkinsci/pipeline-model-definition-plugin/pull/698
* Description:
* Previously skipping stages would only be tagged for the first occurrence of the stage. This now passes the flow node id rather than guessing by stage name
* ...
Before:
After:
see https://github.com/jenkinsci/pipeline-graph-view-plugin/issues/220
=> [JENKINS-72841] - Pass flow node ID when skipping stage

pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/steps/CredentialWrapperStepTest.java
amends #723 that was working as the KeyStore was not validated.
However https://github.com/jenkinsci/credentials-plugin/pull/543 now validates the keystore and hence this test started failing as the password did not match
* Description:
* ...
* ...
=> use valid password for test code

pipeline-model-definition/src/main/resources/org/jenkinsci/plugins/pipeline/modeldefinition/generator/DirectiveGenerator/indexScript.js
Now that Prototype.js has been removed in 2.426.x, we can remove the no-longer needed `Object.toJSON` workaround. This plugin's baseline is 2.426.1, so this change is safe.
`mvn clean verify -DskipTests`
=> Simplify JSON parsing

pipeline-model-definition/pom.xml, pipeline-model-definition/src/main/java/org/jenkinsci/plugins/pipeline/modeldefinition/parser/InternalCalls.java, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/parser/InternalCallsTest.java, pom.xml
Downstream of https://github.com/jenkinsci/workflow-cps-plugin/pull/929.
=> Implement `IgnoredInternalClasses`

pom.xml
Picking up https://github.com/jenkinsci/support-core-plugin/pull/624 and https://github.com/jenkinsci/jenkins-test-harness/pull/922 to try to solve https://ci.jenkins.io/job/Plugins/job/pipeline-model-definition-plugin/job/PR-762/1/testReport/org.jenkinsci.plugins.pipeline.modeldefinition/MatrixTest/windows_17___Build__windows_17_______/ in #762 and similar. Supersedes #760 & #763.
=> Bump deps to address test flakes on Windows

pipeline-model-definition/src/main/resources/org/jenkinsci/plugins/pipeline/modeldefinition/ModelInterpreter.groovy, pipeline-model-definition/src/main/resources/org/jenkinsci/plugins/pipeline/modeldefinition/agent/impl/AnyScript.groovy, pipeline-model-definition/src/main/resources/org/jenkinsci/plugins/pipeline/modeldefinition/agent/impl/LabelScript.groovy, pipeline-model-definition/src/main/resources/org/jenkinsci/plugins/pipeline/modeldefinition/agent/impl/NoneScript.groovy, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/BasicModelDefTest.java, pipeline-model-definition/src/test/resources/org/jenkinsci/plugins/pipeline/modeldefinition/agent/impl/LabelAndOtherFieldAgentScript.groovy, pipeline-model-extensions/src/main/java/org/jenkinsci/plugins/pipeline/modeldefinition/agent/DeclarativeAgent.java, pipeline-model-extensions/src/main/java/org/jenkinsci/plugins/pipeline/modeldefinition/agent/DeclarativeAgentScript.java, pipeline-model-extensions/src/main/java/org/jenkinsci/plugins/pipeline/modeldefinition/agent/DeclarativeAgentScript2.java, pipeline-model-extensions/src/main/java/org/jenkinsci/plugins/pipeline/modeldefinition/agent/RetryableDeclarativeAgent.java, pipeline-model-extensions/src/main/resources/org/jenkinsci/plugins/pipeline/modeldefinition/agent/CheckoutScript.groovy
Output from https://github.com/jenkinsci/workflow-support-plugin/pull/305 indicate that a lot of stack frames are `Closure.call`. In some cases this is actually helping to structure code. In others, it is not. Two half-cheese, half-sausage pizzas are just one cheese and one sausage pizza.
[CloudBees-internal issue](https://cloudbees.atlassian.net/browse/BEE-54716)
=> Reduce depth of `Closure`s being `call`ed

Jenkinsfile
Pending https://github.com/jenkins-infra/helpdesk/issues/4574. You can see that even #771 for example is broken otherwise.
=> Temporarily suppress Windows builds

Jenkinsfile
Reverts jenkinsci/pipeline-model-definition-plugin#773
https://github.com/jenkins-infra/helpdesk/issues/4574 is reported as fixed.
=> Revert "Temporarily suppress Windows builds"

pipeline-model-definition/src/main/resources/org/jenkinsci/plugins/pipeline/modeldefinition/actions/RestartDeclarativePipelineAction/index.jelly
* n/a
* Description:
* Use consistent style for restart from stage
- **Before** ![CleanShot 2025-04-24 at 13 02 47](https://github.com/user-attachments/assets/401ddb70-c302-46c8-baae-d49fe04bddb7)
* **After** ![CleanShot 2025-04-24 at 13 01 37](https://github.com/user-attachments/assets/d9b249c8-1ded-4549-9bc4-1740fd49a1bc)
* ...
=> Update inconsistent style for restart from stage
