pom.xml, src/main/resources/org/jenkinsci/plugins/pipeline/modeldefinition/ModelInterpreter.groovy, src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/AgentTest.java, src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/BasicModelDefTest.java, src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/BuildConditionResponderTest.java, src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/EnvironmentTest.java, src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/ScriptStepTest.java, src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/ToolsTest.java
[JENKINS-37897](https://issues.jenkins-ci.org/browse/JENKINS-37897)
Also create synthetic stages for post-build and notifications. Maybe
more of those to come in the future, but haven't decided yet. Also
bumped plugin versions.
cc @reviewbybees @michaelneale @svanoort @jglick @oleg-nenashev
=> [FIXED JENKINS-37897] Switch to block scoped stages.

Jenkinsfile
cc @reviewbybees @oleg-nenashev @svanoort @batmat @rtyler
=> Some comments and improvements to the example Jenkinsfile.

src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/Utils.groovy, src/main/resources/org/jenkinsci/plugins/pipeline/modeldefinition/ClosureModelTranslator.groovy, src/main/resources/org/jenkinsci/plugins/pipeline/modeldefinition/PropertiesToMapTranslator.groovy
=> Remove newInstanceWrapper(Class<NestedModel>).

src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/AbstractModelDefTest.java, src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/BasicModelDefTest.java, src/test/resources/globalLibrarySuccess.groovy
Initial integration tests with https://github.com/jenkinsci/workflow-cps-global-lib-plugin/pull/10 failed, but this seems to be due to preëxisting bugs here.
@reviewbybees
=> Demonstrating some stuff which does not work as I would expect

src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/parser/ModelParser.groovy, src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/ValidatorTest.java, src/test/resources/errors/emptyAgent.groovy
[JENKINS-37928](https://issues.jenkins-ci.org/browse/JENKINS-37928)
The exact error message could be better - I need to understand what
other possible ways this could fail to be a method call expression
besides just not having arguments, but this should be general enough a
message for all possibilities for now.
cc @reviewbybees esp @oleg-nenashev @batmat @svanoort @michaelneale
=> [FIXED JENKINS-37928] Properly detect sections without values.

src/main/resources/org/jenkinsci/plugins/pipeline/modeldefinition/ModelInterpreter.groovy, src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/BasicModelDefTest.java, src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/BuildConditionResponderTest.java, src/test/resources/failingNotifications.groovy, src/test/resources/failingPipeline.groovy, src/test/resources/failingPostBuild.groovy
[JENKINS-38049](https://issues.jenkins-ci.org/browse/JENKINS-38049)
And make sure we throw failures properly. This still feels a bit weird
to me, but it's on the right track, at least.
@vivek - does this look to do the trick for you?
cc @reviewbybees
=> [FIXED JENKINS-38049] Stop using catchError.

src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/ast/ModelASTAgent.groovy, src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/model/Agent.groovy, src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/parser/ModelParser.groovy, src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/validator/ModelValidator.groovy, src/main/resources/org/jenkinsci/plugins/pipeline/modeldefinition/ClosureModelTranslator.groovy, src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/AbstractModelDefTest.java, src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/AgentTest.java, src/test/resources/agentAny.groovy, src/test/resources/json/agentAny.json
[JENKINS-37932](https://issues.jenkins-ci.org/browse/JENKINS-37932)
Better approach for "run anywhere". I think this gets rid of any need
to make the agent section optional, at least for now.
cc @reviewbybees esp @vivek @michaelneale @i386
=> [FIXED JENKINS-37932] Add "agent any"

Jenkinsfile
And pruning out the goofy notifications section until I get the mail
step to be better and add getCulprits to WorkflowRun
cc @rtyler
=> Updating Jenkinsfile for ci.jenkins.io tool versions

EXTENDING.md, src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/Utils.groovy, src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/ast/ModelASTAgent.groovy, src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/ast/ModelASTBranch.groovy, src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/ast/ModelASTBuildCondition.groovy, src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/ast/ModelASTElement.groovy, src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/ast/ModelASTEnvironment.groovy, src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/ast/ModelASTNamedArgumentList.groovy, src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/ast/ModelASTNotifications.groovy, src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/ast/ModelASTPipelineDef.groovy, src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/ast/ModelASTPositionalArgumentList.groovy, src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/ast/ModelASTPostBuild.groovy, src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/ast/ModelASTSingleArgument.groovy, src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/ast/ModelASTStage.groovy, src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/ast/ModelASTStages.groovy, src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/ast/ModelASTStep.groovy, src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/ast/ModelASTTools.groovy, src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/ast/ModelASTTreeStep.groovy, src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/parser/Converter.groovy, src/main/java/org/jenkinsci/plugins/pipeline/modeldefinition/actions/ExecutionModelAction.java, src/main/java/org/jenkinsci/plugins/pipeline/modeldefinition/endpoints/ModelConverterAction.java, src/main/resources/org/jenkinsci/plugins/pipeline/modeldefinition/ModelInterpreter.groovy, src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/BasicModelDefTest.java, src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/endpoints/ErrorsEndpointOpsTest.java, src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/endpoints/SuccessfulEndpointOpsTest.java, src/test/resources/executionModelAction.groovy
[JENKINS-38152](https://issues.jenkins-ci.org/browse/JENKINS-38152)
Very much a work-in-progress at this point, but thought I'd get this up for initial feedback.
cc @reviewbybees esp @vivek
=> JENKINS-38152 - expose execution model on WorkflowRun

src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/model/Agent.groovy, src/main/resources/org/jenkinsci/plugins/pipeline/modeldefinition/ModelInterpreter.groovy, src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/AgentTest.java, src/test/resources/agentDocker.groovy, src/test/resources/agentDockerWithEmptyDockerArgs.groovy, src/test/resources/agentDockerWithNullDockerArgs.groovy
This adds the `args` parameter of the docker plugin to the agent directive.
=> [FIXED JENKINS-38242] Add the ability to specify agent parameters (docker)

src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/AbstractModelDefTest.java, src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/parser/ExecuteConvertedTest.java, src/test/resources/buildPluginParentPOM.groovy
Also fix a test while I'm here. `@ClassRule` is magic.
cc @reviewbybees esp @rsandell @stephenc @batmat
=> Experimenting to speed up build.

src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/parser/Converter.groovy, src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/parser/ModelParser.groovy, src/main/java/org/jenkinsci/plugins/pipeline/modeldefinition/endpoints/ModelConverterAction.java, src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/EnvironmentTest.java, src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/endpoints/ModelConverterActionStepsTest.java, src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/util/IsJsonObjectContaining.java, src/test/resources/json/steps/arrayEcho.json, src/test/resources/json/steps/simpleEcho.json, src/test/resources/json/steps/simpleScript.json
=> [JENKINS-38564] API to convert json step blob to step syntax (and back) - one step at a time

src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/ast/ModelASTPipelineDef.groovy, src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/ast/ModelASTValue.groovy, src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/AbstractModelDefTest.java, src/test/resources/json/stringsNeedingEscapeLogic.json, src/test/resources/stringsNeedingEscapeLogic.groovy
=> [FIXED JENKINS-38818] Correctly escape string constants when generating groovy from AST

src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/ast/ModelASTBuildConditionsContainer.groovy, src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/ast/ModelASTPostStage.groovy, src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/ast/ModelASTStage.groovy, src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/model/PostStage.groovy, src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/model/Root.groovy, src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/model/Stage.groovy, src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/parser/JSONParser.groovy, src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/parser/ModelParser.groovy, src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/validator/ModelValidator.groovy, src/main/resources/ast-schema.json, src/main/resources/org/jenkinsci/plugins/pipeline/modeldefinition/ModelInterpreter.groovy, src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/AbstractModelDefTest.java, src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/PostStageTest.java, src/test/resources/postStage/failingNotifications.groovy, src/test/resources/postStage/globalAndLocalAlways.groovy, src/test/resources/postStage/localAll.groovy, src/test/resources/postStage/localAlways.groovy
=> [JENKINS-37792] Per stage post build steps

pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/model/AbstractBuildConditionResponder.groovy, pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/model/conditions/Aborted.groovy, pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/model/conditions/Always.groovy, pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/model/conditions/Changed.groovy, pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/model/conditions/Failure.groovy, pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/model/conditions/Success.groovy, pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/model/conditions/Unstable.groovy, pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/validator/ModelValidatorImpl.groovy, pipeline-model-definition/src/main/java/org/jenkinsci/plugins/pipeline/modeldefinition/model/BuildCondition.java, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/BuildConditionResponderTest.java, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/ValidatorTest.java, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/endpoints/ModelConverterActionTest.java, pipeline-model-definition/src/test/resources/buildConditionOrdering.groovy
[JENKINS-38993](https://issues.jenkins-ci.org/browse/JENKINS-38993)
Ordering is:
* Always
* Changed
* Aborted/Failure/Success/Unstable
This is all done via ordinals.
cc @reviewbybees esp @stephenc @rsandell
=> [FIXED JENKINS-38993] Add deterministic ordering of conditions.

pipeline-model-definition/pom.xml, pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/Utils.groovy, pipeline-model-definition/src/main/resources/org/jenkinsci/plugins/pipeline/modeldefinition/ModelInterpreter.groovy, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/BasicModelDefTest.java, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/PostStageTest.java
[JENKINS-39631](https://issues.jenkins-ci.org/browse/JENKINS-39631)
cc @reviewbybees esp @vivek @svanoort @rsandell
=> [FIXED JENKINS-39631] Last step in failed stage has an error.

EXTENDING.md
cc @reviewbybees esp @kzantow @michaelneale @rsandell
=> Add info on step conversion endpoint

pipeline-model-api/src/main/java/org/jenkinsci/plugins/pipeline/modeldefinition/ast/AbstractModelASTCodeBlock.java, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/AbstractModelDefTest.java, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/BasicModelDefTest.java, pipeline-model-definition/src/test/resources/basicWhen.groovy, pipeline-model-definition/src/test/resources/json/basicWhen.json, pipeline-model-definition/src/test/resources/json/skippedWhen.json, pipeline-model-definition/src/test/resources/skippedWhen.groovy
We need to make sure we've got a JSON conversion test for `when`, and it's good to have a visible example of the syntax for others to see.
cc @reviewbybees esp @michaelneale @rsandell
=> Add "when" JSON conversion test.

pipeline-model-definition/src/main/resources/org/jenkinsci/plugins/pipeline/modeldefinition/ModelInterpreter.groovy, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/BasicModelDefTest.java, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/WhenStageTest.java
This is just a band-aid until JENKINS-38153 lands with a better
solution involving tags metadata and all that jazz, but this'll at
least make sure our execution plan matches reality for now.
cc @reviewbybees esp @rsandell @HRMPW @i386
=> Run empty stages for conditionally-skipped stages.

pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/BasicModelDefTest.java
=> Clean up a few overlooked old-school tests

pipeline-model-api/src/main/java/org/jenkinsci/plugins/pipeline/modeldefinition/ast/ModelASTStage.java, pipeline-model-api/src/main/resources/ast-schema.json, pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/parser/JSONParser.groovy, pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/parser/ModelParser.groovy, pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/parser/ParallelMatch.groovy, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/AbstractModelDefTest.java, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/BasicModelDefTest.java, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/ValidatorTest.java, pipeline-model-definition/src/test/resources/errors/parallelPipelineWithInvalidExtraKey.groovy, pipeline-model-definition/src/test/resources/errors/parallelPipelineWithInvalidFailFast.groovy, pipeline-model-definition/src/test/resources/json/parallelPipelineWithFailFast.json, pipeline-model-definition/src/test/resources/parallelPipelineWithFailFast.groovy
[JENKINS-40136](https://issues.jenkins-ci.org/browse/JENKINS-40136)
=> [FIXED JENKINS-40136] Properly support failFast in parallel.

pipeline-model-definition/pom.xml, pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/Utils.groovy, pipeline-model-definition/src/main/resources/org/jenkinsci/plugins/pipeline/modeldefinition/ModelInterpreter.groovy, pipeline-model-definition/src/main/resources/org/jenkinsci/plugins/pipeline/modeldefinition/agent/impl/DockerPipelineFromDockerfileScript.groovy, pipeline-model-definition/src/main/resources/org/jenkinsci/plugins/pipeline/modeldefinition/agent/impl/DockerPipelineScript.groovy, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/BasicModelDefTest.java, pipeline-model-definition/src/test/resources/failureBeforeStages.groovy, pipeline-model-definition/src/test/resources/skippedStagesForFailure.groovy
[JENKINS-40226](https://issues.jenkins-ci.org/browse/JENKINS-40226)
More notably, make sure we still end up doing a `post` for them if
needed and that the build status is correct at that time.
=> [FIXED JENKINS-40226] Make sure non-within-stage failures are real.

pipeline-model-api/src/main/java/org/jenkinsci/plugins/pipeline/modeldefinition/ast/ModelASTJobProperties.java, pipeline-model-api/src/main/java/org/jenkinsci/plugins/pipeline/modeldefinition/ast/ModelASTPipelineDef.java, pipeline-model-api/src/main/java/org/jenkinsci/plugins/pipeline/modeldefinition/validator/ModelValidator.java, pipeline-model-api/src/main/resources/ast-schema.json, pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/model/MethodsToList.groovy, pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/model/Root.groovy, pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/parser/JSONParser.groovy, pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/parser/ModelParser.groovy, pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/validator/ModelValidatorImpl.groovy, pipeline-model-definition/src/main/resources/org/jenkinsci/plugins/pipeline/modeldefinition/ModelInterpreter.groovy, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/AbstractModelDefTest.java, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/ValidatorTest.java, pipeline-model-definition/src/test/resources/errors/blockInJobProperties.groovy, pipeline-model-definition/src/test/resources/errors/emptyJobProperties.groovy, pipeline-model-definition/src/test/resources/json/errors/emptyJobProperties.json, pipeline-model-definition/src/test/resources/json/simpleJobProperties.json, pipeline-model-definition/src/test/resources/multipleProperties.groovy, pipeline-model-definition/src/test/resources/simpleJobProperties.groovy
[JENKINS-40388](https://issues.jenkins-ci.org/browse/JENKINS-40388)
cc @reviewbybees esp @rsandell @michaelneale @i386 @HRMPW
=> [FIXED JENKINS-40388] Rename "jobProperties" to "properties"

pipeline-model-definition/src/main/resources/org/jenkinsci/plugins/pipeline/modeldefinition/agent/impl/DockerPipelineFromDockerfileScript.groovy, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/AgentTest.java, pipeline-model-definition/src/test/resources/errors/malformed.groovy
For some reason the dockerfile and malformed verification tests
didn't succeed on my new dev machine when I made a fresh clone
of the workspace. While fixing them I wonder how they ever could have worked.
@reviewbybees esp. @abayer
=> Fixed some test failures

SYNTAX.md
cc @reviewbybees esp @rsandell @michaelneale @HRMPW
=> Get rid of misleading .each example

pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/model/conditions/Aborted.groovy, pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/model/conditions/Always.groovy, pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/model/conditions/Changed.groovy, pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/model/conditions/Failure.groovy, pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/model/conditions/Success.groovy, pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/model/conditions/Unstable.groovy, pipeline-model-definition/src/main/java/org/jenkinsci/plugins/pipeline/modeldefinition/model/BuildCondition.java, pipeline-model-definition/src/main/resources/org/jenkinsci/plugins/pipeline/modeldefinition/model/conditions/Messages.properties
[JENKINS-40239](https://issues.jenkins-ci.org/browse/JENKINS-40239)
There'll be a downstream change corresponding to this in the editor.
cc @reviewbybees esp @rsandell @kzantow
=> [JENKINS-40239] Add descriptions for build conditions

pipeline-model-api/src/main/java/org/jenkinsci/plugins/pipeline/modeldefinition/ast/ModelASTStage.java, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/AbstractModelDefTest.java, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/BasicModelDefTest.java, pipeline-model-definition/src/test/resources/json/parallelPipelineQuoteEscaping.json, pipeline-model-definition/src/test/resources/json/parallelPipelineWithSpaceInBranch.json, pipeline-model-definition/src/test/resources/parallelPipelineQuoteEscaping.groovy, pipeline-model-definition/src/test/resources/parallelPipelineWithSpaceInBranch.groovy
[JENKINS-40580](https://issues.jenkins-ci.org/browse/JENKINS-40580)
Decided to be defensive and always quote when converting, rather than
trying to figure out when we could avoid quoting.
cc @reviewbybees esp @kzantow @rsandell
=> [FIXED JENKINS-40580] Quote parallel branch names

pipeline-model-definition/pom.xml, pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/parser/Converter.groovy, pipeline-model-definition/src/main/java/org/jenkinsci/plugins/pipeline/modeldefinition/parser/GroovyShellDecoratorImpl.java, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/BasicModelDefTest.java, pipeline-model-definition/src/test/resources/libraryAnnotation.groovy, pipeline-model-definition/src/test/resources/libraryObjectInScript.groovy, pipeline-model-definition/src/test/resources/libraryObjectOutsideScript.groovy
[JENKINS-40657](https://issues.jenkins-ci.org/browse/JENKINS-40657)
Note that this is on top of #80. One thing that did have to change is that the object has to be `Serializable`.
cc @reviewbybees esp @rsandell and also @imod since he opened the issue. =)
=> [JENKINS-40657] Verify that library objects can be instantiated

pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/DurabilityTest.java
[JENKINS-40547](https://issues.jenkins-ci.org/browse/JENKINS-40547)
Was 99% sure this would work, and, well, that was correct.
cc @reviewbybees esp @rsandell and @jglick - any ideas for additional things we should be testing re durability?
=> [FIXED JENKINS-40547] Verify durability of Declarative runs

pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/parser/Converter.groovy
We didn't have @Library in our classloader, so we'd get errors. That
was annoying. So here is a fix.
@kzantow - can you do a local build of this and verify it works right for you now?
cc @reviewbybees esp @kzantow @rsandell
=> Fixing errors using endpoint/CLI for conversion/validation

pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/Utils.groovy, pipeline-model-definition/src/main/resources/org/jenkinsci/plugins/pipeline/modeldefinition/ModelInterpreter.groovy
It's a bit confusing when you see the stage step in the logs for a
skipped stage but no steps executed. There should be log messages for
the skip cases. So, well, here they are.
cc @reviewbybees esp @batmat @rsandell
=> Log feedback for skipped stages

pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/BasicModelDefTest.java, pipeline-model-definition/src/test/resources/whenLaterStage.groovy, pipeline-model-definition/src/test/resources/whenLaterStages.groovy
Came up in conversation, decided it was worth having the test here
even though it works. =)
cc @reviewbybees esp @batmat @rsandell
=> Testing that stages after a skipped stage run right

pipeline-model-declarative-agent/src/main/java/org/jenkinsci/plugins/pipeline/modeldefinition/agent/DeclarativeAgent.java, pipeline-model-declarative-agent/src/main/java/org/jenkinsci/plugins/pipeline/modeldefinition/agent/DeclarativeAgentDescriptor.java, pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/model/Agent.groovy, pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/validator/ModelValidatorImpl.groovy, pipeline-model-definition/src/main/java/org/jenkinsci/plugins/pipeline/modeldefinition/agent/impl/DockerPipeline.java, pipeline-model-definition/src/main/resources/org/jenkinsci/plugins/pipeline/modeldefinition/ModelInterpreter.groovy, pipeline-model-definition/src/main/resources/org/jenkinsci/plugins/pipeline/modeldefinition/agent/impl/AbstractDockerPipelineScript.groovy, pipeline-model-definition/src/main/resources/org/jenkinsci/plugins/pipeline/modeldefinition/agent/impl/AnyScript.groovy, pipeline-model-definition/src/main/resources/org/jenkinsci/plugins/pipeline/modeldefinition/agent/impl/DockerPipelineFromDockerfileScript.groovy, pipeline-model-definition/src/main/resources/org/jenkinsci/plugins/pipeline/modeldefinition/agent/impl/LabelScript.groovy, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/steps/DeclarativePropsStepTest.java
[JENKINS-41050](https://issues.jenkins-ci.org/browse/JENKINS-41050)
cc @reviewbybees esp @michaelneale @rsandell @HRMPW
=> [JENKINS-41050] Always do SCM checkout directly on agent, not in container

pipeline-model-declarative-agent/src/main/java/org/jenkinsci/plugins/pipeline/modeldefinition/agent/DeclarativeAgent.java, pipeline-model-declarative-agent/src/main/java/org/jenkinsci/plugins/pipeline/modeldefinition/agent/DeclarativeAgentDescriptor.java, pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/model/Agent.groovy, pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/validator/ModelValidatorImpl.groovy, pipeline-model-definition/src/main/resources/org/jenkinsci/plugins/pipeline/modeldefinition/ModelInterpreter.groovy, pipeline-model-definition/src/main/resources/org/jenkinsci/plugins/pipeline/modeldefinition/agent/impl/AbstractDockerPipelineScript.groovy, pipeline-model-definition/src/main/resources/org/jenkinsci/plugins/pipeline/modeldefinition/agent/impl/AnyScript.groovy, pipeline-model-definition/src/main/resources/org/jenkinsci/plugins/pipeline/modeldefinition/agent/impl/LabelScript.groovy, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/AgentTest.java, pipeline-model-definition/src/test/resources/agentDockerDontReuseNode.groovy, pipeline-model-definition/src/test/resources/agentInStageAutoCheckout.groovy, pipeline-model-definition/src/test/resources/org/jenkinsci/plugins/pipeline/modeldefinition/agent/impl/LabelAndOtherFieldAgentScript.groovy
* [JENKINS-41900](https://issues.jenkins-ci.org/browse/JENKINS-41900)
* Description:
* Reduces dependency load for other plugins extending DeclarativeAgent. Relevant for [JENKINS-41758](https://issues.jenkins-ci.org/browse/JENKINS-41758)
* n/a - no user-facing impact.
* @rsandell
=> [FIXED JENKINS-41900] Expose doCheckout on DeclarativeAgent

pipeline-model-api/src/main/java/org/jenkinsci/plugins/pipeline/modeldefinition/ast/ModelASTValue.java, pipeline-model-api/src/main/resources/ast-schema.json, pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/parser/Converter.groovy, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/AbstractModelDefTest.java, pipeline-model-definition/src/test/resources/json/jsonSchemaNull.json, pipeline-model-definition/src/test/resources/jsonSchemaNull.groovy
* [JENKINS-41503](https://issues.jenkins-ci.org/browse/JENKINS-41503)
* Description:
* Makes sure another path can convert between Groovy and JSON without issues. Also required changing org.json -> Jackson conversion to go through a string rather than use a mapper due to the mapper not liking nulls at all.
* n/a
* @rsandell 
* @kzantow
=> [FIXED JENKINS-41503] Allow null values in JSON

pipeline-model-api/src/main/java/org/jenkinsci/plugins/pipeline/modeldefinition/ast/ModelASTWhen.java, pipeline-model-definition/src/main/resources/org/jenkinsci/plugins/pipeline/modeldefinition/when/impl/AnyOfConditionalScript.groovy, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/AbstractModelDefTest.java, pipeline-model-definition/src/test/resources/org/jenkinsci/plugins/pipeline/modeldefinition/agent/impl/LabelAndOtherFieldAgentScript.groovy
* n/a
* Description:
* Sigh. Whoops. Fixing.
* n/a
* @rsandell
=> Fix a pile of test failures I inadvertently merged

pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/parser/JSONParser.groovy, pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/parser/ModelParser.groovy, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/ValidatorTest.java, pipeline-model-definition/src/test/resources/errors/undefinedSectionReferencesCorrectly.groovy
* [JENKINS-42550](https://issues.jenkins-ci.org/browse/JENKINS-42550)
* Description:
* Doing so by switching to a placeholder ModelASTKey for the source location - previously we were just using the top-level ModelASTPipelineDef's source location.
* n/a
* @rsandell 
* @rtyler
=> [FIXED JENKINS-42550] Point to error in top-level sections

pipeline-model-definition/src/main/java/org/jenkinsci/plugins/pipeline/modeldefinition/agent/impl/DockerPipelineFromDockerfile.java, pipeline-model-definition/src/main/resources/org/jenkinsci/plugins/pipeline/modeldefinition/agent/impl/DockerPipelineFromDockerfileScript.groovy, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/AgentTest.java, pipeline-model-definition/src/test/resources/additionalDockerBuildArgs.groovy
* [JENKINS-42693](https://issues.jenkins-ci.org/browse/JENKINS-42693)
* Description:
* Allows specifying like
```groovy
dockerfile {
additionalBuildArgs "--build-arg someArg=someValue"
}
```
which will get added to the "docker build ..." command line call.
* [Doc PR](https://github.com/jenkins-infra/jenkins.io/pull/751)
* @rsandell
=> [FIXED JENKINS-42693] Add additionalBuildArgs dockerfile parameter

pipeline-model-definition/src/main/resources/org/jenkinsci/plugins/pipeline/modeldefinition/Messages_pt_BR.properties, pipeline-model-definition/src/main/resources/org/jenkinsci/plugins/pipeline/modeldefinition/model/conditions/Messages_pt_BR.properties
=> pt_BR translation 

pipeline-model-api/src/main/java/org/jenkinsci/plugins/pipeline/modeldefinition/ASTSchema.java, pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/parser/Converter.groovy, pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/parser/JSONParser.groovy, pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/validator/JSONErrorCollector.groovy, pipeline-model-definition/src/main/java/org/jenkinsci/plugins/pipeline/modeldefinition/endpoints/ModelConverterAction.java, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/BaseParserLoaderTest.java, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/validator/JSONSchemaTest.java, pipeline-model-json-shaded/pom.xml
* [JENKINS-43195](https://issues.jenkins-ci.org/browse/JENKINS-43195)
* Description:
* Avoids polluting classloaders for other uses.
* n/a
* @rsandell
=> [FIXED JENKINS-43195] Relocate shaded com.github.fge.*

pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/EnvironmentTest.java, pipeline-model-definition/src/test/resources/nonLiteralEnvironment.groovy
* [JENKINS-43681](https://issues.jenkins-ci.org/browse/JENKINS-43681)
* Description:
* Just adding a test to verify a known case works.
* n/a
* @rsandell 
=> [JENKINS-43681] Just verify that a simple expression works as well

pipeline-model-definition/src/main/resources/org/jenkinsci/plugins/pipeline/modeldefinition/ModelInterpreter.groovy, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/OptionsTest.java, pipeline-model-definition/src/test/resources/retryOptions.groovy
* [JENKINS-45270](https://issues.jenkins-ci.org/browse/JENKINS-45270)
* Description:
* Specifically this will make retry from the options directive actually work.
* n/a
=> [FIXED JENKINS-45270] Properly throw errors so wrappers can catch them.

pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/BasicModelDefTest.java, pipeline-model-definition/src/test/resources/parallelAndPostFailure.groovy
* [JENKINS-43625](https://issues.jenkins-ci.org/browse/JENKINS-43625)
* Description:
* So this matches the reported bug but does not reproduce it. Still thought it was worth adding the test anyway.
* n/a
=> [JENKINS-43625] Test attempting to reproduce bug - passes, though

pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/model/Tools.groovy, pipeline-model-definition/src/main/resources/org/jenkinsci/plugins/pipeline/modeldefinition/ModelInterpreter.groovy, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/ToolsTest.java, pipeline-model-definition/src/test/resources/toolsAndAgentNone.groovy
* [JENKINS-42338](https://issues.jenkins-ci.org/browse/JENKINS-42338)
* Description:
* If there's a top-level `tools` directive, make sure to install those tools on any `agent` specific to a `stage`. Override the root-level tools with any stage-level tool definitions of the same type.
* n/a
=> [FIXED JENKINS-42338] Install root-level tools on stage agents.

pipeline-model-definition/src/main/resources/org/jenkinsci/plugins/pipeline/modeldefinition/ModelInterpreter.groovy, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/PostStageTest.java, pipeline-model-definition/src/test/resources/postStage/withAgentNoneAndAgentAny.groovy, pipeline-model-definition/src/test/resources/postStage/withAgentNoneAndAgentDocker.groovy
When agent none is set globally and agent docker in the stage
* [JENKINS-46276](https://issues.jenkins-ci.org/browse/JENKINS-46276)
* Description:
* ...
* @abayer 
=> [FIXED JENKINS-46276] post stage not running inside stage agent block

pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/AbstractModelDefTest.java
Sometimes, when multiple tests are being run and...some other
condition applies (haven't figured out what, since I can't reproduce
it locally), the TestExtension in MultipleUnnamedParametersTest ends
up being present in other tests, most notably ErrorsEndpointOpsTest
and ErrorsJSONParserTest. Since we have to hardcode the expected error
in those tests, without it being calculated at the moment the test's
running, like ValidatorTest#invalidWrapperType, this can result in
failures where the list of valid options the test is expecting to see
is calculated before the TestExtension is added but the actual error
message is generated afterwards and so includes the TestExtension.
Since we have the full check including the list of valid types in
ValidatorTest, we might as well simplify the …
=> Tweak invalidWrapperType tests

pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/model/Tools.groovy, pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/parser/RuntimeASTTransformer.groovy, pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/validator/ModelValidatorImpl.groovy, pipeline-model-definition/src/main/resources/org/jenkinsci/plugins/pipeline/modeldefinition/ModelInterpreter.groovy, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/ToolsTest.java
* [JENKINS-44497](https://issues.jenkins-ci.org/browse/JENKINS-44497)
* Description:
* We can't validate those, obviously, but such is life.
* n/a
* @kshultzCB
=> [FIXED JENKINS-44497] Allow env vars and such in tools values.

pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/AgentTest.java, pipeline-model-definition/src/test/resources/agentDockerGlobalThenLabel.groovy
* n/a
* Description:
* I faced a problem when the agent on the global level is a Docker container and when the agent on the stage is a normal agent. This ends up with a very odd issue. I'd like to make sure it's coming from my end and not from the plugin.
* @abayer
=> [JENKINS-46831] Test behaviour when agent defined globally and on stage

pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/parser/ModelParser.groovy
* n/a
* Description:
* Too much logging, let's cut down. =)
* n/a
=> Stop logging so much in hpi:run

pipeline-model-definition/pom.xml, pom.xml
* n/a
* Description:
* Gets us onto the most recent `plugin` parent version, fixes various upper bounds related dependency issues resulting from that.
* n/a
* @kshultzCB
=> Bump to plugin parent 2.35, fix upperBoundsDep issues

pipeline-model-definition/src/main/java/org/jenkinsci/plugins/pipeline/modeldefinition/steps/ScriptStep.java, pom.xml
Downstream of https://github.com/jenkinsci/workflow-step-api-plugin/pull/30.
@reviewbybees
=> [JENKINS-26148] Using default implementation of StepExecution.stop

pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/BasicModelDefTest.java, pipeline-model-definition/src/test/resources/parallelStagesHaveStatusWhenSkipped.groovy
* [JENKINS-47783](https://issues.jenkins-ci.org/browse/JENKINS-47783)
* Description:
* Just verifying that yes, we are properly applying skipped stage status metadata for parallel stages.
* n/a
=> [JENKINS-47783] Verify skipped stage status for parallel stages

pipeline-model-api/src/main/java/org/jenkinsci/plugins/pipeline/modeldefinition/ast/ModelASTValue.java, pipeline-model-api/src/main/java/org/jenkinsci/plugins/pipeline/modeldefinition/validator/ModelValidator.java, pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/validator/ModelValidatorImpl.groovy, pipeline-model-extensions/src/main/java/org/jenkinsci/plugins/pipeline/modeldefinition/validator/DeclarativeValidatorContributor.java
* n/a
* Description:
* No-op currently, but this'll allow a DeclarativeValidatorContributor to do more specific validation of a ModelASTValue in the future.
* n/a
=> Add validation hook for ModelASTValue

pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/parser/Converter.groovy, pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/parser/ModelParser.groovy, pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/validator/ModelValidatorImpl.groovy, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/ValidatorTest.java, pipeline-model-extensions/src/main/java/org/jenkinsci/plugins/pipeline/modeldefinition/validator/DeclarativeValidatorContributor.java
* n/a
* Description:
* I've got a potential use case for this in some awfully speculative stuff, but this won't cause any harm and lets us be more flexible in some cases for validation down the road.
* n/a
=> Add the ability to make validator contributors optional.

pipeline-model-definition/src/main/resources/org/jenkinsci/plugins/pipeline/modeldefinition/agent/impl/DockerPipelineFromDockerfileScript.groovy
* [JENKINS-49677](https://issues.jenkins-ci.org/browse/JENKINS-49677)
* Description:
* Better de-duplication of Dockerfile tags is a good thing, so let's do it.
* n/a
=> [FIXED JENKINS-49677] Include full project name in hash for Dockerfile tag

pipeline-model-api/src/main/java/org/jenkinsci/plugins/pipeline/modeldefinition/ast/ModelASTValue.java
* [JENKINS-49976](https://issues.jenkins-ci.org/browse/JENKINS-49976)
* Description:
* Based on other PRs I've seen, getting rid of the anonymous classes seems to do the trick to get rid of the warnings. So.
* n/a
=> [FIXED JENKINS-49976] Get rid of ModelASTValue anonymous classes

pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/model/Agent.groovy, pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/validator/ModelValidatorImpl.groovy, pipeline-model-definition/src/main/java/org/jenkinsci/plugins/pipeline/modeldefinition/generator/AgentDirective.java, pipeline-model-extensions/src/main/java/org/jenkinsci/plugins/pipeline/modeldefinition/agent/DeclarativeAgentDescriptor.java
* [JENKINS-50833](https://issues.jenkins-ci.org/browse/JENKINS-50833)
* Description:
* This was an oopsie in the first place, easy enough to fix.
* n/a
* ...
=> [FIXED JENKINS-50833] Revert DeclarativeAgentDescriptor.all() signature

pipeline-model-definition/src/main/java/org/jenkinsci/plugins/pipeline/modeldefinition/generator/WhenDirective.java, pipeline-model-definition/src/main/java/org/jenkinsci/plugins/pipeline/modeldefinition/when/impl/BuildingTagConditional.java, pipeline-model-definition/src/main/java/org/jenkinsci/plugins/pipeline/modeldefinition/when/impl/ChangeRequestConditional.java, pipeline-model-definition/src/main/java/org/jenkinsci/plugins/pipeline/modeldefinition/when/impl/TagConditional.java, pipeline-model-definition/src/main/resources/org/jenkinsci/plugins/pipeline/modeldefinition/generator/WhenDirective/config.jelly, pipeline-model-definition/src/main/resources/org/jenkinsci/plugins/pipeline/modeldefinition/when/impl/ChangeRequestConditional/config.jelly
* [JENKINS-50682](https://issues.jenkins-ci.org/browse/JENKINS-50682)
* Description:
* Also add display name for a few `when` conditions, move all of `ChangeRequestConditional`'s fields into "advanced", since they're optional and all, and smack things around a bit internally to not display `when` directive parameters when they're not required and they've got an empty string value.
* n/a
=> [FIXED JENKINS-50682] Actually pass descriptor to when condition forms

pipeline-model-definition/src/main/java/org/jenkinsci/plugins/pipeline/modeldefinition/generator/DirectiveGenerator.java
* [JENKINS-50882](https://issues.jenkins-ci.org/browse/JENKINS-50882)
* Description:
* Sigh - I didn't realize that Snippetizer actually had to do the same thing in three places (well, more accurately, two of those are in workflow-multibranch but are otherwise identical to what's in Snippetizer). So here are `TransientActionFactory`s added for `OrganizationFolder` and `WorkflowMultiBranchProject` (aka multibranch folder), and a refinement of the `WorkflowJob` one too.
* n/a
=> [FIXED JENKINS-50882] Make generator work on multibranch and org folders

pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/model/Options.groovy, pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/model/StageOptions.groovy, pipeline-model-definition/src/main/java/org/jenkinsci/plugins/pipeline/modeldefinition/generator/OptionsDirective.java, pipeline-model-extensions/src/main/java/org/jenkinsci/plugins/pipeline/modeldefinition/options/DeclarativeOptionDescriptor.java
* n/a
* Description:
* No concrete use case for this right now, but I've got some possibilities I'm brewing that would want this elsewhere, so let's get it in so that it'll be available in 1.2.8.
* n/a
* ...
=> Allow stage-only DeclarativeOptions

pipeline-model-definition/src/main/resources/org/jenkinsci/plugins/pipeline/modeldefinition/ModelInterpreter.groovy, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/BasicModelDefTest.java, pipeline-model-definition/src/test/resources/failureInFirstOfSequential.groovy
* [JENKINS-51962](https://issues.jenkins-ci.org/browse/JENKINS-51962)
* Description:
* I feel goofy that I missed this originally, but here's the fix. Note that we're not bothering with this in `skipStage`, because that can't actually result in errors anyway.
* n/a
* ...
=> [FIXED JENKINS-51962] Propagate errors from nested sequential stages

pipeline-model-definition/src/main/java/org/jenkinsci/plugins/pipeline/modeldefinition/generator/DirectiveGenerator.java, pom.xml
=> Bump plugin parent, branch-api, scm-api to fix PCT

pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/model/conditions/Cleanup.groovy, pipeline-model-definition/src/main/resources/org/jenkinsci/plugins/pipeline/modeldefinition/model/conditions/Messages.properties, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/generator/DirectiveGeneratorTest.java
* [JENKINS-51027](https://issues.jenkins-ci.org/browse/JENKINS-51027)
* Description:
* This fixes the Directive Generator for post conditions.
* n/a
* ...
=> [FIXED JENKINS-51027] Fix descriptions on build conditions

pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/parser/Converter.groovy
=> Fixing a typo =)

pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/parser/ASTParserUtils.groovy, pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/parser/RuntimeASTTransformer.groovy, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/EnvironmentTest.java, pipeline-model-definition/src/test/resources/notExpressionInEnvironment.groovy, pom.xml
* [JENKINS-54047](https://issues.jenkins-ci.org/browse/JENKINS-54047)
* Description:
* Distinguish between `NotExpression` and `BooleanExpression` because sigh, I was dumb.
* n/a
* ...
=> [FIXED JENKINS-54047] Handle ! in env values

Jenkinsfile
* n/a
* Description:
* Of course `'${TEST_TIMEOUT}'` wouldn't actually do anything useful on Windows.
* n/a
* ...
=> Fix test timeout in Jenkinsfile

pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/Utils.groovy, pipeline-model-definition/src/main/java/org/jenkinsci/plugins/pipeline/modeldefinition/when/impl/TriggeredByConditional.java, pipeline-model-definition/src/main/resources/org/jenkinsci/plugins/pipeline/modeldefinition/when/impl/TriggeredByConditional/config.jelly, pipeline-model-definition/src/main/resources/org/jenkinsci/plugins/pipeline/modeldefinition/when/impl/TriggeredByConditional/help-compare.html, pipeline-model-definition/src/main/resources/org/jenkinsci/plugins/pipeline/modeldefinition/when/impl/TriggeredByConditional/help.html, pipeline-model-definition/src/main/resources/org/jenkinsci/plugins/pipeline/modeldefinition/when/impl/TriggeredByConditionalScript.groovy, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/BasicModelDefTest.java, pipeline-model-definition/src/test/resources/BuildStatusWhen.groovy, pipeline-model-definition/src/test/resources/buildStatusWhenSCMTrigger.groovy, pipeline-model-definition/src/test/resources/buildStatusWhenTimerTrigger.groovy, pipeline-model-definition/src/test/resources/buildStatusWhenUserIdCause.groovy, pom.xml
*https://issues.jenkins-ci.org/browse/JENKINS-46894
* Description:
* Provide means of detecting cause of build from declarative pipeline
* https://github.com/jenkins-infra/jenkins.io/pull/1925
* N/A
=> [Jenkins-46894] Adding triggeredBy when condition

pipeline-model-definition/src/main/java/org/jenkinsci/plugins/pipeline/modeldefinition/agent/DeclarativeDockerUtils.java, pipeline-model-definition/src/main/resources/org/jenkinsci/plugins/pipeline/modeldefinition/agent/impl/AbstractDockerPipelineScript.groovy, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/AgentTest.java, pipeline-model-definition/src/test/resources/agentDockerWithCreds.groovy
* https://issues.jenkins-ci.org/browse/JENKINS-49950
* Description:
* Specifying Docker registry credentials should not silently fail if using default URL
* https://github.com/jenkins-infra/jenkins.io/pull/1978
* ...
=> JENKINS-49950 Allowing to use dockerhub credentials

pipeline-model-definition/src/main/resources/org/jenkinsci/plugins/pipeline/modeldefinition/generator/EnvironmentDirective/config.jelly, pipeline-model-definition/src/main/resources/org/jenkinsci/plugins/pipeline/modeldefinition/generator/LibrariesDirective/config.jelly, pipeline-model-definition/src/main/resources/org/jenkinsci/plugins/pipeline/modeldefinition/generator/StageDirective/config.jelly
* [JENKINS-56372](https://issues.jenkins-ci.org/browse/JENKINS-56372)
* Description:
* ...
* ...
=> [JENKINS-56372] Make it easier to distinguish Name from Value

pipeline-model-definition/src/main/resources/org/jenkinsci/plugins/pipeline/modeldefinition/agent/impl/DockerPipeline/config.jelly, pipeline-model-definition/src/main/resources/org/jenkinsci/plugins/pipeline/modeldefinition/agent/impl/DockerPipelineFromDockerfile/config.jelly, pipeline-model-definition/src/main/resources/org/jenkinsci/plugins/pipeline/modeldefinition/generator/WhenDirective/config.jelly, pipeline-model-definition/src/main/resources/org/jenkinsci/plugins/pipeline/modeldefinition/options/impl/SkipDefaultCheckout/config.jelly, pipeline-model-definition/src/main/resources/org/jenkinsci/plugins/pipeline/modeldefinition/when/impl/ChangeSetConditional/config.jelly, pipeline-model-definition/src/main/resources/org/jenkinsci/plugins/pipeline/modeldefinition/when/impl/EnvironmentConditional/config.jelly
* [JENKINS-55787](https://issues.jenkins-ci.org/browse/JENKINS-55787)
* Description:
* ...
* ...
=> [JENKINS-55787] Switch labels from entry to checkbox

pipeline-model-definition/src/main/java/org/jenkinsci/plugins/pipeline/modeldefinition/credentials/impl/SSHUserPrivateKeyHandler.java, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/steps/CredentialWrapperStepTest.java, pipeline-model-definition/src/test/resources/noBinding.groovy, pipeline-model-definition/src/test/resources/sshCredentialsInEnv.groovy
* [JENKINS-52850](https://issues.jenkins-ci.org/browse/JENKINS-52850)
* Description:
* Add a credentials helper for SSH with Private Key credentials
* https://github.com/jenkins-infra/jenkins.io/pull/2171
* @abayer
=> [JENKINS-52850] Add credentials helper for SSH with Private Key

pipeline-model-definition/src/main/resources/org/jenkinsci/plugins/pipeline/modeldefinition/generator/DirectiveGenerator/symbol-hetero-list.jelly, pipeline-model-definition/src/main/resources/org/jenkinsci/plugins/pipeline/modeldefinition/generator/ToolsDirective/config.jelly
* [JENKINS-56832](https://issues.jenkins-ci.org/browse/JENKINS-56832)
* Description:
* Simplification of the correction applied after SECURITY-624
* (internal change only)
* @abayer
Explanation of the reasons why I think this PR could be useful.
=> [JENKINS-56832] Simplify the jelly corrections due to SEC-624

pipeline-model-api/src/main/java/org/jenkinsci/plugins/pipeline/modeldefinition/ast/ModelASTParallel.java, pipeline-model-api/src/main/java/org/jenkinsci/plugins/pipeline/modeldefinition/ast/ModelASTStage.java, pipeline-model-api/src/main/java/org/jenkinsci/plugins/pipeline/modeldefinition/ast/ModelASTStages.java, pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/model/Parallel.groovy, pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/model/Stage.groovy, pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/parser/JSONParser.groovy, pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/parser/ModelParser.groovy, pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/parser/RuntimeASTTransformer.groovy, pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/validator/ModelValidatorImpl.groovy, pipeline-model-definition/src/main/resources/org/jenkinsci/plugins/pipeline/modeldefinition/ModelInterpreter.groovy, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/DeclarativeUpgradeTest.java
=>  Create serial and parallel stages classes

Jenkinsfile, pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/Utils.groovy, pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/model/conditions/Changed.groovy, pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/model/conditions/Failure.groovy, pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/model/conditions/Fixed.groovy, pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/model/conditions/NotBuilt.groovy, pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/model/conditions/Regression.groovy, pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/model/conditions/Success.groovy, pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/model/conditions/Unstable.groovy, pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/model/conditions/Unsuccessful.groovy, pipeline-model-definition/src/main/resources/org/jenkinsci/plugins/pipeline/modeldefinition/ModelInterpreter.groovy, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/AgentTest.java, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/BasicModelDefTest.java, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/OptionsTest.java, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/ParallelTest.java, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/PostStageTest.java, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/actions/RestartDeclarativePipelineActionTest.java, pipeline-model-definition/src/test/resources/parallel/parallelStagesFailFastWithAgent.groovy, pipeline-model-definition/src/test/resources/postStage/catchErrorStageAborted.groovy, pipeline-model-definition/src/test/resources/postStage/catchErrorStageFailure.groovy, pipeline-model-definition/src/test/resources/postStage/catchErrorStageFailureNested.groovy, pipeline-model-definition/src/test/resources/postStage/catchErrorStageNotBuilt.groovy, pipeline-model-definition/src/test/resources/postStage/catchErrorStageUnstable.groovy, pipeline-model-definition/src/test/resources/postStage/catchErrorStageUnstableBuildFailure.groovy, pipeline-model-definition/src/test/resources/postStage/warnErrorStageUnstable.groovy, pipeline-model-extensions/pom.xml, pipeline-model-extensions/src/main/java/org/jenkinsci/plugins/pipeline/modeldefinition/CommonUtils.java, pipeline-model-extensions/src/main/java/org/jenkinsci/plugins/pipeline/modeldefinition/model/BuildCondition.java, pom.xml
* [JENKINS-57826](https://issues.jenkins-ci.org/browse/JENKINS-57826)
* Description:
* This probably needs `StatusAndTiming#findWarningBetween` to be made public rather than copy-pasting here.
* ...
=> [FIXED JENKINS-57826] Post should handle catchError stageResult

pipeline-model-api/src/main/java/org/jenkinsci/plugins/pipeline/modeldefinition/ast/ModelASTAgent.java, pipeline-model-api/src/main/java/org/jenkinsci/plugins/pipeline/modeldefinition/ast/ModelASTBranch.java, pipeline-model-api/src/main/java/org/jenkinsci/plugins/pipeline/modeldefinition/ast/ModelASTBuildCondition.java, pipeline-model-api/src/main/java/org/jenkinsci/plugins/pipeline/modeldefinition/ast/ModelASTBuildConditionsContainer.java, pipeline-model-api/src/main/java/org/jenkinsci/plugins/pipeline/modeldefinition/ast/ModelASTBuildParameters.java, pipeline-model-api/src/main/java/org/jenkinsci/plugins/pipeline/modeldefinition/ast/ModelASTClosureMap.java, pipeline-model-api/src/main/java/org/jenkinsci/plugins/pipeline/modeldefinition/ast/ModelASTElement.java, pipeline-model-api/src/main/java/org/jenkinsci/plugins/pipeline/modeldefinition/ast/ModelASTElementContainer.java, pipeline-model-api/src/main/java/org/jenkinsci/plugins/pipeline/modeldefinition/ast/ModelASTEnvironment.java, pipeline-model-api/src/main/java/org/jenkinsci/plugins/pipeline/modeldefinition/ast/ModelASTInternalFunctionCall.java, pipeline-model-api/src/main/java/org/jenkinsci/plugins/pipeline/modeldefinition/ast/ModelASTKeyValueOrMethodCallPair.java, pipeline-model-api/src/main/java/org/jenkinsci/plugins/pipeline/modeldefinition/ast/ModelASTLibraries.java, pipeline-model-api/src/main/java/org/jenkinsci/plugins/pipeline/modeldefinition/ast/ModelASTMatrix.java, pipeline-model-api/src/main/java/org/jenkinsci/plugins/pipeline/modeldefinition/ast/ModelASTMethodCall.java, pipeline-model-api/src/main/java/org/jenkinsci/plugins/pipeline/modeldefinition/ast/ModelASTNamedArgumentList.java, pipeline-model-api/src/main/java/org/jenkinsci/plugins/pipeline/modeldefinition/ast/ModelASTOptions.java, pipeline-model-api/src/main/java/org/jenkinsci/plugins/pipeline/modeldefinition/ast/ModelASTParallel.java, pipeline-model-api/src/main/java/org/jenkinsci/plugins/pipeline/modeldefinition/ast/ModelASTPipelineDef.java, pipeline-model-api/src/main/java/org/jenkinsci/plugins/pipeline/modeldefinition/ast/ModelASTPositionalArgumentList.java, pipeline-model-api/src/main/java/org/jenkinsci/plugins/pipeline/modeldefinition/ast/ModelASTSingleArgument.java, pipeline-model-api/src/main/java/org/jenkinsci/plugins/pipeline/modeldefinition/ast/ModelASTStage.java, pipeline-model-api/src/main/java/org/jenkinsci/plugins/pipeline/modeldefinition/ast/ModelASTStageInput.java, pipeline-model-api/src/main/java/org/jenkinsci/plugins/pipeline/modeldefinition/ast/ModelASTStages.java, pipeline-model-api/src/main/java/org/jenkinsci/plugins/pipeline/modeldefinition/ast/ModelASTStep.java, pipeline-model-api/src/main/java/org/jenkinsci/plugins/pipeline/modeldefinition/ast/ModelASTTools.java, pipeline-model-api/src/main/java/org/jenkinsci/plugins/pipeline/modeldefinition/ast/ModelASTTreeStep.java, pipeline-model-api/src/main/java/org/jenkinsci/plugins/pipeline/modeldefinition/ast/ModelASTTriggers.java, pipeline-model-api/src/main/java/org/jenkinsci/plugins/pipeline/modeldefinition/ast/ModelASTWhen.java, pipeline-model-api/src/main/java/org/jenkinsci/plugins/pipeline/modeldefinition/ast/ModelASTWhenCondition.java, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/MatrixTest.java
* n/a
* Description:
* Refactor of AST methods to reduce repeated code and improve understandability.
* Not a notable changed externally unless we want to document the added static helpers
* @dwnusbaum
=> Refactor Model AST methods to reduce repeated code

pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/Utils.groovy, pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/parser/Converter.groovy, pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/parser/ModelParser.groovy, pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/parser/RuntimeASTTransformer.groovy, pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/validator/ModelValidatorImpl.groovy, pom.xml
* N/A
* Description:
* Based on a comment from @jglick I figured I'd see if gmaven-plus could work for us (and unblock java 11 build).  Probably not, but can't hurt to check.
* ...
=> Switch to gmavenplus to build groovy

Jenkinsfile, pipeline-model-definition/pom.xml, pom.xml
=> Java 11 Experiment

pipeline-model-api/src/main/java/org/jenkinsci/plugins/pipeline/modeldefinition/ast/ModelASTExclude.java, pipeline-model-api/src/main/java/org/jenkinsci/plugins/pipeline/modeldefinition/ast/ModelASTExcludeAxis.java, pipeline-model-api/src/main/java/org/jenkinsci/plugins/pipeline/modeldefinition/ast/ModelASTExcludes.java, pipeline-model-api/src/main/java/org/jenkinsci/plugins/pipeline/modeldefinition/ast/ModelASTMatrix.java, pipeline-model-api/src/main/java/org/jenkinsci/plugins/pipeline/modeldefinition/validator/ModelValidator.java, pipeline-model-api/src/main/resources/ast-schema.json, pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/parser/JSONParser.groovy, pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/parser/ModelParser.groovy, pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/parser/RuntimeASTTransformer.groovy, pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/validator/ModelValidatorImpl.groovy, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/AbstractModelDefTest.java, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/MatrixTest.java, pipeline-model-definition/src/test/resources/json/matrix/matrixPipelineTwoAxis.json, pipeline-model-definition/src/test/resources/json/matrix/matrixPipelineTwoAxisExcludeNot.json, pipeline-model-definition/src/test/resources/json/matrix/matrixPipelineTwoAxisOneExclude.json, pipeline-model-definition/src/test/resources/json/matrix/matrixPipelineTwoAxisTwoExcludes.json, pipeline-model-definition/src/test/resources/matrix/matrixPipelineTwoAxisExcludeNot.groovy, pipeline-model-definition/src/test/resources/matrix/matrixPipelineTwoAxisOneExclude.groovy, pipeline-model-definition/src/test/resources/matrix/matrixPipelineTwoAxisTwoExcludes.groovy
Does not include not operator for values.
Using a simplistic representation of ExcludeAxis elements.
=> Added excludes directive to matrix

pipeline-model-definition/src/main/resources/org/jenkinsci/plugins/pipeline/modeldefinition/agent/impl/DockerPipelineFromDockerfileScript.groovy
* [JENKINS-47703](https://issues.jenkins-ci.org/browse/JENKINS-47703)
* Description:
* Support docker image build on Windows, related to https://github.com/jenkinsci/docker-workflow-plugin/pull/184
* N/A
* @bitwiseman
=> [JENKINS-47703] - allow building dockerfile on Windows

README.md
Documentation improvments: Updated: README.md Added: Contributors badge #hacktoberfest
=> Documentation improvments #hacktoberfest

CHANGELOG.md, DEV_GUIDE.md, README.md, pom.xml
* Moving documentation and changelog to github
@dwnusbaum @car-roll @kshultzCB @olamy
=> Move plugin URL to github

pipeline-model-definition/src/main/java/org/jenkinsci/plugins/pipeline/modeldefinition/when/impl/BranchConditional.java, pipeline-model-definition/src/main/resources/org/jenkinsci/plugins/pipeline/modeldefinition/when/impl/BranchConditional/help-comparator.html, pipeline-model-definition/src/main/resources/org/jenkinsci/plugins/pipeline/modeldefinition/when/impl/BranchConditional/help-pattern.html, pipeline-model-definition/src/main/resources/org/jenkinsci/plugins/pipeline/modeldefinition/when/impl/BranchConditionalScript.groovy, pipeline-model-definition/src/main/resources/org/jenkinsci/plugins/pipeline/modeldefinition/when/impl/ChangeRequestConditional/help-comparator.html, pipeline-model-definition/src/main/resources/org/jenkinsci/plugins/pipeline/modeldefinition/when/impl/TagConditional/help-comparator.html, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/WhenStageMultibranchTest.java, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/when/utils/ComparatorTest.java, pipeline-model-definition/src/test/resources/when/whenBranch.groovy
* [JENKINS-59115](https://issues.jenkins-ci.org/browse/JENKINS-59115)
* Description:
* Support the comparator for the branch as already done with the tag one in https://github.com/jenkinsci/pipeline-model-definition-plugin/pull/240
* `help-*.html`.
* https://github.com/jenkins-infra/jenkins.io/pull/2450
* @rsandell
* @abayer 
* @jenkinsci/code-reviewers
=> [JENKINS-59115] Support comparator for the when branch

pipeline-model-api/pom.xml, pipeline-model-definition/pom.xml, pipeline-model-extensions/pom.xml, pipeline-stage-tags-metadata/pom.xml, pom.xml
I think #364 broke the incrementalification I did in #336.
=> <tag>${scmTag}</tag>

README.md
* n/a
* Description:
* Fix GitHub rendering of developing section of readme 
* ...
* ...
=> Fix Developing markdown for README

Jenkinsfile, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/AbstractModelDefTest.java, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/util/HasArchived.java, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/util/InputStreamContainingString.java, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/util/IsJsonObjectContaining.java, pom.xml
Trying just plugin-pom-4.1 minimal update.
=> Update to plugin-pom 4.1

pipeline-model-definition/src/main/resources/org/jenkinsci/plugins/pipeline/modeldefinition/generator/AgentDirective/config.jelly
See [JENKINS-62177](https://issues.jenkins-ci.org/browse/JENKINS-62177)
@bitwiseman
=> [JENKINS-62177] Pass descriptor in context for DeclarativeAgent descriptors

pipeline-model-definition/pom.xml, pipeline-model-definition/src/main/java/org/jenkinsci/plugins/pipeline/modeldefinition/generator/DirectiveGenerator.java, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/generator/DirectiveGeneratorTest.java, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/generator/DirectiveGeneratorTester.java, pom.xml
* Fix DirectiveGenerator support of nested describables
Downstream of https://github.com/jenkinsci/workflow-cps-plugin/pull/362
=> Fix DirectiveGenerator support of nested describables / improve testing

pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/StageInputTest.java
* https://issues.jenkins-ci.org/browse/JENKINS-62808
* Description:
* Fixes tests when running with form layout changes to divs, backwards compatible change.
* @bitwiseman @dwnusbaum @fqueiruga
=> JENKINS-62808 Fix tests when using tables to divs

pipeline-model-api/pom.xml, pom.xml
=> Use bom for more dependencies including Jackson

Jenkinsfile
=> Remove UseAci

pom.xml
=> Update to 2.222.x LTS

Jenkinsfile
=> Test 2.289.x LTS in Jenkinsfile

pom.xml
=> Update dependencies to BOM versions

pom.xml
Picks up https://github.com/jenkinsci/plugin-pom/pull/426.
=> [JENKINS-66247] Use an annotation index compatible with the core baseline

pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/DeclarativePipelineTest.java
* JENKINS-66247 made it into the release because we didn't have even one RealJenkinsRule smoke test.  This PR adds one. 
* Description:
* ...
* ...
=> [JENKINS-66247] Add a RealJenkinsRule test

pipeline-model-api/pom.xml, pipeline-model-api/src/main/java/org/jenkinsci/plugins/pipeline/modeldefinition/ASTSchema.java, pipeline-model-definition/pom.xml, pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/Utils.groovy, pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/parser/Converter.groovy, pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/parser/JSONParser.groovy, pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/validator/JSONErrorCollector.groovy, pipeline-model-definition/src/main/java/org/jenkinsci/plugins/pipeline/modeldefinition/endpoints/ModelConverterAction.java, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/AbstractModelDefTest.java, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/BaseParserLoaderTest.java, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/actions/RestartDeclarativePipelineActionTest.java, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/validator/JSONSchemaTest.java, pipeline-model-extensions/pom.xml, pipeline-model-extensions/src/main/java/org/jenkinsci/plugins/pipeline/modeldefinition/CommonUtils.java, pipeline-stage-tags-metadata/pom.xml, pom.xml
Downstream of jenkinsci/jenkins#5707.
=> Bump `json-schema-validator` from 2.0.4 to 2.2.14

pipeline-model-api/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/DescriptorLookupCacheTest.java, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/generator/DirectiveGeneratorTester.java
=> EOL JSR 305

pipeline-model-definition/pom.xml, pom.xml
includes #479 as needed to try and get a full CI run.
=> optimize memory usage to remove test failures

pipeline-model-definition/pom.xml, pom.xml
This reverts commit 573bae01baf906b2f5aacad3da4e33387da3656f.
Identifying #498 as the cause of the recent windows CI failures
* Description:
* ...
* ...
=> Revert "Update plugin parent POM and plugin BOM"

EXTENDING.md
Rather than "master" use "controller"
~Ensure you have provided tests - that demonstrate the feature works or fixes the issue~
=> Make a comment more inclusive

pipeline-model-definition/src/main/resources/org/jenkinsci/plugins/pipeline/modeldefinition/generator/DirectiveGenerator/index.jelly, pipeline-model-definition/src/main/resources/org/jenkinsci/plugins/pipeline/modeldefinition/generator/DirectiveGenerator/indexScript.js
* [JENKINS-70695](https://issues.jenkins.io/browse/JENKINS-70695)
* Description:
* Add a copy to clipboard button below the text field with the generated code.
=> [JENKINS-70695] add copy to clipboard button for declarative generator

pipeline-model-api/pom.xml
=> Use joda-time api plugin

pipeline-model-definition/pom.xml
=> Removing gratuitous dep on `git-client`

pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/ParallelTest.java, pipeline-model-definition/src/test/resources/parallel/parallelErrorPost.groovy, pom.xml
https://issues.jenkins.io/browse/JENKINS-73726 presumably caused by https://github.com/jenkinsci/workflow-cps-plugin/pull/925
=> [JENKINS-73726] Reproduced error in test

pipeline-model-definition/src/main/java/org/jenkinsci/plugins/pipeline/modeldefinition/Upgrade.java, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/UpgradeTest.java
Not sure whether we really care, but this is one way to address https://github.com/jenkinsci/pipeline-model-definition-plugin/pull/770#discussion_r2223511515.
=> Extend serial compatibility fix to apply after multiple restarts

pipeline-model-api/pom.xml, pipeline-model-api/src/main/java/org/jenkinsci/plugins/pipeline/modeldefinition/ast/AbstractModelASTCodeBlock.java, pipeline-model-api/src/main/java/org/jenkinsci/plugins/pipeline/modeldefinition/ast/ModelASTAxis.java, pipeline-model-api/src/main/java/org/jenkinsci/plugins/pipeline/modeldefinition/ast/ModelASTPipelineDef.java, pipeline-model-api/src/main/java/org/jenkinsci/plugins/pipeline/modeldefinition/ast/ModelASTStage.java, pipeline-model-api/src/main/java/org/jenkinsci/plugins/pipeline/modeldefinition/ast/ModelASTStageBase.java, pipeline-model-definition/pom.xml, pipeline-model-definition/src/main/java/org/jenkinsci/plugins/pipeline/modeldefinition/agent/impl/Label.java, pipeline-model-definition/src/main/java/org/jenkinsci/plugins/pipeline/modeldefinition/endpoints/ModelConverterAction.java, pipeline-model-definition/src/main/java/org/jenkinsci/plugins/pipeline/modeldefinition/generator/InputDirective.java, pipeline-model-definition/src/main/java/org/jenkinsci/plugins/pipeline/modeldefinition/generator/LibrariesDirective.java, pipeline-model-definition/src/main/java/org/jenkinsci/plugins/pipeline/modeldefinition/generator/StageDirective.java, pipeline-model-definition/src/main/java/org/jenkinsci/plugins/pipeline/modeldefinition/generator/ToolsDirective.java, pipeline-model-definition/src/main/java/org/jenkinsci/plugins/pipeline/modeldefinition/steps/ValidateDeclarativePipelineStep.java, pipeline-model-definition/src/main/java/org/jenkinsci/plugins/pipeline/modeldefinition/when/impl/BranchConditional.java, pipeline-model-definition/src/main/java/org/jenkinsci/plugins/pipeline/modeldefinition/when/impl/ChangeRequestConditional.java, pipeline-model-definition/src/main/java/org/jenkinsci/plugins/pipeline/modeldefinition/when/impl/EnvironmentConditional.java, pipeline-model-definition/src/main/java/org/jenkinsci/plugins/pipeline/modeldefinition/when/impl/TagConditional.java, pipeline-model-definition/src/main/java/org/jenkinsci/plugins/pipeline/modeldefinition/when/utils/Comparator.java, pipeline-model-definition/src/main/java/org/jenkinsci/plugins/pipeline/modeldefinition/when/utils/EnvironmentNames.java, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/AbstractDeclarativeTest.java, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/AbstractModelDefTest.java, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/MatrixTest.java, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/ParallelTest.java, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/StageInputTest.java, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/ValidatorTest.java, pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/util/HasArchived.java, pipeline-model-extensions/pom.xml, pipeline-model-extensions/src/main/java/org/jenkinsci/plugins/pipeline/modeldefinition/model/CredentialsBindingHandler.java, pipeline-model-extensions/src/main/java/org/jenkinsci/plugins/pipeline/modeldefinition/withscript/WithScriptDescribable.java
Migrate from deprecated/EOL Commons Lang 2 to Commons Lang 3.
=> Upgrade Commons Lang from 2 to 3
